run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional linters
    - bodyclose
    - dogsled
    - dupl
    - errorlint
    - exhaustive
    - exportloopref
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tparallel
    - unconvert
    - unparam
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 20

  gocognit:
    min-complexity: 30

  dupl:
    threshold: 150

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  revive:
    rules:
      - name: exported
        disabled: true  # Allow unexported return types

  gosec:
    excludes:
      - G104  # Audit errors not checked (too noisy for TUI)
      - G304  # File path provided as taint input (expected for dotfiles)

issues:
  exclude-rules:
    # Test files can have longer functions
    - path: _test\.go
      linters:
        - gocyclo
        - gocognit
        - dupl

    # UI files tend to have longer functions
    - path: internal/ui/
      linters:
        - gocyclo
        - gocognit
        - dupl

    # Allow fmt.Print in CLI
    - path: cmd/
      linters:
        - forbidigo

  max-issues-per-linter: 50
  max-same-issues: 10
