package tools

import (
	"bytes"
	"errors"
	"fmt"
	"sort"
	"strings"

	"github.com/tekierz/dotfiles/internal/operation"
	"github.com/tekierz/dotfiles/internal/pkg"
	"github.com/tekierz/dotfiles/internal/safefile"
	"github.com/tekierz/dotfiles/internal/theme"
)

// BtopConfig holds btop configuration settings
type BtopConfig struct {
	Theme     string // "auto", "Default", "TTY", custom theme name
	UpdateMs  int    // Update interval in milliseconds
	ShowTemp  bool   // Show temperature sensors
	GraphType string // "braille", "block", "tty"

	TempScale  string // "celsius", "fahrenheit"
	ShownBoxes string // e.g. "cpu mem net proc"
}

// BtopTool represents btop system monitor
type BtopTool struct {
	BaseTool
}

// NewBtopTool creates a new btop tool
func NewBtopTool() *BtopTool {
	configPath, err := BtopConfigMutationPath()
	var configPaths []string
	if err == nil {
		configPaths = []string{configPath}
	}
	return &BtopTool{
		BaseTool: BaseTool{
			id:          "btop",
			name:        "btop",
			description: "Resource monitor with TUI",
			icon:        "󰄨",
			category:    CategoryUtility,
			packages: map[pkg.Platform][]string{
				pkg.PlatformMacOS:  {"btop"},
				pkg.PlatformArch:   {"btop"},
				pkg.PlatformDebian: {"btop"},
			},
			configPaths: configPaths,
			heavyTool:   true, // Skip on low-memory systems (Pi Zero 2)
			// UI metadata
			uiGroup:        UIGroupCLITools,
			configScreen:   30, // ScreenConfigBtop - has dedicated config screen
			defaultEnabled: true,
		},
	}
}

func (t *BtopTool) ConfigPaths() []string {
	path, err := BtopConfigMutationPath()
	if err != nil {
		return nil
	}
	return []string{path}
}

func (t *BtopTool) HasConfig() bool { return true }

// btopColorTheme resolves btop's color_theme: an explicit per-tool override
// (the Manage "btop/theme" field) when the user set one, otherwise the global
// dotfiles theme — whose palette .theme file WriteBtopConfig generates so the
// unified theme actually applies by default.
func btopColorTheme(cfg BtopConfig, themeName string) string {
	switch cfg.Theme {
	case "", "auto", "Default":
		return themeName
	default:
		return cfg.Theme
	}
}

// BtopThemeArtifactName is the exact theme file stem referenced by btop.conf.
// Planning and writing share it so a per-tool override cannot point at an
// artifact outside the reviewed backup/mutation set.
func BtopThemeArtifactName(cfg BtopConfig, themeName string) string {
	return btopColorTheme(cfg, themeName)
}

func btopThemePaletteName(name string) string {
	if name == "gruvbox" {
		return "gruvbox-dark"
	}
	return name
}

func normalizeBtopConfig(cfg BtopConfig) BtopConfig {
	if cfg.UpdateMs == 0 {
		cfg.UpdateMs = 2000
	}
	if cfg.GraphType == "" {
		cfg.GraphType = "braille"
	}
	if cfg.TempScale == "" {
		cfg.TempScale = "celsius"
	}
	if cfg.ShownBoxes == "" {
		cfg.ShownBoxes = "cpu mem net proc"
	}
	return cfg
}

func ValidateBtopConfig(cfg BtopConfig, themeName string) error {
	cfg = normalizeBtopConfig(cfg)
	if err := validateConfigToken("global btop theme", themeName); err != nil {
		return err
	}
	if cfg.Theme != "" {
		switch cfg.Theme {
		case "auto", "Default", "TTY", "dracula", "gruvbox", "nord", "tokyo-night":
		default:
			return fmt.Errorf("unsupported btop theme %q", cfg.Theme)
		}
	}
	if cfg.UpdateMs < 250 || cfg.UpdateMs > 10000 {
		return fmt.Errorf("btop update interval must be between 250 and 10000 ms")
	}
	if cfg.GraphType != "braille" && cfg.GraphType != "block" && cfg.GraphType != "tty" {
		return fmt.Errorf("unsupported btop graph symbol %q", cfg.GraphType)
	}
	if cfg.TempScale != "celsius" && cfg.TempScale != "fahrenheit" {
		return fmt.Errorf("unsupported btop temperature scale %q", cfg.TempScale)
	}
	seen := make(map[string]bool)
	for _, box := range strings.Fields(cfg.ShownBoxes) {
		if seen[box] || (box != "cpu" && box != "mem" && box != "net" && box != "proc") {
			return fmt.Errorf("unsupported or duplicate btop shown box %q", box)
		}
		seen[box] = true
	}
	if len(seen) == 0 {
		return fmt.Errorf("btop shown boxes must include at least one of cpu, mem, net, proc")
	}
	return nil
}

// GenerateBtopConfig builds the btop.conf content
func GenerateBtopConfig(cfg BtopConfig, themeName string) string {
	cfg = normalizeBtopConfig(cfg)
	var sb strings.Builder

	// Header
	sb.WriteString("#? Generated by dotfiles TUI\n")
	sb.WriteString(fmt.Sprintf("#? Theme: %s\n\n", themeName))

	// Color theme
	sb.WriteString("#* Color theme\n")
	sb.WriteString(fmt.Sprintf("color_theme = \"%s\"\n\n", btopColorTheme(cfg, themeName)))

	// Update interval
	sb.WriteString("#* Update time in milliseconds\n")
	sb.WriteString(fmt.Sprintf("update_ms = %d\n\n", cfg.UpdateMs))

	// Process sorting
	sb.WriteString("#* Processes sorting\n")
	sb.WriteString("proc_sorting = \"cpu lazy\"\n")
	sb.WriteString("proc_reversed = false\n")
	sb.WriteString("proc_tree = false\n")
	sb.WriteString("proc_colors = true\n")
	sb.WriteString("proc_gradient = true\n")
	sb.WriteString("proc_per_core = false\n")
	sb.WriteString("proc_mem_bytes = true\n\n")

	// Graph settings
	sb.WriteString("#* Graph settings\n")
	sb.WriteString(fmt.Sprintf("graph_symbol = \"%s\"\n", cfg.GraphType))
	sb.WriteString("graph_symbol_cpu = \"default\"\n")
	sb.WriteString("graph_symbol_mem = \"default\"\n")
	sb.WriteString("graph_symbol_net = \"default\"\n")
	sb.WriteString("graph_symbol_proc = \"default\"\n")
	shownBoxes := cfg.ShownBoxes
	if shownBoxes == "" {
		shownBoxes = "cpu mem net proc"
	}
	sb.WriteString(fmt.Sprintf("shown_boxes = \"%s\"\n\n", shownBoxes))

	// Temperature
	sb.WriteString("#* Temperature\n")
	sb.WriteString(fmt.Sprintf("show_coretemp = %t\n", cfg.ShowTemp))
	tempScale := cfg.TempScale
	if tempScale == "" {
		tempScale = "celsius"
	}
	sb.WriteString(fmt.Sprintf("temp_scale = \"%s\"\n\n", tempScale))

	// Memory
	sb.WriteString("#* Memory\n")
	sb.WriteString("mem_graphs = true\n")
	sb.WriteString("mem_below_net = false\n")
	sb.WriteString("show_swap = true\n")
	sb.WriteString("swap_disk = true\n")
	sb.WriteString("show_disks = true\n")
	sb.WriteString("only_physical = true\n")
	sb.WriteString("use_fstab = false\n")
	sb.WriteString("show_io_stat = true\n")
	sb.WriteString("io_mode = false\n")
	sb.WriteString("io_graph_combined = false\n\n")

	// Network
	sb.WriteString("#* Network\n")
	sb.WriteString("net_download = 100\n")
	sb.WriteString("net_upload = 100\n")
	sb.WriteString("net_auto = true\n")
	sb.WriteString("net_sync = false\n")
	sb.WriteString("net_iface = \"\"\n\n")

	// General
	sb.WriteString("#* General\n")
	sb.WriteString("vim_keys = true\n")
	sb.WriteString("rounded_corners = true\n")
	sb.WriteString("clock_format = \"%X\"\n")
	sb.WriteString("background_update = true\n")
	sb.WriteString("update_check = false\n")
	sb.WriteString("log_level = \"WARNING\"\n")

	return sb.String()
}

// GenerateBtopTheme builds the btop theme file content.
func GenerateBtopTheme(themeName string) string {
	p := theme.GetOrDefault(themeName)
	directives := []struct {
		key   string
		value string
	}{
		{"main_bg", p.Bg},
		{"main_fg", p.Text},
		{"title", p.Accent},
		{"hi_fg", p.AccentAlt},
		{"selected_bg", p.Surface},
		{"selected_fg", p.TextBright},
		{"inactive_fg", p.TextMuted},
		{"graph_text", p.TextMuted},
		{"meter_bg", p.Surface},
		{"proc_misc", p.AccentAlt},
		{"div_line", p.Border},
		{"cpu_box", p.Border},
		{"mem_box", p.Border},
		{"net_box", p.Border},
		{"proc_box", p.Border},
		{"cpu_start", p.Accent},
		{"cpu_mid", ""},
		{"cpu_end", ""},
		{"temp_start", p.Warning},
		{"temp_mid", ""},
		{"temp_end", ""},
		{"used_start", p.Warning},
		{"used_mid", ""},
		{"used_end", ""},
		{"free_start", p.Success},
		{"free_mid", ""},
		{"free_end", ""},
		{"available_start", p.Success},
		{"available_mid", ""},
		{"available_end", ""},
		{"cached_start", p.Info},
		{"cached_mid", ""},
		{"cached_end", ""},
		{"download_start", p.Info},
		{"download_mid", ""},
		{"download_end", ""},
		{"upload_start", p.Accent},
		{"upload_mid", ""},
		{"upload_end", ""},
		{"process_start", p.Accent},
		{"process_mid", ""},
		{"process_end", ""},
	}

	var sb strings.Builder
	sb.WriteString("# Generated by dotfiles TUI\n")
	sb.WriteString(fmt.Sprintf("# Theme: %s\n\n", themeName))
	for _, directive := range directives {
		sb.WriteString(fmt.Sprintf("theme[%s]=\"%s\"\n", directive.key, directive.value))
	}
	return sb.String()
}

// WriteBtopConfig writes the btop config to disk
func WriteBtopConfig(cfg BtopConfig, theme string) error {
	_, err := WriteBtopConfigTracked(cfg, theme)
	return err
}

func WriteBtopConfigTracked(cfg BtopConfig, theme string) ([]MutationEvidence, error) {
	if err := ValidateBtopConfig(cfg, theme); err != nil {
		return nil, err
	}
	cfg = normalizeBtopConfig(cfg)
	configPath, err := BtopConfigMutationPath()
	if err != nil {
		return nil, err
	}
	themePath, err := BtopThemeMutationPath(cfg, theme)
	if err != nil {
		return nil, err
	}
	if err := preflightWholeFileConfig(themePath, false); err != nil {
		if errors.Is(err, ErrUnmanagedConfig) {
			return nil, fmt.Errorf("%w; legacy btop theme files carried no verifiable ownership marker and require explicit adoption", err)
		}
		return nil, fmt.Errorf("preflight btop config set: %w", err)
	}
	if imported, importErr := ImportBtopConfig(); importErr != nil {
		return nil, fmt.Errorf("preflight btop config set: %w", importErr)
	} else if len(imported.Warnings) != 0 {
		return nil, fmt.Errorf("preflight btop config set: %s", strings.Join(imported.Warnings, "; "))
	}
	themeContent := GenerateBtopTheme(btopThemePaletteName(BtopThemeArtifactName(cfg, theme)))
	var committed []MutationEvidence
	evidence, err := writeToolConfigTracked(themePath, []byte(themeContent))
	if err != nil {
		if errors.Is(err, ErrUnmanagedConfig) {
			return nil, partialMutationError(fmt.Errorf("%w; legacy btop theme files carried no verifiable ownership marker and require explicit adoption", err), committed)
		}
		return nil, partialMutationError(err, committed)
	}
	committed = append(committed, evidence)

	evidence, err = writeBtopManagedConfigTracked(configPath, cfg, theme)
	if err != nil {
		return nil, partialMutationError(err, committed)
	}
	return append(committed, evidence), nil
}

// WriteBtopConfigAtRevisionsTracked applies the complete plan-accepted btop set.
func WriteBtopConfigAtRevisionsTracked(cfg BtopConfig, theme string, themeAccepted, configAccepted safefile.Revision) ([]MutationEvidence, error) {
	if err := ValidateBtopConfig(cfg, theme); err != nil {
		return nil, err
	}
	cfg = normalizeBtopConfig(cfg)
	configPath, err := BtopConfigMutationPath()
	if err != nil {
		return nil, err
	}
	themePath, err := BtopThemeMutationPath(cfg, theme)
	if err != nil {
		return nil, err
	}
	themeParents, err := compatibilityToolConfigParents(themePath)
	if err != nil {
		return nil, err
	}
	configParents, err := compatibilityToolConfigParents(configPath)
	if err != nil {
		return nil, err
	}
	return WriteBtopConfigAtAuthoritiesTracked(cfg, theme, themeAccepted, themeParents, configAccepted, configParents, operation.DefaultLocker)
}

func WriteBtopConfigAtAuthoritiesTracked(cfg BtopConfig, theme string, themeAccepted safefile.Revision, themeParents *safefile.ParentChain, configAccepted safefile.Revision, configParents *safefile.ParentChain, locker operation.Locker) (results []MutationEvidence, returnErr error) {
	if err := ValidateBtopConfig(cfg, theme); err != nil {
		return nil, err
	}
	cfg = normalizeBtopConfig(cfg)
	configPath, err := BtopConfigMutationPath()
	if err != nil {
		return nil, err
	}
	themePath, err := BtopThemeMutationPath(cfg, theme)
	if err != nil {
		return nil, err
	}
	if !themeAccepted.Tracked() || !configAccepted.Tracked() || !themeParents.Tracked() || !configParents.Tracked() || locker == nil {
		return nil, fmt.Errorf("%w: accepted btop config-set authority is incomplete", safefile.ErrParentChanged)
	}
	var committed []MutationEvidence
	lockPaths := []string{configPath, themePath}
	sort.Strings(lockPaths)
	releases := make([]func() error, 0, len(lockPaths))
	for _, path := range lockPaths {
		release, lockErr := locker("tool-config", path)
		if lockErr != nil {
			for index := len(releases) - 1; index >= 0; index-- {
				lockErr = errors.Join(lockErr, releases[index]())
			}
			return nil, lockErr
		}
		releases = append(releases, release)
	}
	defer func() {
		var releaseErr error
		for index := len(releases) - 1; index >= 0; index-- {
			if err := releases[index](); err != nil {
				releaseErr = errors.Join(releaseErr, fmt.Errorf("release btop config-set lock: %w", err))
			}
		}
		if releaseErr != nil {
			joined := errors.Join(returnErr, releaseErr)
			if len(committed) != 0 {
				results = nil
				returnErr = partialMutationError(joined, committed)
			} else {
				returnErr = joined
			}
		}
	}()

	themeRoot, themeRel, _, err := generatedConfigDestination(themePath)
	if err != nil {
		return nil, err
	}
	configRoot, configRel, _, err := generatedConfigDestination(configPath)
	if err != nil {
		return nil, err
	}
	themeExisting, themeCurrent, err := safefile.ReadWithinAuthorized(themeRoot, themeRel, themeParents)
	if err != nil {
		return nil, err
	}
	configExisting, configCurrent, err := safefile.ReadWithinAuthorized(configRoot, configRel, configParents)
	if err != nil {
		return nil, err
	}
	if themeCurrent != themeAccepted || configCurrent != configAccepted {
		return nil, fmt.Errorf("%w: btop config set changed after plan acceptance", safefile.ErrRevisionChanged)
	}
	if themeCurrent.Exists() && !hasGeneratedConfigHeader(themeExisting) {
		return nil, fmt.Errorf("%w: %s; legacy btop theme files carried no verifiable ownership marker and require explicit adoption", ErrUnmanagedConfig, themePath)
	}
	parsed, err := parseBtopConfigImport(configPath, configExisting, configCurrent.Exists())
	if err != nil {
		return nil, fmt.Errorf("preflight accepted btop config set: %w", err)
	}
	if len(parsed.Warnings) != 0 {
		return nil, fmt.Errorf("preflight accepted btop config set: %s", strings.Join(parsed.Warnings, "; "))
	}
	merged, _, err := mergeBtopManagedSection(configExisting, cfg, theme)
	if err != nil {
		return nil, err
	}
	themeContent := []byte(GenerateBtopTheme(btopThemePaletteName(BtopThemeArtifactName(cfg, theme))))

	themeEvidence := MutationEvidence{Path: themePath, Revision: themeCurrent, Parents: themeParents}
	if !themeCurrent.Exists() || !bytes.Equal(themeExisting, themeContent) {
		committedRevision, replaceErr := replaceToolConfigAtRevisionNoCreateAuthorizedTracked(themeRoot, themeRel, themeAccepted, themeParents, themeContent)
		if replaceErr != nil {
			return nil, partialMutationError(replaceErr, committed)
		}
		themeEvidence.Revision = committedRevision
		committed = append(committed, themeEvidence)
	}
	results = append(results, themeEvidence)
	configEvidence := MutationEvidence{Path: configPath, Revision: configCurrent, Parents: configParents}
	if !configCurrent.Exists() || !bytes.Equal(configExisting, merged) {
		committedRevision, replaceErr := replaceToolConfigAtRevisionNoCreateAuthorizedTracked(configRoot, configRel, configAccepted, configParents, merged)
		if replaceErr != nil {
			return nil, partialMutationError(replaceErr, committed)
		}
		configEvidence.Revision = committedRevision
		committed = append(committed, configEvidence)
	}
	return append(results, configEvidence), nil
}

func writeBtopManagedConfigTracked(path string, cfg BtopConfig, theme string) (MutationEvidence, error) {
	var evidence MutationEvidence
	err := withToolConfigLock(path, func(root, rel string) error {
		existing, revision, err := readToolConfig(root, rel)
		if err != nil {
			return err
		}
		parsed, err := parseBtopConfigImport(path, existing, revision.Exists())
		if err != nil {
			return err
		}
		if len(parsed.Warnings) != 0 {
			return fmt.Errorf("refusing ambiguous btop config: %s", strings.Join(parsed.Warnings, "; "))
		}
		merged, _, err := mergeBtopManagedSection(existing, cfg, theme)
		if err != nil {
			return err
		}
		if revision.Exists() && bytes.Equal(existing, merged) {
			evidence = MutationEvidence{Path: path, Revision: revision}
			return nil
		}
		committed, err := replaceToolConfigAtRevisionTracked(root, rel, revision, merged)
		if err == nil {
			evidence = MutationEvidence{Path: path, Revision: committed}
		}
		return err
	})
	return evidence, err
}
