package tools

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/tekierz/dotfiles/internal/pkg"
	"github.com/tekierz/dotfiles/internal/theme"
)

// BtopConfig holds btop configuration settings
type BtopConfig struct {
	Theme     string // "auto", "Default", "TTY", custom theme name
	UpdateMs  int    // Update interval in milliseconds
	ShowTemp  bool   // Show temperature sensors
	GraphType string // "braille", "block", "tty"

	TempScale  string // "celsius", "fahrenheit"
	ShownBoxes string // e.g. "cpu mem net proc"
}

// BtopTool represents btop system monitor
type BtopTool struct {
	BaseTool
}

// NewBtopTool creates a new btop tool
func NewBtopTool() *BtopTool {
	home, _ := os.UserHomeDir()
	return &BtopTool{
		BaseTool: BaseTool{
			id:          "btop",
			name:        "btop",
			description: "Resource monitor with TUI",
			icon:        "󰄨",
			category:    CategoryUtility,
			packages: map[pkg.Platform][]string{
				pkg.PlatformMacOS:  {"btop"},
				pkg.PlatformArch:   {"btop"},
				pkg.PlatformDebian: {"btop"},
			},
			configPaths: []string{
				filepath.Join(home, ".config", "btop", "btop.conf"),
			},
			heavyTool: true, // Skip on low-memory systems (Pi Zero 2)
			// UI metadata
			uiGroup:        UIGroupCLITools,
			configScreen:   30, // ScreenConfigBtop - has dedicated config screen
			defaultEnabled: true,
		},
	}
}

// btopColorTheme resolves btop's color_theme: an explicit per-tool override
// (the Manage "btop/theme" field) when the user set one, otherwise the global
// dotfiles theme — whose palette .theme file WriteBtopConfig generates so the
// unified theme actually applies by default.
func btopColorTheme(cfg BtopConfig, themeName string) string {
	switch cfg.Theme {
	case "", "auto", "Default":
		return themeName
	default:
		return cfg.Theme
	}
}

// GenerateBtopConfig builds the btop.conf content
func GenerateBtopConfig(cfg BtopConfig, themeName string) string {
	var sb strings.Builder

	// Header
	sb.WriteString("#? Generated by dotfiles TUI\n")
	sb.WriteString(fmt.Sprintf("#? Theme: %s\n\n", themeName))

	// Color theme
	sb.WriteString("#* Color theme\n")
	sb.WriteString(fmt.Sprintf("color_theme = \"%s\"\n\n", btopColorTheme(cfg, themeName)))

	// Update interval
	sb.WriteString("#* Update time in milliseconds\n")
	sb.WriteString(fmt.Sprintf("update_ms = %d\n\n", cfg.UpdateMs))

	// Process sorting
	sb.WriteString("#* Processes sorting\n")
	sb.WriteString("proc_sorting = \"cpu lazy\"\n")
	sb.WriteString("proc_reversed = false\n")
	sb.WriteString("proc_tree = false\n")
	sb.WriteString("proc_colors = true\n")
	sb.WriteString("proc_gradient = true\n")
	sb.WriteString("proc_per_core = false\n")
	sb.WriteString("proc_mem_bytes = true\n\n")

	// Graph settings
	sb.WriteString("#* Graph settings\n")
	sb.WriteString(fmt.Sprintf("graph_symbol = \"%s\"\n", cfg.GraphType))
	sb.WriteString("graph_symbol_cpu = \"default\"\n")
	sb.WriteString("graph_symbol_mem = \"default\"\n")
	sb.WriteString("graph_symbol_net = \"default\"\n")
	sb.WriteString("graph_symbol_proc = \"default\"\n")
	shownBoxes := cfg.ShownBoxes
	if shownBoxes == "" {
		shownBoxes = "cpu mem net proc"
	}
	sb.WriteString(fmt.Sprintf("shown_boxes = \"%s\"\n\n", shownBoxes))

	// Temperature
	sb.WriteString("#* Temperature\n")
	sb.WriteString(fmt.Sprintf("show_coretemp = %t\n", cfg.ShowTemp))
	tempScale := cfg.TempScale
	if tempScale == "" {
		tempScale = "celsius"
	}
	sb.WriteString(fmt.Sprintf("temp_scale = \"%s\"\n\n", tempScale))

	// Memory
	sb.WriteString("#* Memory\n")
	sb.WriteString("mem_graphs = true\n")
	sb.WriteString("mem_below_net = false\n")
	sb.WriteString("show_swap = true\n")
	sb.WriteString("swap_disk = true\n")
	sb.WriteString("show_disks = true\n")
	sb.WriteString("only_physical = true\n")
	sb.WriteString("use_fstab = false\n")
	sb.WriteString("show_io_stat = true\n")
	sb.WriteString("io_mode = false\n")
	sb.WriteString("io_graph_combined = false\n\n")

	// Network
	sb.WriteString("#* Network\n")
	sb.WriteString("net_download = 100\n")
	sb.WriteString("net_upload = 100\n")
	sb.WriteString("net_auto = true\n")
	sb.WriteString("net_sync = false\n")
	sb.WriteString("net_iface = \"\"\n\n")

	// General
	sb.WriteString("#* General\n")
	sb.WriteString("vim_keys = true\n")
	sb.WriteString("rounded_corners = true\n")
	sb.WriteString("clock_format = \"%X\"\n")
	sb.WriteString("background_update = true\n")
	sb.WriteString("update_check = false\n")
	sb.WriteString("log_level = \"WARNING\"\n")

	return sb.String()
}

// GenerateBtopTheme builds the btop theme file content.
func GenerateBtopTheme(themeName string) string {
	p := theme.GetOrDefault(themeName)
	directives := []struct {
		key   string
		value string
	}{
		{"main_bg", p.Bg},
		{"main_fg", p.Text},
		{"title", p.Accent},
		{"hi_fg", p.AccentAlt},
		{"selected_bg", p.Surface},
		{"selected_fg", p.TextBright},
		{"inactive_fg", p.TextMuted},
		{"graph_text", p.TextMuted},
		{"meter_bg", p.Surface},
		{"proc_misc", p.AccentAlt},
		{"div_line", p.Border},
		{"cpu_box", p.Border},
		{"mem_box", p.Border},
		{"net_box", p.Border},
		{"proc_box", p.Border},
		{"cpu_start", p.Accent},
		{"cpu_mid", ""},
		{"cpu_end", ""},
		{"temp_start", p.Warning},
		{"temp_mid", ""},
		{"temp_end", ""},
		{"used_start", p.Warning},
		{"used_mid", ""},
		{"used_end", ""},
		{"free_start", p.Success},
		{"free_mid", ""},
		{"free_end", ""},
		{"available_start", p.Success},
		{"available_mid", ""},
		{"available_end", ""},
		{"cached_start", p.Info},
		{"cached_mid", ""},
		{"cached_end", ""},
		{"download_start", p.Info},
		{"download_mid", ""},
		{"download_end", ""},
		{"upload_start", p.Accent},
		{"upload_mid", ""},
		{"upload_end", ""},
		{"process_start", p.Accent},
		{"process_mid", ""},
		{"process_end", ""},
	}

	var sb strings.Builder
	for _, directive := range directives {
		sb.WriteString(fmt.Sprintf("theme[%s]=\"%s\"\n", directive.key, directive.value))
	}
	return sb.String()
}

// WriteBtopConfig writes the btop config to disk
func WriteBtopConfig(cfg BtopConfig, theme string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}

	themePath := filepath.Join(home, ".config", "btop", "themes", theme+".theme")
	themeContent := GenerateBtopTheme(theme)
	if err := writeToolConfig(themePath, []byte(themeContent)); err != nil {
		return err
	}

	configPath := filepath.Join(home, ".config", "btop", "btop.conf")
	content := GenerateBtopConfig(cfg, theme)
	return writeToolConfig(configPath, []byte(content))
}
