package tools

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/tekierz/dotfiles/internal/pkg"
	"github.com/tekierz/dotfiles/internal/theme"
)

// FzfConfig holds FZF configuration settings
type FzfConfig struct {
	Preview bool
	Height  int    // Percentage (e.g., 40 for 40%)
	Layout  string // "reverse", "default", "reverse-list"

	DefaultOpts   string // additional fzf flags stored as inert environment data
	BorderStyle   string // "rounded", "sharp", "bold", "none"
	PreviewWindow string // "right:50%", "up:50%", "down:50%"
}

// FzfTool represents the fzf fuzzy finder
type FzfTool struct {
	BaseTool
}

// NewFzfTool creates a new fzf tool
func NewFzfTool() *FzfTool {
	home, _ := os.UserHomeDir()
	return &FzfTool{
		BaseTool: BaseTool{
			id:          "fzf",
			name:        "fzf",
			description: "Command-line fuzzy finder",
			icon:        "󰍉",
			category:    CategoryUtility,
			packages: map[pkg.Platform][]string{
				pkg.PlatformMacOS:  {"fzf"},
				pkg.PlatformArch:   {"fzf"},
				pkg.PlatformDebian: {"fzf"},
			},
			configPaths: []string{
				filepath.Join(home, ".config", "fzf", "fzf.zsh"),
			},
			// UI metadata
			uiGroup:        UIGroupNone,
			configScreen:   15, // ScreenConfigFzf
			defaultEnabled: true,
		},
	}
}

// GenerateFzfConfig builds the fzf environment configuration
func GenerateFzfConfig(cfg FzfConfig, theme string) string {
	var sb strings.Builder

	// Header
	sb.WriteString("# Generated by dotfiles TUI\n")
	sb.WriteString(fmt.Sprintf("# Theme: %s\n\n", sanitizeFzfComment(theme)))

	// Build FZF_DEFAULT_OPTS
	var opts []string

	// Layout
	if cfg.Layout != "" && validFzfLayout(cfg.Layout) && cfg.Layout != "default" {
		opts = append(opts, fmt.Sprintf("--layout=%s", cfg.Layout))
	}

	// Height
	if cfg.Height > 0 && cfg.Height < 100 {
		opts = append(opts, fmt.Sprintf("--height=%d%%", cfg.Height))
	}

	// Preview
	if cfg.Preview {
		opts = append(opts, "--preview 'bat --style=numbers --color=always --line-range :500 {} 2>/dev/null || cat {}'")
		previewWindow := cfg.PreviewWindow
		if !validFzfPreviewWindow(previewWindow) {
			previewWindow = "right:50%"
		}
		opts = append(opts, fmt.Sprintf("--preview-window=%s:wrap", previewWindow))
	}

	// Common styling
	border := cfg.BorderStyle
	if !validFzfBorderStyle(border) {
		border = "rounded"
	}
	opts = append(opts, fmt.Sprintf("--border=%s", border))
	opts = append(opts, "--margin=1")
	opts = append(opts, "--padding=1")

	// Extra user-supplied flags remain literal FZF_DEFAULT_OPTS data. They are
	// never interpolated as shell syntax when this generated file is sourced.
	if strings.TrimSpace(cfg.DefaultOpts) != "" {
		opts = append(opts, sanitizeFzfOptionData(strings.TrimSpace(cfg.DefaultOpts)))
	}

	// Quote the complete value as one zsh single-quoted word. Embedded quotes,
	// command substitutions, backticks, newlines, and backslashes consequently
	// survive as inert environment data rather than being evaluated on source.
	if len(opts) > 0 {
		sb.WriteString("export FZF_DEFAULT_OPTS=")
		sb.WriteString(quoteZshData(strings.Join(opts, " ")))
		sb.WriteString("\n")
	}
	sb.WriteString("\n")
	sb.WriteString(buildFzfColorGuard(theme))
	sb.WriteString("\n")

	// FZF_DEFAULT_COMMAND (use fd if available)
	sb.WriteString("# Use fd if available for faster searching\n")
	sb.WriteString("if command -v fd &>/dev/null; then\n")
	sb.WriteString("  export FZF_DEFAULT_COMMAND='fd --type f --strip-cwd-prefix --hidden --follow --exclude .git'\n")
	sb.WriteString("  export FZF_CTRL_T_COMMAND=\"$FZF_DEFAULT_COMMAND\"\n")
	sb.WriteString("  export FZF_ALT_C_COMMAND='fd --type d --strip-cwd-prefix --hidden --follow --exclude .git'\n")
	sb.WriteString("fi\n\n")

	// Key bindings
	sb.WriteString("# Enable fzf key bindings and completion\n")
	sb.WriteString("if [[ -f /usr/share/fzf/key-bindings.zsh ]]; then\n")
	sb.WriteString("  source /usr/share/fzf/key-bindings.zsh\n")
	sb.WriteString("  [[ -f /usr/share/fzf/completion.zsh ]] && source /usr/share/fzf/completion.zsh\n")
	sb.WriteString("elif [[ -f ~/.fzf.zsh ]]; then\n")
	sb.WriteString("  source ~/.fzf.zsh\n")
	sb.WriteString("elif command -v brew &>/dev/null; then\n")
	sb.WriteString("  [[ -f $(brew --prefix)/opt/fzf/shell/key-bindings.zsh ]] && source $(brew --prefix)/opt/fzf/shell/key-bindings.zsh\n")
	sb.WriteString("  [[ -f $(brew --prefix)/opt/fzf/shell/completion.zsh ]] && source $(brew --prefix)/opt/fzf/shell/completion.zsh\n")
	sb.WriteString("fi\n")

	return sb.String()
}

func validFzfLayout(value string) bool {
	switch value {
	case "default", "reverse", "reverse-list":
		return true
	default:
		return false
	}
}

func validFzfBorderStyle(value string) bool {
	switch value {
	case "rounded", "sharp", "bold", "none":
		return true
	default:
		return false
	}
}

func validFzfPreviewWindow(value string) bool {
	switch value {
	case "right:50%", "up:50%", "down:50%":
		return true
	default:
		return false
	}
}

func quoteZshData(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}

func sanitizeFzfOptionData(value string) string {
	// Environment variables and shell source files cannot contain NUL bytes.
	// Preserve their visible intent without emitting an invalid script.
	return strings.ReplaceAll(value, "\x00", `\0`)
}

func sanitizeFzfComment(value string) string {
	replacer := strings.NewReplacer("\r", " ", "\n", " ", "\x00", `\0`)
	return replacer.Replace(value)
}

func buildFzfColorGuard(themeName string) string {
	baseColor := buildFzfBaseColorOption(themeName)
	hexColor := buildFzfColorOption(themeName)

	var sb strings.Builder
	sb.WriteString("# Apply hex fzf colors only when the installed fzf supports them.\n")
	sb.WriteString("if command -v fzf &>/dev/null; then\n")
	sb.WriteString("  __dotfiles_fzf_version=\"$(fzf --version 2>/dev/null)\"\n")
	sb.WriteString("  __dotfiles_fzf_version=\"${__dotfiles_fzf_version%% *}\"\n")
	sb.WriteString("  __dotfiles_fzf_major=\"${__dotfiles_fzf_version%%.*}\"\n")
	sb.WriteString("  __dotfiles_fzf_minor=\"${__dotfiles_fzf_version#*.}\"\n")
	sb.WriteString("  __dotfiles_fzf_minor=\"${__dotfiles_fzf_minor%%.*}\"\n")
	sb.WriteString(fmt.Sprintf("  __dotfiles_fzf_color_opt=\"%s\"\n", baseColor))
	sb.WriteString("  if [[ \"$__dotfiles_fzf_major\" == <-> && \"$__dotfiles_fzf_minor\" == <-> ]] && (( 10#$__dotfiles_fzf_major > 0 || 10#$__dotfiles_fzf_minor >= 35 )); then\n")
	sb.WriteString(fmt.Sprintf("    __dotfiles_fzf_color_opt=\"%s\"\n", hexColor))
	sb.WriteString("  fi\n")
	sb.WriteString("  export FZF_DEFAULT_OPTS=\"$FZF_DEFAULT_OPTS $__dotfiles_fzf_color_opt\"\n")
	sb.WriteString("  unset __dotfiles_fzf_version __dotfiles_fzf_major __dotfiles_fzf_minor __dotfiles_fzf_color_opt\n")
	sb.WriteString("else\n")
	sb.WriteString(fmt.Sprintf("  export FZF_DEFAULT_OPTS=\"$FZF_DEFAULT_OPTS %s\"\n", baseColor))
	sb.WriteString("fi\n")
	return sb.String()
}

func buildFzfBaseColorOption(themeName string) string {
	p := theme.GetOrDefault(themeName)
	base := "light"
	if isDarkHexColor(p.Bg) {
		base = "dark"
	}

	return fmt.Sprintf("--color=%s", base)
}

func buildFzfColorOption(themeName string) string {
	p := theme.GetOrDefault(themeName)

	return fmt.Sprintf("%s,fg:%s,bg:%s,hl:%s,fg+:%s,bg+:%s,hl+:%s,info:%s,prompt:%s,pointer:%s,marker:%s,spinner:%s,header:%s,border:%s",
		buildFzfBaseColorOption(themeName),
		p.Text,
		p.Bg,
		p.Accent,
		p.TextBright,
		p.Surface,
		p.AccentAlt,
		p.Info,
		p.Accent,
		p.AccentAlt,
		p.Success,
		p.AccentAlt,
		p.Info,
		p.Border,
	)
}

func isDarkHexColor(hex string) bool {
	hex = strings.TrimPrefix(strings.TrimSpace(hex), "#")
	if len(hex) != 6 {
		return true
	}

	r, errR := strconv.ParseUint(hex[0:2], 16, 8)
	g, errG := strconv.ParseUint(hex[2:4], 16, 8)
	b, errB := strconv.ParseUint(hex[4:6], 16, 8)
	if errR != nil || errG != nil || errB != nil {
		return true
	}

	luminance := 0.299*float64(r) + 0.587*float64(g) + 0.114*float64(b)
	return luminance < 128
}

// WriteFzfConfig writes the fzf configuration to a sourceable file
func WriteFzfConfig(cfg FzfConfig, theme string) error {
	_, err := WriteFzfConfigTracked(cfg, theme)
	return err
}

// WriteFzfConfigTracked writes the fzf configuration and returns the exact
// committed revision for rollback evidence.
func WriteFzfConfigTracked(cfg FzfConfig, theme string) (MutationEvidence, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return MutationEvidence{}, fmt.Errorf("failed to get home directory: %w", err)
	}

	configPath := filepath.Join(home, ".config", "fzf", "fzf.zsh")
	content := GenerateFzfConfig(cfg, theme)
	return writeToolConfigTracked(configPath, []byte(content))
}
