package tools

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/tekierz/dotfiles/internal/pkg"
)

// GhosttyConfig holds Ghostty configuration settings
type GhosttyConfig struct {
	FontSize        int
	FontFamily      string
	Opacity         int    // 0-100 (100 = fully opaque)
	BlurRadius      int    // 0-100
	TabBindings     string // "super", "ctrl", "ctrl-shift"
	ScrollbackLines int
	CursorStyle     string // "block", "bar", "underline"
}

// GhosttyTool represents the Ghostty terminal emulator
type GhosttyTool struct {
	BaseTool
}

// NewGhosttyTool creates a new Ghostty tool
func NewGhosttyTool() *GhosttyTool {
	home, _ := os.UserHomeDir()
	return &GhosttyTool{
		BaseTool: BaseTool{
			id:          "ghostty",
			name:        "Ghostty",
			description: "GPU-accelerated terminal emulator",
			icon:        "󰆍",
			category:    CategoryTerminal,
			packages: map[pkg.Platform][]string{
				pkg.PlatformMacOS: {"ghostty"},
				pkg.PlatformArch:  {"ghostty"},
				// Debian: not yet in repos, manual install
			},
			configPaths: []string{
				filepath.Join(home, ".config", "ghostty", "config"),
			},
			// UI metadata
			uiGroup:        UIGroupNone,
			configScreen:   9, // ScreenConfigGhostty
			defaultEnabled: true,
		},
	}
}

// GenerateGhosttyConfig builds the Ghostty config file content
func GenerateGhosttyConfig(cfg GhosttyConfig, theme string) string {
	var sb strings.Builder

	// Header
	sb.WriteString("# Generated by dotfiles TUI\n")
	sb.WriteString(fmt.Sprintf("# Theme: %s\n\n", theme))

	// Font settings
	sb.WriteString("# Font settings\n")
	sb.WriteString(fmt.Sprintf("font-family = %s\n", cfg.FontFamily))
	sb.WriteString(fmt.Sprintf("font-size = %d\n\n", cfg.FontSize))

	// Window appearance
	sb.WriteString("# Window appearance\n")
	if cfg.Opacity < 100 {
		// Convert 0-100 to 0.0-1.0
		opacity := float64(cfg.Opacity) / 100.0
		sb.WriteString(fmt.Sprintf("background-opacity = %.2f\n", opacity))
	}
	if cfg.BlurRadius > 0 {
		sb.WriteString(fmt.Sprintf("background-blur-radius = %d\n", cfg.BlurRadius))
	}
	sb.WriteString("\n")

	// Cursor
	sb.WriteString("# Cursor\n")
	sb.WriteString(fmt.Sprintf("cursor-style = %s\n", cfg.CursorStyle))
	sb.WriteString("cursor-style-blink = true\n\n")

	// Scrollback
	sb.WriteString("# Scrollback\n")
	sb.WriteString(fmt.Sprintf("scrollback-limit = %d\n\n", cfg.ScrollbackLines))

	// Keybindings based on tab binding preference
	sb.WriteString("# Tab keybindings\n")
	switch cfg.TabBindings {
	case "super":
		sb.WriteString("keybind = super+t=new_tab\n")
		sb.WriteString("keybind = super+w=close_surface\n")
		sb.WriteString("keybind = super+shift+]=next_tab\n")
		sb.WriteString("keybind = super+shift+[=previous_tab\n")
	case "ctrl":
		sb.WriteString("keybind = ctrl+t=new_tab\n")
		sb.WriteString("keybind = ctrl+w=close_surface\n")
		sb.WriteString("keybind = ctrl+tab=next_tab\n")
		sb.WriteString("keybind = ctrl+shift+tab=previous_tab\n")
	case "ctrl-shift":
		sb.WriteString("keybind = ctrl+shift+t=new_tab\n")
		sb.WriteString("keybind = ctrl+shift+w=close_surface\n")
		sb.WriteString("keybind = ctrl+tab=next_tab\n")
		sb.WriteString("keybind = ctrl+shift+tab=previous_tab\n")
	}
	sb.WriteString("\n")

	// Shell integration
	sb.WriteString("# Shell integration\n")
	sb.WriteString("shell-integration = zsh\n")
	sb.WriteString("shell-integration-features = cursor,sudo,title\n\n")

	// Performance settings
	sb.WriteString("# Performance\n")
	sb.WriteString("gtk-single-instance = true\n")

	return sb.String()
}

// WriteGhosttyConfig writes the Ghostty config file to disk
func WriteGhosttyConfig(cfg GhosttyConfig, theme string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}

	configDir := filepath.Join(home, ".config", "ghostty")
	if err := os.MkdirAll(configDir, 0700); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	configPath := filepath.Join(configDir, "config")
	content := GenerateGhosttyConfig(cfg, theme)

	if err := os.WriteFile(configPath, []byte(content), 0600); err != nil {
		return fmt.Errorf("failed to write ghostty config: %w", err)
	}

	return nil
}

// GenerateConfig implements Tool interface (uses defaults)
func (t *GhosttyTool) GenerateConfig(theme string) string {
	cfg := GhosttyConfig{
		FontSize:        14,
		FontFamily:      "JetBrains Mono",
		Opacity:         100,
		BlurRadius:      0,
		TabBindings:     "super",
		ScrollbackLines: 10000,
		CursorStyle:     "block",
	}
	return GenerateGhosttyConfig(cfg, theme)
}

// ApplyConfig implements Tool interface (uses defaults)
func (t *GhosttyTool) ApplyConfig(theme string) error {
	cfg := GhosttyConfig{
		FontSize:        14,
		FontFamily:      "JetBrains Mono",
		Opacity:         100,
		BlurRadius:      0,
		TabBindings:     "super",
		ScrollbackLines: 10000,
		CursorStyle:     "block",
	}
	return WriteGhosttyConfig(cfg, theme)
}
