package tools

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/tekierz/dotfiles/internal/pkg"
	"github.com/tekierz/dotfiles/internal/safefile"
	"github.com/tekierz/dotfiles/internal/theme"
)

// GhosttyConfig holds Ghostty configuration settings
type GhosttyConfig struct {
	FontSize        int
	FontFamily      string
	Opacity         int    // 0-100 (100 = fully opaque)
	BlurRadius      int    // 0-100
	TabBindings     string // "super", "ctrl", "ctrl-shift"
	ScrollbackLines int    // Ghostty's scrollback-limit is measured in bytes.
	CursorStyle     string // "block", "bar", "underline"

	WindowDecorations bool // Show native window decorations
	ConfirmClose      bool // Prompt before closing a surface
}

// IsInstalled recognizes direct/manual Ghostty installs as well as package
// receipts. This matters on Debian/Pi, where no supported package is declared
// but an externally installed binary may still be safely configured.
func (t *GhosttyTool) IsInstalled() bool {
	if _, err := exec.LookPath("ghostty"); err == nil {
		return true
	}
	if ghosttyAppBundleInstalled() {
		return true
	}
	return t.BaseTool.IsInstalled()
}

func ghosttyAppBundleInstalled() bool {
	return hasMacOSApp("Ghostty")
}

// GhosttyTool represents the Ghostty terminal emulator
type GhosttyTool struct {
	BaseTool
}

const (
	ghosttyManagedStart = "# >>> dotfiles ghostty (managed)"
	ghosttyManagedEnd   = "# <<< dotfiles ghostty (managed)"
)

// NewGhosttyTool creates a new Ghostty tool
func NewGhosttyTool() *GhosttyTool {
	home, _ := os.UserHomeDir()
	return &GhosttyTool{
		BaseTool: BaseTool{
			id:          "ghostty",
			name:        "Ghostty",
			description: "GPU-accelerated terminal emulator",
			icon:        "󰆍",
			category:    CategoryTerminal,
			packages: map[pkg.Platform][]string{
				pkg.PlatformMacOS: {"ghostty"},
				pkg.PlatformArch:  {"ghostty"},
				// Debian: not yet in repos, manual install
			},
			configPaths: ghosttyConfigCandidates(home),
			// UI metadata
			uiGroup:        UIGroupNone,
			configScreen:   9, // ScreenConfigGhostty
			defaultEnabled: true,
		},
	}
}

// ghosttyConfigCandidates follows Ghostty's platform source precedence. On
// macOS the Application Support file is loaded after the XDG source and may
// override it; both must therefore be observed. Other platforms use the XDG
// source only.
func ghosttyConfigCandidates(home string) []string {
	xdgRoot := filepath.Join(home, ".config")
	if xdg := os.Getenv("XDG_CONFIG_HOME"); filepath.IsAbs(xdg) {
		xdgRoot = filepath.Clean(xdg)
	}
	paths := []string{
		filepath.Join(xdgRoot, "ghostty", "config.ghostty"),
		filepath.Join(xdgRoot, "ghostty", "config"),
	}
	if runtime.GOOS == "darwin" {
		appSupport := filepath.Join(home, "Library", "Application Support", "com.mitchellh.ghostty")
		paths = append(paths,
			filepath.Join(appSupport, "config.ghostty"),
			filepath.Join(appSupport, "config"),
		)
	}
	return paths
}

func activeGhosttyConfigPath(home string) (string, error) {
	paths := ghosttyConfigCandidates(home)
	active := paths[0]
	for _, path := range paths {
		_, exists, err := readNativeConfig(path)
		if err != nil {
			return "", err
		}
		if exists {
			active = path
		}
	}
	return active, nil
}

// GhosttyConfigMutationPath returns the exact source WriteGhosttyConfig would
// update without mutating it. Plans and previews use this observer so their
// declared target cannot diverge from execution on macOS's two-source chain.
func GhosttyConfigMutationPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("failed to get home directory: %w", err)
	}
	return activeGhosttyConfigPath(home)
}

// GenerateGhosttyConfig builds the Ghostty config file content
func GenerateGhosttyConfig(cfg GhosttyConfig, themeName string) string {
	var sb strings.Builder
	p := theme.GetOrDefault(themeName)
	cfg = normalizedGhosttyConfig(cfg)

	// Header
	sb.WriteString("# Generated by dotfiles TUI\n")
	sb.WriteString("\n")

	// Font settings
	sb.WriteString("# Font settings\n")
	// font-family is repeatable. Reset the inherited list before installing the
	// managed primary so an earlier native fallback cannot remain primary.
	sb.WriteString("font-family =\n")
	sb.WriteString(fmt.Sprintf("font-family = %s\n", cfg.FontFamily))
	sb.WriteString(fmt.Sprintf("font-size = %d\n\n", cfg.FontSize))

	// Window appearance
	sb.WriteString("# Window appearance\n")
	writeGhosttyThemeDirectives(&sb, p)
	// Emit explicit defaults too; omission would let an earlier native source
	// keep opacity/blur active and make the dashboard's 100/0 selections lie.
	opacity := float64(cfg.Opacity) / 100.0
	sb.WriteString(fmt.Sprintf("background-opacity = %.2f\n", opacity))
	sb.WriteString(fmt.Sprintf("background-blur = %d\n", cfg.BlurRadius))
	sb.WriteString(fmt.Sprintf("window-decoration = %t\n", cfg.WindowDecorations))
	sb.WriteString(fmt.Sprintf("confirm-close-surface = %t\n", cfg.ConfirmClose))
	sb.WriteString("\n")

	// Cursor
	sb.WriteString("# Cursor\n")
	sb.WriteString(fmt.Sprintf("cursor-style = %s\n", cfg.CursorStyle))
	sb.WriteString("\n")

	// Scrollback
	sb.WriteString("# Scrollback\n")
	sb.WriteString(fmt.Sprintf("scrollback-limit = %d\n\n", cfg.ScrollbackLines))

	// Keybindings based on tab binding preference
	sb.WriteString("# Tab keybindings\n")
	switch cfg.TabBindings {
	case "super":
		sb.WriteString("keybind = super+t=new_tab\n")
		sb.WriteString("keybind = super+w=close_surface\n")
		sb.WriteString("keybind = super+shift+]=next_tab\n")
		sb.WriteString("keybind = super+shift+[=previous_tab\n")
	case "ctrl":
		sb.WriteString("keybind = ctrl+t=new_tab\n")
		sb.WriteString("keybind = ctrl+w=close_surface\n")
		sb.WriteString("keybind = ctrl+tab=next_tab\n")
		sb.WriteString("keybind = ctrl+shift+tab=previous_tab\n")
	case "ctrl-shift":
		sb.WriteString("keybind = ctrl+shift+t=new_tab\n")
		sb.WriteString("keybind = ctrl+shift+w=close_surface\n")
		sb.WriteString("keybind = ctrl+tab=next_tab\n")
		sb.WriteString("keybind = ctrl+shift+tab=previous_tab\n")
	}
	sb.WriteString("\n")

	return sb.String()
}

func normalizedGhosttyConfig(cfg GhosttyConfig) GhosttyConfig {
	cfg.FontFamily = singleLineConfigText(cfg.FontFamily)
	if cfg.FontFamily == "" {
		cfg.FontFamily = "JetBrains Mono"
	}
	if cfg.FontSize <= 0 || cfg.FontSize > 512 {
		cfg.FontSize = 14
	}
	if cfg.Opacity < 0 || cfg.Opacity > 100 {
		cfg.Opacity = 100
	}
	if cfg.BlurRadius < 0 || cfg.BlurRadius > 100 {
		cfg.BlurRadius = 0
	}
	if cfg.ScrollbackLines <= 0 {
		cfg.ScrollbackLines = 10_000_000
	}
	if cfg.CursorStyle != "block" && cfg.CursorStyle != "bar" && cfg.CursorStyle != "underline" {
		cfg.CursorStyle = "block"
	}
	if cfg.TabBindings != "super" && cfg.TabBindings != "ctrl" && cfg.TabBindings != "ctrl-shift" {
		cfg.TabBindings = "super"
	}
	return cfg
}

func writeGhosttyThemeDirectives(sb *strings.Builder, p theme.Palette) {
	fmt.Fprintf(sb, "background = %s\n", p.Bg)
	fmt.Fprintf(sb, "foreground = %s\n", p.Text)
	for slot, color := range ghosttyANSIPalette(p) {
		fmt.Fprintf(sb, "palette = %d=%s\n", slot, color)
	}
	fmt.Fprintf(sb, "selection-background = %s\n", p.Overlay)
	fmt.Fprintf(sb, "selection-foreground = %s\n", p.TextBright)
	fmt.Fprintf(sb, "cursor-color = %s\n", p.Accent)
	fmt.Fprintf(sb, "cursor-text = %s\n", p.Bg)
	sb.WriteString("\n")
}

func ghosttyANSIPalette(p theme.Palette) []string {
	black := p.Bg
	white := p.Text
	brightBlack := p.Surface
	brightWhite := p.TextBright
	if !isDarkHexColor(p.Bg) {
		black = p.Text
		white = p.Surface
		brightBlack = p.TextMuted
		brightWhite = p.Bg
	}

	return []string{
		black,
		p.Error,
		p.Success,
		p.Warning,
		p.Info,
		p.AccentAlt,
		p.Accent,
		white,
		brightBlack,
		p.Error,
		p.Success,
		p.Warning,
		p.Info,
		p.AccentAlt,
		p.Accent,
		brightWhite,
	}
}

// WriteGhosttyConfig updates only dotfiles' delimited section in the native
// Ghostty config. Settings and comments outside that exact section remain
// user-owned and are preserved byte-for-byte.
func WriteGhosttyConfig(cfg GhosttyConfig, themeName string) error {
	_, err := WriteGhosttyConfigTracked(cfg, themeName)
	return err
}

func WriteGhosttyConfigTracked(cfg GhosttyConfig, themeName string) (MutationEvidence, error) {
	configPath, err := GhosttyConfigMutationPath()
	if err != nil {
		return MutationEvidence{}, fmt.Errorf("discover active Ghostty config: %w", err)
	}
	return WriteGhosttyConfigAtTracked(configPath, cfg, themeName)
}

// WriteGhosttyConfigAt applies to the exact source accepted by a reviewed plan.
// The target must be one of Ghostty's platform config candidates; callers
// cannot redirect the writer to an arbitrary path.
func WriteGhosttyConfigAt(configPath string, cfg GhosttyConfig, themeName string) error {
	_, err := WriteGhosttyConfigAtTracked(configPath, cfg, themeName)
	return err
}

func WriteGhosttyConfigAtTracked(configPath string, cfg GhosttyConfig, themeName string) (MutationEvidence, error) {
	return writeGhosttyConfigAtRevisionTracked(configPath, cfg, themeName, nil)
}

// WriteGhosttyConfigAtRevisionTracked applies a plan-accepted Ghostty revision.
func WriteGhosttyConfigAtRevisionTracked(configPath string, cfg GhosttyConfig, themeName string, accepted safefile.Revision) (MutationEvidence, error) {
	if !accepted.Tracked() {
		return MutationEvidence{}, fmt.Errorf("%w: accepted Ghostty revision is untracked", safefile.ErrRevisionChanged)
	}
	return writeGhosttyConfigAtRevisionTracked(configPath, cfg, themeName, &accepted)
}

func writeGhosttyConfigAtRevisionTracked(configPath string, cfg GhosttyConfig, themeName string, accepted *safefile.Revision) (MutationEvidence, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return MutationEvidence{}, fmt.Errorf("failed to get home directory: %w", err)
	}
	cleanTarget := filepath.Clean(configPath)
	allowed := false
	for _, candidate := range ghosttyConfigCandidates(home) {
		if cleanTarget == filepath.Clean(candidate) {
			allowed = true
			break
		}
	}
	if !allowed {
		return MutationEvidence{}, fmt.Errorf("refusing unsupported Ghostty config target %s", configPath)
	}
	managed := wrapManagedConfigSection(
		ghosttyManagedStart,
		ghosttyManagedEnd,
		GenerateGhosttyConfig(cfg, themeName),
	)

	var evidence MutationEvidence
	err = withToolConfigLock(cleanTarget, func(root, rel string) error {
		existing, revision, err := readToolConfig(root, rel)
		if err != nil {
			return err
		}
		if accepted != nil && revision != *accepted {
			return fmt.Errorf("%w: Ghostty config changed after plan acceptance", safefile.ErrRevisionChanged)
		}
		merged, _, err := mergeManagedConfigSection(
			existing,
			managed,
			ghosttyManagedStart,
			ghosttyManagedEnd,
			"Ghostty config",
		)
		if err != nil {
			return err
		}
		if revision.Exists() && bytes.Equal(existing, merged) {
			evidence = MutationEvidence{Path: cleanTarget, Revision: revision}
			return nil
		}
		expected := revision
		if accepted != nil {
			expected = *accepted
		}
		committed, err := replaceToolConfigAtRevisionTracked(root, rel, expected, merged)
		if err != nil {
			return fmt.Errorf("write managed Ghostty config: %w", err)
		}
		evidence = MutationEvidence{Path: cleanTarget, Revision: committed}
		return nil
	})
	return evidence, err
}
