package tools

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/tekierz/dotfiles/internal/pkg"
	themepkg "github.com/tekierz/dotfiles/internal/theme"
)

// GitConfig holds Git configuration settings
type GitConfig struct {
	DeltaSideBySide  bool
	DefaultBranch    string
	Aliases          []string // "st", "co", "br", "ci", "lg"
	PullRebase       bool
	SignCommits      bool
	CredentialHelper string // "cache", "store", "osxkeychain"

	AutoSetupRemote bool   // push.autoSetupRemote
	MergeTool       string // "vimdiff", "nvimdiff", "meld"
	DiffTool        string // "delta" (default), "difftastic", "vimdiff"/"nvimdiff"
}

// GitTool represents Git version control
type GitTool struct {
	BaseTool
}

// NewGitTool creates a new Git tool
func NewGitTool() *GitTool {
	home, _ := os.UserHomeDir()
	return &GitTool{
		BaseTool: BaseTool{
			id:          "git",
			name:        "Git",
			description: "Distributed version control system",
			icon:        "",
			category:    CategoryGit,
			packages: map[pkg.Platform][]string{
				pkg.PlatformMacOS:  {"git"},
				pkg.PlatformArch:   {"git"},
				pkg.PlatformDebian: {"git"},
			},
			configPaths: []string{
				filepath.Join(home, ".gitconfig"),
			},
			// UI metadata
			uiGroup:        UIGroupNone,
			configScreen:   13, // ScreenConfigGit
			defaultEnabled: true,
		},
	}
}

// normalizeDiffTool maps the Manage/wizard diff-tool vocabulary onto the values
// GenerateGitConfig branches on. An empty value (older configs that predate the
// DiffTool field) defaults to delta so the generated config is unchanged for them.
func normalizeDiffTool(diffTool string) string {
	switch diffTool {
	case "difftastic":
		return "difftastic"
	case "vimdiff", "nvimdiff":
		return diffTool
	default:
		return "delta"
	}
}

func gitDeltaSyntaxTheme(themeName string) string {
	name := strings.ToLower(themeName)

	switch {
	case strings.HasSuffix(name, "-latte"):
		return "GitHub"
	case strings.HasSuffix(name, "-light"):
		if strings.Contains(name, "gruvbox") {
			return "gruvbox-light"
		}
		if name == "solarized-light" {
			return "\"Solarized (light)\""
		}
		return "OneHalfLight"
	case strings.Contains(name, "gruvbox"):
		return "gruvbox-dark"
	case strings.Contains(name, "nord"):
		return "Nord"
	case strings.Contains(name, "dracula"):
		return "Dracula"
	default:
		return "OneHalfDark"
	}
}

// GenerateGitConfig builds the .gitconfig content
func GenerateGitConfig(cfg GitConfig, theme string) string {
	var sb strings.Builder
	p := themepkg.GetOrDefault(theme)

	// Header comment
	sb.WriteString("# Generated by dotfiles TUI\n")
	sb.WriteString(fmt.Sprintf("# Theme: %s\n\n", theme))

	// Core settings
	sb.WriteString("[init]\n")
	sb.WriteString(fmt.Sprintf("\tdefaultBranch = %s\n\n", cfg.DefaultBranch))

	// Pull behavior
	sb.WriteString("[pull]\n")
	if cfg.PullRebase {
		sb.WriteString("\trebase = true\n")
	} else {
		sb.WriteString("\trebase = false\n")
	}
	sb.WriteString("\n")

	// Push behavior
	sb.WriteString("[push]\n")
	sb.WriteString(fmt.Sprintf("\tautoSetupRemote = %t\n\n", cfg.AutoSetupRemote))

	// Credential helper
	if cfg.CredentialHelper != "" && cfg.CredentialHelper != "none" {
		sb.WriteString("[credential]\n")
		sb.WriteString(fmt.Sprintf("\thelper = %s\n\n", cfg.CredentialHelper))
	}

	// Commit signing
	if cfg.SignCommits {
		sb.WriteString("[commit]\n")
		sb.WriteString("\tgpgsign = true\n\n")
	}

	// Diff tool. The choice drives which (if any) external diff pager is wired
	// in: delta routes git's pager + interactive diffFilter through delta and
	// emits a [delta] block; difftastic and vimdiff/nvimdiff must NOT force the
	// delta pager (that was the bug — the diff-tool selection was ignored).
	switch normalizeDiffTool(cfg.DiffTool) {
	case "difftastic":
		// difftastic's documented git integration: register it as the external
		// diff driver. Leave core.pager unset so git uses its own pager.
		sb.WriteString("[core]\n")
		sb.WriteString("\teditor = nvim\n\n")
		sb.WriteString("[diff]\n")
		sb.WriteString("\texternal = difft\n")
		sb.WriteString("\tcolorMoved = default\n\n")
		sb.WriteString("[merge]\n")
		sb.WriteString("\tconflictstyle = diff3\n")
		if cfg.MergeTool != "" {
			sb.WriteString(fmt.Sprintf("\ttool = %s\n", cfg.MergeTool))
		}
		sb.WriteString("\n")

	case "vimdiff", "nvimdiff":
		// Use (n)vim as the interactive difftool; do not force the delta pager.
		sb.WriteString("[core]\n")
		sb.WriteString("\teditor = nvim\n\n")
		sb.WriteString("[diff]\n")
		sb.WriteString(fmt.Sprintf("\ttool = %s\n", cfg.DiffTool))
		sb.WriteString("\tcolorMoved = default\n\n")
		sb.WriteString("[merge]\n")
		sb.WriteString("\tconflictstyle = diff3\n")
		if cfg.MergeTool != "" {
			sb.WriteString(fmt.Sprintf("\ttool = %s\n", cfg.MergeTool))
		}
		sb.WriteString("\n")

	default: // "delta"
		sb.WriteString("[core]\n")
		sb.WriteString("\tpager = delta\n")
		sb.WriteString("\teditor = nvim\n\n")

		sb.WriteString("[interactive]\n")
		sb.WriteString("\tdiffFilter = delta --color-only\n\n")

		sb.WriteString("[delta]\n")
		sb.WriteString("\tnavigate = true\n")
		if cfg.DeltaSideBySide {
			sb.WriteString("\tside-by-side = true\n")
		}
		sb.WriteString("\tline-numbers = true\n")
		sb.WriteString(fmt.Sprintf("\tminus-style = normal %s\n", p.Error))
		sb.WriteString(fmt.Sprintf("\tplus-style = normal %s\n", p.Success))
		sb.WriteString(fmt.Sprintf("\tminus-emph-style = normal %s bold\n", p.Error))
		sb.WriteString(fmt.Sprintf("\tplus-emph-style = normal %s bold\n", p.Success))
		sb.WriteString(fmt.Sprintf("\tfile-style = %s bold\n", p.Accent))
		sb.WriteString(fmt.Sprintf("\thunk-header-style = %s bold\n", p.AccentAlt))
		sb.WriteString(fmt.Sprintf("\tsyntax-theme = %s\n\n", gitDeltaSyntaxTheme(theme)))

		sb.WriteString("[merge]\n")
		sb.WriteString("\tconflictstyle = diff3\n")
		if cfg.MergeTool != "" {
			sb.WriteString(fmt.Sprintf("\ttool = %s\n", cfg.MergeTool))
		}
		sb.WriteString("\n")

		sb.WriteString("[diff]\n")
		sb.WriteString("\tcolorMoved = default\n\n")
	}

	// Aliases
	sb.WriteString("[alias]\n")
	for _, alias := range cfg.Aliases {
		switch alias {
		case "st":
			sb.WriteString("\tst = status\n")
		case "co":
			sb.WriteString("\tco = checkout\n")
		case "br":
			sb.WriteString("\tbr = branch\n")
		case "ci":
			sb.WriteString("\tci = commit\n")
		case "lg":
			sb.WriteString("\tlg = log --oneline --graph --decorate\n")
		}
	}

	return sb.String()
}

// WriteGitConfig writes the .gitconfig file to disk
func WriteGitConfig(cfg GitConfig, theme string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}

	configPath := filepath.Join(home, ".gitconfig")
	content := GenerateGitConfig(cfg, theme)
	return writeToolConfig(configPath, []byte(content))
}
