package tools

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/tekierz/dotfiles/internal/pkg"
)

// GitConfig holds Git configuration settings
type GitConfig struct {
	DeltaSideBySide  bool
	DefaultBranch    string
	Aliases          []string // "st", "co", "br", "ci", "lg"
	PullRebase       bool
	SignCommits      bool
	CredentialHelper string // "cache", "store", "osxkeychain"
}

// GitTool represents Git version control
type GitTool struct {
	BaseTool
}

// NewGitTool creates a new Git tool
func NewGitTool() *GitTool {
	home, _ := os.UserHomeDir()
	return &GitTool{
		BaseTool: BaseTool{
			id:          "git",
			name:        "Git",
			description: "Distributed version control system",
			icon:        "",
			category:    CategoryGit,
			packages: map[pkg.Platform][]string{
				pkg.PlatformMacOS:  {"git"},
				pkg.PlatformArch:   {"git"},
				pkg.PlatformDebian: {"git"},
			},
			configPaths: []string{
				filepath.Join(home, ".gitconfig"),
			},
			// UI metadata
			uiGroup:        UIGroupNone,
			configScreen:   13, // ScreenConfigGit
			defaultEnabled: true,
		},
	}
}

// GenerateGitConfig builds the .gitconfig content
func GenerateGitConfig(cfg GitConfig, theme string) string {
	var sb strings.Builder

	// Header comment
	sb.WriteString("# Generated by dotfiles TUI\n")
	sb.WriteString(fmt.Sprintf("# Theme: %s\n\n", theme))

	// Core settings
	sb.WriteString("[init]\n")
	sb.WriteString(fmt.Sprintf("\tdefaultBranch = %s\n\n", cfg.DefaultBranch))

	// Pull behavior
	sb.WriteString("[pull]\n")
	if cfg.PullRebase {
		sb.WriteString("\trebase = true\n")
	} else {
		sb.WriteString("\trebase = false\n")
	}
	sb.WriteString("\n")

	// Credential helper
	if cfg.CredentialHelper != "" && cfg.CredentialHelper != "none" {
		sb.WriteString("[credential]\n")
		sb.WriteString(fmt.Sprintf("\thelper = %s\n\n", cfg.CredentialHelper))
	}

	// Commit signing
	if cfg.SignCommits {
		sb.WriteString("[commit]\n")
		sb.WriteString("\tgpgsign = true\n\n")
	}

	// Delta pager (if delta is available)
	sb.WriteString("[core]\n")
	sb.WriteString("\tpager = delta\n")
	sb.WriteString("\teditor = nvim\n\n")

	sb.WriteString("[interactive]\n")
	sb.WriteString("\tdiffFilter = delta --color-only\n\n")

	sb.WriteString("[delta]\n")
	sb.WriteString("\tnavigate = true\n")
	if cfg.DeltaSideBySide {
		sb.WriteString("\tside-by-side = true\n")
	}
	sb.WriteString("\tline-numbers = true\n")
	sb.WriteString("\tsyntax-theme = Dracula\n\n")

	sb.WriteString("[merge]\n")
	sb.WriteString("\tconflictstyle = diff3\n\n")

	sb.WriteString("[diff]\n")
	sb.WriteString("\tcolorMoved = default\n\n")

	// Aliases
	sb.WriteString("[alias]\n")
	for _, alias := range cfg.Aliases {
		switch alias {
		case "st":
			sb.WriteString("\tst = status\n")
		case "co":
			sb.WriteString("\tco = checkout\n")
		case "br":
			sb.WriteString("\tbr = branch\n")
		case "ci":
			sb.WriteString("\tci = commit\n")
		case "lg":
			sb.WriteString("\tlg = log --oneline --graph --decorate\n")
		}
	}

	return sb.String()
}

// WriteGitConfig writes the .gitconfig file to disk
func WriteGitConfig(cfg GitConfig, theme string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}

	configPath := filepath.Join(home, ".gitconfig")
	content := GenerateGitConfig(cfg, theme)

	if err := os.WriteFile(configPath, []byte(content), 0600); err != nil {
		return fmt.Errorf("failed to write .gitconfig: %w", err)
	}

	return nil
}

// GenerateConfig implements Tool interface (uses defaults)
func (t *GitTool) GenerateConfig(theme string) string {
	cfg := GitConfig{
		DeltaSideBySide:  true,
		DefaultBranch:    "main",
		Aliases:          []string{"st", "co", "br", "ci", "lg"},
		PullRebase:       true,
		SignCommits:      false,
		CredentialHelper: "cache",
	}
	return GenerateGitConfig(cfg, theme)
}

// ApplyConfig implements Tool interface (uses defaults)
func (t *GitTool) ApplyConfig(theme string) error {
	cfg := GitConfig{
		DeltaSideBySide:  true,
		DefaultBranch:    "main",
		Aliases:          []string{"st", "co", "br", "ci", "lg"},
		PullRebase:       true,
		SignCommits:      false,
		CredentialHelper: "cache",
	}
	return WriteGitConfig(cfg, theme)
}
