package tools

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/tekierz/dotfiles/internal/operation"

	"github.com/tekierz/dotfiles/internal/pkg"
	"github.com/tekierz/dotfiles/internal/safefile"
	themepkg "github.com/tekierz/dotfiles/internal/theme"
)

// GitConfig holds Git configuration settings
type GitConfig struct {
	DeltaSideBySide  bool
	DefaultBranch    string
	Aliases          []string // "st", "co", "br", "ci", "lg"
	PullRebase       bool
	SignCommits      bool
	CredentialHelper string // "cache", "store", "osxkeychain"

	AutoSetupRemote bool   // push.autoSetupRemote
	MergeTool       string // "vimdiff", "nvimdiff", "meld"
	DiffTool        string // "delta" (default), "difftastic", "vimdiff"/"nvimdiff"
}

// GitTool represents Git version control
type GitTool struct {
	BaseTool
}

const (
	gitManagedIncludeStart = "# >>> dotfiles git include (managed)"
	gitManagedIncludeEnd   = "# <<< dotfiles git include (managed)"
	gitManagedConfigRel    = ".config/dotfiles/git/config"
	gitManagedIncludePath  = "~/.config/dotfiles/git/config"
)

// NewGitTool creates a new Git tool
func NewGitTool() *GitTool {
	home, _ := os.UserHomeDir()
	return &GitTool{
		BaseTool: BaseTool{
			id:          "git",
			name:        "Git",
			description: "Distributed version control system",
			icon:        "",
			category:    CategoryGit,
			packages: map[pkg.Platform][]string{
				pkg.PlatformMacOS:  {"git"},
				pkg.PlatformArch:   {"git"},
				pkg.PlatformDebian: {"git"},
			},
			configPaths: []string{
				filepath.Join(home, ".gitconfig"),
				filepath.Join(home, filepath.FromSlash(gitManagedConfigRel)),
			},
			// UI metadata
			uiGroup:        UIGroupNone,
			configScreen:   13, // ScreenConfigGit
			defaultEnabled: true,
		},
	}
}

// normalizeDiffTool maps the Manage/wizard diff-tool vocabulary onto the values
// GenerateGitConfig branches on. An empty value (older configs that predate the
// DiffTool field) defaults to delta so the generated config is unchanged for them.
func normalizeDiffTool(diffTool string) string {
	switch diffTool {
	case "difftastic":
		return "difftastic"
	case "vimdiff", "nvimdiff":
		return diffTool
	default:
		return "delta"
	}
}

func gitDeltaSyntaxTheme(themeName string) string {
	name := strings.ToLower(themeName)

	switch {
	case strings.HasSuffix(name, "-latte"):
		return "GitHub"
	case strings.HasSuffix(name, "-light"):
		if strings.Contains(name, "gruvbox") {
			return "gruvbox-light"
		}
		if name == "solarized-light" {
			return "\"Solarized (light)\""
		}
		return "OneHalfLight"
	case strings.Contains(name, "gruvbox"):
		return "gruvbox-dark"
	case strings.Contains(name, "nord"):
		return "Nord"
	case strings.Contains(name, "dracula"):
		return "Dracula"
	default:
		return "OneHalfDark"
	}
}

func brightenDeltaEmphBackground(hex string) string {
	if len(hex) != 7 || hex[0] != '#' {
		return hex
	}

	r, errR := strconv.ParseUint(hex[1:3], 16, 8)
	g, errG := strconv.ParseUint(hex[3:5], 16, 8)
	b, errB := strconv.ParseUint(hex[5:7], 16, 8)
	if errR != nil || errG != nil || errB != nil {
		return hex
	}

	brighten := func(v uint64) uint64 {
		return v + ((255 - v) * 30 / 100)
	}

	return fmt.Sprintf("#%02X%02X%02X", brighten(r), brighten(g), brighten(b))
}

// GenerateGitConfig builds the .gitconfig content
func GenerateGitConfig(cfg GitConfig, theme string) string {
	var sb strings.Builder
	p := themepkg.GetOrDefault(theme)
	defaultBranch := safeGitBranchName(cfg.DefaultBranch)
	credentialHelper := safeGitCredentialHelper(cfg.CredentialHelper)
	mergeTool := safeGitMergeTool(cfg.MergeTool)

	// Header comment
	sb.WriteString("# Generated by dotfiles TUI\n")
	sb.WriteString(fmt.Sprintf("# Theme: %s\n\n", singleLineConfigText(theme)))

	// Core settings
	sb.WriteString("[init]\n")
	sb.WriteString(fmt.Sprintf("\tdefaultBranch = %s\n\n", defaultBranch))

	// Pull behavior
	sb.WriteString("[pull]\n")
	if cfg.PullRebase {
		sb.WriteString("\trebase = true\n")
	} else {
		sb.WriteString("\trebase = false\n")
	}
	sb.WriteString("\n")

	// Push behavior
	sb.WriteString("[push]\n")
	sb.WriteString(fmt.Sprintf("\tautoSetupRemote = %t\n\n", cfg.AutoSetupRemote))

	// Credential helper
	if credentialHelper != "" {
		sb.WriteString("[credential]\n")
		if credentialHelper == "none" {
			// An empty helper resets the multi-valued helper list inherited from
			// earlier global sources.
			sb.WriteString("\thelper =\n\n")
		} else {
			sb.WriteString(fmt.Sprintf("\thelper = %s\n\n", credentialHelper))
		}
	}

	// Emit explicit false so an earlier native source cannot keep signing on.
	sb.WriteString("[commit]\n")
	sb.WriteString(fmt.Sprintf("\tgpgsign = %t\n\n", cfg.SignCommits))

	// Diff tool. The choice drives which (if any) external diff pager is wired
	// in: delta routes git's pager + interactive diffFilter through delta and
	// emits a [delta] block; difftastic and vimdiff/nvimdiff must NOT force the
	// delta pager (that was the bug — the diff-tool selection was ignored).
	switch normalizeDiffTool(cfg.DiffTool) {
	case "difftastic":
		// difftastic's documented git integration: register it as the external
		// diff driver. Leave core.pager unset so git uses its own pager.
		sb.WriteString("[core]\n")
		sb.WriteString("\n")
		sb.WriteString("[diff]\n")
		sb.WriteString("\texternal = difft\n")
		sb.WriteString("\tcolorMoved = default\n\n")
		sb.WriteString("[merge]\n")
		sb.WriteString("\tconflictstyle = diff3\n")
		if mergeTool != "" {
			sb.WriteString(fmt.Sprintf("\ttool = %s\n", mergeTool))
		}
		sb.WriteString("\n")

	case "vimdiff", "nvimdiff":
		// Use (n)vim as the interactive difftool; do not force the delta pager.
		sb.WriteString("[core]\n")
		sb.WriteString("\n")
		sb.WriteString("[diff]\n")
		sb.WriteString(fmt.Sprintf("\ttool = %s\n", cfg.DiffTool))
		sb.WriteString("\tcolorMoved = default\n\n")
		sb.WriteString("[merge]\n")
		sb.WriteString("\tconflictstyle = diff3\n")
		if mergeTool != "" {
			sb.WriteString(fmt.Sprintf("\ttool = %s\n", mergeTool))
		}
		sb.WriteString("\n")

	default: // "delta"
		sb.WriteString("[core]\n")
		sb.WriteString("\tpager = delta\n")
		sb.WriteString("\n")

		sb.WriteString("[interactive]\n")
		sb.WriteString("\tdiffFilter = delta --color-only\n\n")

		sb.WriteString("[delta]\n")
		sb.WriteString("\tnavigate = true\n")
		sb.WriteString(fmt.Sprintf("\tside-by-side = %t\n", cfg.DeltaSideBySide))
		sb.WriteString("\tline-numbers = true\n")
		sb.WriteString(fmt.Sprintf("\tminus-style = \"normal %s\"\n", p.Error))
		sb.WriteString(fmt.Sprintf("\tplus-style = \"normal %s\"\n", p.Success))
		sb.WriteString(fmt.Sprintf("\tminus-emph-style = \"normal %s bold\"\n", brightenDeltaEmphBackground(p.Error)))
		sb.WriteString(fmt.Sprintf("\tplus-emph-style = \"normal %s bold\"\n", brightenDeltaEmphBackground(p.Success)))
		sb.WriteString(fmt.Sprintf("\tfile-style = \"%s bold\"\n", p.Accent))
		sb.WriteString(fmt.Sprintf("\thunk-header-style = \"%s bold\"\n", p.AccentAlt))
		sb.WriteString(fmt.Sprintf("\tsyntax-theme = %s\n\n", gitDeltaSyntaxTheme(theme)))

		sb.WriteString("[merge]\n")
		sb.WriteString("\tconflictstyle = diff3\n")
		if mergeTool != "" {
			sb.WriteString(fmt.Sprintf("\ttool = %s\n", mergeTool))
		}
		sb.WriteString("\n")

		sb.WriteString("[diff]\n")
		sb.WriteString("\tcolorMoved = default\n\n")
	}

	// Aliases
	sb.WriteString("[alias]\n")
	for _, alias := range cfg.Aliases {
		switch alias {
		case "st":
			sb.WriteString("\tst = status\n")
		case "co":
			sb.WriteString("\tco = checkout\n")
		case "br":
			sb.WriteString("\tbr = branch\n")
		case "ci":
			sb.WriteString("\tci = commit\n")
		case "lg":
			sb.WriteString("\tlg = log --oneline --graph --decorate\n")
		}
	}

	return sb.String()
}

func safeGitBranchName(value string) string {
	if value == "" || strings.HasPrefix(value, "-") || strings.HasPrefix(value, "/") || strings.HasSuffix(value, "/") ||
		strings.HasSuffix(value, ".") || strings.HasSuffix(value, ".lock") || strings.Contains(value, "..") || strings.Contains(value, "@{") {
		return "main"
	}
	for _, r := range value {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
		case r == '-', r == '_', r == '.', r == '/':
		default:
			return "main"
		}
	}
	return value
}

func safeGitCredentialHelper(value string) string {
	switch value {
	case "cache", "store", "osxkeychain", "none", "":
		return value
	default:
		return "none"
	}
}

func safeGitMergeTool(value string) string {
	switch value {
	case "vimdiff", "nvimdiff", "meld":
		return value
	default:
		return ""
	}
}

// WriteGitConfig preserves the user's native .gitconfig and installs one
// managed include. Dotfiles owns the included file, not the surrounding Git
// configuration, so comments, identity, conditional includes, and unknown
// settings remain byte-for-byte intact.
func WriteGitConfig(cfg GitConfig, theme string) error {
	_, err := WriteGitConfigTracked(cfg, theme)
	return err
}

func WriteGitConfigTracked(cfg GitConfig, theme string) ([]MutationEvidence, error) {
	if override := os.Getenv("GIT_CONFIG_GLOBAL"); override != "" {
		return nil, fmt.Errorf("refusing to write ~/.gitconfig while GIT_CONFIG_GLOBAL overrides the global source: %s", override)
	}
	if count := strings.TrimSpace(os.Getenv("GIT_CONFIG_COUNT")); count != "" && count != "0" {
		return nil, fmt.Errorf("refusing to write Git config while GIT_CONFIG_COUNT command overrides are active")
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, fmt.Errorf("failed to get home directory: %w", err)
	}

	configPath := filepath.Join(home, ".gitconfig")
	managedContent := []byte(GenerateGitConfig(cfg, theme))
	includeSection := wrapManagedConfigSection(
		gitManagedIncludeStart,
		gitManagedIncludeEnd,
		"[include]\n\tpath = "+gitManagedIncludePath,
	)

	var evidence []MutationEvidence
	err = withToolConfigLock(configPath, func(root, rel string) error {
		existing, revision, err := readToolConfig(root, rel)
		if err != nil {
			return err
		}
		merged, _, err := mergeManagedConfigSection(
			existing,
			includeSection,
			gitManagedIncludeStart,
			gitManagedIncludeEnd,
			".gitconfig",
		)
		if err != nil {
			return err
		}

		existingManaged, managedRevision, err := readToolConfig(root, gitManagedConfigRel)
		if err != nil {
			return fmt.Errorf("inspect managed Git config: %w", err)
		}
		if managedRevision.Exists() && !hasGeneratedConfigHeader(existingManaged) {
			return fmt.Errorf("%w: %s", ErrUnmanagedConfig, filepath.Join(home, filepath.FromSlash(gitManagedConfigRel)))
		}
		managedChanged := !managedRevision.Exists() || !bytes.Equal(existingManaged, managedContent)
		committedManaged := managedRevision
		if managedChanged {
			committedManaged, err = replaceToolConfigAtRevisionTracked(root, gitManagedConfigRel, managedRevision, managedContent)
			if err != nil {
				rollbackErr := rollbackManagedArtifactIfApplied(root, gitManagedConfigRel, managedContent, existingManaged, managedRevision.Exists())
				return errors.Join(fmt.Errorf("write managed Git config: %w", err), rollbackErr)
			}
		}
		evidence = append(evidence, MutationEvidence{Path: filepath.Join(home, filepath.FromSlash(gitManagedConfigRel)), Revision: committedManaged})
		committedRoot := revision
		if !revision.Exists() || !bytes.Equal(existing, merged) {
			committedRoot, err = replaceToolConfigAtRevisionTracked(root, rel, revision, merged)
			if err != nil {
				if errorReportsCommittedMutation(err) {
					return fmt.Errorf("install managed Git include: %w", err)
				}
				var rollbackErr error
				if managedChanged {
					rollbackErr = rollbackManagedArtifact(root, gitManagedConfigRel, managedContent, existingManaged, managedRevision.Exists())
				}
				return errors.Join(fmt.Errorf("install managed Git include: %w", err), rollbackErr)
			}
		}
		evidence = append(evidence, MutationEvidence{Path: configPath, Revision: committedRoot})
		return nil
	})
	if err != nil {
		return nil, partialMutationError(err, evidence)
	}
	return evidence, nil
}

// WriteGitConfigAtRevisionsTracked applies the complete plan-accepted Git set.
func WriteGitConfigAtRevisionsTracked(cfg GitConfig, theme string, rootAccepted, managedAccepted safefile.Revision) ([]MutationEvidence, error) {
	return writeGitConfigAtBoundAuthoritiesTracked(cfg, theme, rootAccepted, nil, managedAccepted, nil, operation.DefaultLocker, true)
}

func WriteGitConfigAtAuthoritiesTracked(cfg GitConfig, theme string, rootAccepted safefile.Revision, rootParents *safefile.ParentChain, managedAccepted safefile.Revision, managedParents *safefile.ParentChain) ([]MutationEvidence, error) {
	return WriteGitConfigAtBoundAuthoritiesTracked(cfg, theme, rootAccepted, rootParents, managedAccepted, managedParents, operation.DefaultLocker)
}

func WriteGitConfigAtBoundAuthoritiesTracked(cfg GitConfig, theme string, rootAccepted safefile.Revision, rootParents *safefile.ParentChain, managedAccepted safefile.Revision, managedParents *safefile.ParentChain, locker operation.Locker) ([]MutationEvidence, error) {
	return writeGitConfigAtBoundAuthoritiesTracked(cfg, theme, rootAccepted, rootParents, managedAccepted, managedParents, locker, false)
}

func writeGitConfigAtBoundAuthoritiesTracked(cfg GitConfig, theme string, rootAccepted safefile.Revision, rootParents *safefile.ParentChain, managedAccepted safefile.Revision, managedParents *safefile.ParentChain, locker operation.Locker, allowRevisionCompatibility bool) ([]MutationEvidence, error) {
	if !rootAccepted.Tracked() || !managedAccepted.Tracked() {
		return nil, fmt.Errorf("%w: accepted Git revisions must be tracked", safefile.ErrRevisionChanged)
	}
	if !allowRevisionCompatibility && (!rootParents.Tracked() || !managedParents.Tracked() || locker == nil) {
		return nil, fmt.Errorf("%w: accepted Git authority is incomplete", safefile.ErrParentChanged)
	}
	if override := os.Getenv("GIT_CONFIG_GLOBAL"); override != "" {
		return nil, fmt.Errorf("refusing to write ~/.gitconfig while GIT_CONFIG_GLOBAL overrides the global source: %s", override)
	}
	if count := strings.TrimSpace(os.Getenv("GIT_CONFIG_COUNT")); count != "" && count != "0" {
		return nil, fmt.Errorf("refusing to write Git config while GIT_CONFIG_COUNT command overrides are active")
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, fmt.Errorf("failed to get home directory: %w", err)
	}
	configPath := filepath.Join(home, ".gitconfig")
	managedPath := filepath.Join(home, filepath.FromSlash(gitManagedConfigRel))
	managedContent := []byte(GenerateGitConfig(cfg, theme))
	includeSection := wrapManagedConfigSection(gitManagedIncludeStart, gitManagedIncludeEnd, "[include]\n\tpath = "+gitManagedIncludePath)

	var results, committed []MutationEvidence
	lock := withToolConfigLockNoCreate
	if !allowRevisionCompatibility {
		lock = func(path string, mutate func(string, string) error) error {
			return withToolConfigLockAuthorized(path, locker, mutate)
		}
	}
	err = lock(configPath, func(root, rel string) error {
		var existing []byte
		var rootCurrent safefile.Revision
		if rootParents != nil {
			existing, rootCurrent, err = safefile.ReadWithinAuthorized(root, rel, rootParents)
		} else {
			existing, rootCurrent, err = readToolConfig(root, rel)
		}
		if err != nil {
			return err
		}
		var existingManaged []byte
		var managedCurrent safefile.Revision
		if managedParents != nil {
			existingManaged, managedCurrent, err = safefile.ReadWithinAuthorized(root, gitManagedConfigRel, managedParents)
		} else {
			existingManaged, managedCurrent, err = readToolConfig(root, gitManagedConfigRel)
		}
		if err != nil {
			return fmt.Errorf("inspect managed Git config: %w", err)
		}
		// Validate the complete accepted set before parsing ownership or making
		// the first mutation.
		if rootCurrent != rootAccepted || managedCurrent != managedAccepted {
			return fmt.Errorf("%w: Git config set changed after plan acceptance", safefile.ErrRevisionChanged)
		}
		merged, _, err := mergeManagedConfigSection(existing, includeSection, gitManagedIncludeStart, gitManagedIncludeEnd, ".gitconfig")
		if err != nil {
			return err
		}
		if managedCurrent.Exists() && !hasGeneratedConfigHeader(existingManaged) {
			return fmt.Errorf("%w: %s", ErrUnmanagedConfig, managedPath)
		}

		managedResult := managedCurrent
		if !managedCurrent.Exists() || !bytes.Equal(existingManaged, managedContent) {
			if managedParents != nil {
				managedResult, err = replaceToolConfigAtRevisionNoCreateAuthorizedTracked(root, gitManagedConfigRel, managedAccepted, managedParents, managedContent)
			} else {
				managedResult, err = replaceToolConfigAtRevisionNoCreateTracked(root, gitManagedConfigRel, managedAccepted, managedContent)
			}
			if err != nil {
				return fmt.Errorf("write managed Git config: %w", err)
			}
		}
		managedEvidence := MutationEvidence{Path: managedPath, Revision: managedResult, Parents: managedParents}
		results = append(results, managedEvidence)
		if managedResult != managedAccepted {
			committed = append(committed, managedEvidence)
		}

		rootResult := rootCurrent
		if !rootCurrent.Exists() || !bytes.Equal(existing, merged) {
			if rootParents != nil {
				rootResult, err = replaceToolConfigAtRevisionNoCreateAuthorizedTracked(root, rel, rootAccepted, rootParents, merged)
			} else {
				rootResult, err = replaceToolConfigAtRevisionNoCreateTracked(root, rel, rootAccepted, merged)
			}
			if err != nil {
				return fmt.Errorf("install managed Git include: %w", err)
			}
		}
		rootEvidence := MutationEvidence{Path: configPath, Revision: rootResult, Parents: rootParents}
		results = append(results, rootEvidence)
		if rootResult != rootAccepted {
			committed = append(committed, rootEvidence)
		}
		return nil
	})
	if err != nil {
		return nil, partialMutationError(err, committed)
	}
	return results, nil
}
