package tools

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/tekierz/dotfiles/internal/pkg"
)

// GlowConfig holds Glow configuration settings
type GlowConfig struct {
	Pager string // "auto", "less", "never"
	Style string // "auto", "dark", "light", "dracula", etc.
	Width int    // Max width for rendering (0 = terminal width)
}

// GlowTool represents glow markdown viewer
type GlowTool struct {
	BaseTool
}

// NewGlowTool creates a new glow tool
func NewGlowTool() *GlowTool {
	return &GlowTool{
		BaseTool: BaseTool{
			id:          "glow",
			name:        "Glow",
			description: "Render markdown on the CLI",
			icon:        "󰈙",
			category:    CategoryUtility,
			packages: map[pkg.Platform][]string{
				pkg.PlatformMacOS:  {"glow"},
				pkg.PlatformArch:   {"glow"},
				pkg.PlatformDebian: {"glow"},
			},
			configPaths: []string{},
			// UI metadata
			uiGroup:        UIGroupCLITools,
			configScreen:   31, // ScreenConfigGlow - has dedicated config screen
			defaultEnabled: true,
		},
	}
}

// GenerateGlowConfig builds the glow.yml content
func GenerateGlowConfig(cfg GlowConfig, theme string) string {
	var sb strings.Builder

	// Header
	sb.WriteString("# Generated by dotfiles TUI\n")
	sb.WriteString(fmt.Sprintf("# Theme: %s\n\n", theme))

	// Style
	glowStyle := cfg.Style
	if glowStyle == "auto" {
		glowStyle = "dark"
	}
	sb.WriteString(fmt.Sprintf("style: \"%s\"\n", glowStyle))

	// Pager
	if cfg.Pager == "never" {
		sb.WriteString("pager: false\n")
	} else if cfg.Pager == "less" {
		sb.WriteString("pager: true\n")
	} else {
		sb.WriteString("pager: true\n")
	}

	// Width
	if cfg.Width > 0 {
		sb.WriteString(fmt.Sprintf("width: %d\n", cfg.Width))
	}

	// Local mode (don't try to use Charm cloud)
	sb.WriteString("\n# Local mode (no cloud)\n")
	sb.WriteString("local: true\n")

	// Mouse support
	sb.WriteString("mouse: true\n")

	return sb.String()
}

// WriteGlowConfig writes the glow config to disk
func WriteGlowConfig(cfg GlowConfig, theme string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}

	configDir := filepath.Join(home, ".config", "glow")
	if err := os.MkdirAll(configDir, 0700); err != nil {
		return fmt.Errorf("failed to create glow config directory: %w", err)
	}

	configPath := filepath.Join(configDir, "glow.yml")
	content := GenerateGlowConfig(cfg, theme)

	if err := os.WriteFile(configPath, []byte(content), 0600); err != nil {
		return fmt.Errorf("failed to write glow config: %w", err)
	}

	return nil
}

// GenerateConfig implements Tool interface (uses defaults)
func (t *GlowTool) GenerateConfig(theme string) string {
	cfg := GlowConfig{
		Pager: "auto",
		Style: "auto",
		Width: 80,
	}
	return GenerateGlowConfig(cfg, theme)
}

// ApplyConfig implements Tool interface (uses defaults)
func (t *GlowTool) ApplyConfig(theme string) error {
	cfg := GlowConfig{
		Pager: "auto",
		Style: "auto",
		Width: 80,
	}
	return WriteGlowConfig(cfg, theme)
}
