package tools

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/tekierz/dotfiles/internal/pkg"
	"github.com/tekierz/dotfiles/internal/safefile"
)

// GlowConfig holds Glow configuration settings
type GlowConfig struct {
	Pager string // "auto", "less", "never"
	Style string // "auto", "dark", "light", "dracula", etc.
	Width int    // Max width for rendering (0 = terminal width)
	Mouse bool   // Enable mouse support
}

// GlowTool represents glow markdown viewer
type GlowTool struct {
	BaseTool
}

// NewGlowTool creates a new glow tool
func NewGlowTool() *GlowTool {
	configPath, err := glowConfigPath()
	if err != nil {
		configPath = fallbackGlowConfigPath()
	}

	return &GlowTool{
		BaseTool: BaseTool{
			id:          "glow",
			name:        "Glow",
			description: "Render markdown on the CLI",
			icon:        "󰈙",
			category:    CategoryUtility,
			packages: map[pkg.Platform][]string{
				pkg.PlatformMacOS: {"glow"},
				pkg.PlatformArch:  {"glow"},
				// glow is not in stock Debian/Ubuntu repos (requires Charm keyring);
				// omitting Debian entry prevents a guaranteed-failing apt install.
			},
			configPaths: []string{configPath},
			// UI metadata
			uiGroup:        UIGroupCLITools,
			configScreen:   31, // ScreenConfigGlow - has dedicated config screen
			defaultEnabled: true,
		},
	}
}

// GenerateGlowConfig builds the glow.yml content
func GenerateGlowConfig(cfg GlowConfig, theme string) string {
	var sb strings.Builder

	// Header
	sb.WriteString("# Generated by dotfiles TUI\n")
	sb.WriteString(fmt.Sprintf("# Theme: %s\n\n", theme))

	// Style
	glowStyle := cfg.Style
	if glowStyle == "auto" {
		glowStyle = "dark"
	}
	sb.WriteString(fmt.Sprintf("style: \"%s\"\n", glowStyle))

	// Pager
	sb.WriteString(fmt.Sprintf("pager: %t\n", cfg.Pager != "never"))

	// Width
	if cfg.Width > 0 {
		sb.WriteString(fmt.Sprintf("width: %d\n", cfg.Width))
	}

	// Local mode (don't try to use Charm cloud)
	sb.WriteString("\n# Local mode (no cloud)\n")
	sb.WriteString("local: true\n")

	// Mouse support
	sb.WriteString(fmt.Sprintf("mouse: %t\n", cfg.Mouse))

	return sb.String()
}

// WriteGlowConfig writes the glow config to disk
func WriteGlowConfig(cfg GlowConfig, theme string) error {
	_, err := WriteGlowConfigTracked(cfg, theme)
	return err
}

// WriteGlowConfigTracked writes the glow config and returns the exact committed
// revision for rollback evidence.
func WriteGlowConfigTracked(cfg GlowConfig, theme string) (MutationEvidence, error) {
	configPath, err := glowConfigPath()
	if err != nil {
		return MutationEvidence{}, err
	}

	content := GenerateGlowConfig(cfg, theme)
	return writeToolConfigTracked(configPath, []byte(content))
}

// WriteGlowConfigAtRevisionTracked applies a plan-accepted Glow revision.
func WriteGlowConfigAtRevisionTracked(cfg GlowConfig, theme string, accepted safefile.Revision) (MutationEvidence, error) {
	configPath, err := glowConfigPath()
	if err != nil {
		return MutationEvidence{}, err
	}
	return writeToolConfigAtRevisionTracked(configPath, []byte(GenerateGlowConfig(cfg, theme)), accepted)
}

// glowConfigPath returns the config file glow itself loads. Glow resolves its
// config through go-app-paths' User scope: ~/Library/Preferences on macOS
// (NOT os.UserConfigDir's ~/Library/Application Support), XDG everywhere else.
func glowConfigPath() (string, error) {
	if runtime.GOOS == "darwin" {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("failed to get home directory: %w", err)
		}
		return filepath.Join(home, "Library", "Preferences", "glow", "glow.yml"), nil
	}
	userConfigDir, err := os.UserConfigDir()
	if err != nil {
		return "", fmt.Errorf("failed to get user config directory: %w", err)
	}
	return filepath.Join(userConfigDir, "glow", "glow.yml"), nil
}

func fallbackGlowConfigPath() string {
	home, err := os.UserHomeDir()
	if err != nil || home == "" {
		return filepath.Join(".config", "glow", "glow.yml")
	}
	return filepath.Join(home, ".config", "glow", "glow.yml")
}
