package tools

import (
	"bytes"
	"fmt"
	"path/filepath"
	"strings"
	"unicode"

	"github.com/tekierz/dotfiles/internal/operation"
	"github.com/tekierz/dotfiles/internal/pkg"
	"github.com/tekierz/dotfiles/internal/safefile"
)

const (
	lazyGitManagedHeader = "# Generated by dotfiles TUI\n"
	lazyGitCompatVersion = "LazyGit v0.62.1 (f2788e4)"
)

// LazyGitConfig exposes four deliberately bounded global concepts. ColorPreset
// and PagerPreset are product presets, not upstream LazyGit setting names.
type LazyGitConfig struct {
	SidePanelWidth string
	MouseEvents    bool
	ColorPreset    string // standard/light-high-contrast/custom
	PagerPreset    string // builtin/delta/custom
}

func normalizeLazyGitConfig(cfg LazyGitConfig) LazyGitConfig {
	if cfg.SidePanelWidth == "" {
		cfg.SidePanelWidth = "0.3333"
	}
	if cfg.ColorPreset == "" {
		cfg.ColorPreset = "standard"
	}
	if cfg.PagerPreset == "" {
		cfg.PagerPreset = "builtin"
	}
	if strings.HasPrefix(cfg.SidePanelWidth, ".") {
		cfg.SidePanelWidth = "0" + cfg.SidePanelWidth
	}
	return cfg
}

func ValidateLazyGitConfig(cfg LazyGitConfig, theme string) error {
	cfg = normalizeLazyGitConfig(cfg)
	if err := validateConfigToken("global LazyGit theme", theme); err != nil {
		return err
	}
	if err := validateLazyGitFraction(cfg.SidePanelWidth); err != nil {
		return err
	}
	if cfg.ColorPreset != "standard" && cfg.ColorPreset != "light-high-contrast" {
		return fmt.Errorf("custom LazyGit colors are read-only in this release")
	}
	if cfg.PagerPreset != "builtin" && cfg.PagerPreset != "delta" {
		return fmt.Errorf("custom LazyGit pagers are read-only in this release")
	}
	return nil
}

// ValidateLazyGitSidePanelWidth validates the exact decimal syntax accepted by
// the dashboard's LazyGit fraction editors without validating unrelated presets.
func ValidateLazyGitSidePanelWidth(value string) error {
	return validateLazyGitFraction(value)
}

func validateLazyGitFraction(value string) error {
	if value == "" || len(value) > 32 || strings.TrimSpace(value) != value || strings.ContainsAny(value, "eE+-_\r\n\x00") {
		return fmt.Errorf("LazyGit Side Panel Fraction must be a decimal from 0 through 1")
	}
	for _, r := range value {
		if unicode.IsControl(r) || isBidiControl(r) {
			return fmt.Errorf("LazyGit Side Panel Fraction contains unsafe characters")
		}
	}
	parts := strings.Split(value, ".")
	if len(parts) > 2 || (parts[0] == "" && (len(parts) != 2 || parts[1] == "")) || (len(parts) == 2 && parts[1] == "") {
		return fmt.Errorf("LazyGit Side Panel Fraction must be a decimal from 0 through 1")
	}
	for _, part := range parts {
		for _, r := range part {
			if r < '0' || r > '9' {
				return fmt.Errorf("LazyGit Side Panel Fraction must be a decimal from 0 through 1")
			}
		}
	}
	integer := parts[0]
	if integer == "" {
		integer = "0"
	}
	if integer != "0" && integer != "1" {
		return fmt.Errorf("LazyGit Side Panel Fraction must be between 0 and 1")
	}
	if integer == "1" && len(parts) == 2 && strings.Trim(parts[1], "0") != "" {
		return fmt.Errorf("LazyGit Side Panel Fraction must be between 0 and 1")
	}
	return nil
}

type LazyGitTool struct{ BaseTool }

func NewLazyGitTool() *LazyGitTool {
	t := &LazyGitTool{BaseTool: BaseTool{
		id: "lazygit", name: "LazyGit", description: "Simple terminal UI for Git commands", icon: "󰊢", category: CategoryGit,
		packages: map[pkg.Platform][]string{pkg.PlatformMacOS: {"lazygit"}, pkg.PlatformArch: {"lazygit"}},
		uiGroup:  UIGroupCLITools, configScreen: 28, defaultEnabled: true,
	}}
	if path, err := LazyGitConfigMutationPath(); err == nil {
		t.configPaths = []string{path}
	}
	return t
}

func (t *LazyGitTool) ConfigPaths() []string {
	path, err := LazyGitConfigMutationPath()
	if err != nil {
		return nil
	}
	return []string{path}
}
func (t *LazyGitTool) HasConfig() bool { return true }

// GenerateLazyGitConfig emits only the four dashboard concepts. Compatibility
// is pinned to LazyGit v0.62.1 (f2788e4); repo-local .git/lazygit.yml or a
// parent .lazygit.yml can override these global values.
func GenerateLazyGitConfig(cfg LazyGitConfig, theme string) string {
	cfg = normalizeLazyGitConfig(cfg)
	var sb strings.Builder
	sb.WriteString(lazyGitManagedHeader)
	sb.WriteString("# Color Preset: " + cfg.ColorPreset + "\n\n")
	sb.WriteString("gui:\n")
	sb.WriteString("  sidePanelWidth: " + cfg.SidePanelWidth + "\n")
	sb.WriteString(fmt.Sprintf("  mouseEvents: %t\n", cfg.MouseEvents))
	sb.WriteString("  theme:\n")
	if cfg.ColorPreset == "light-high-contrast" {
		sb.WriteString("    activeBorderColor: [blue, bold]\n    inactiveBorderColor: [default]\n    selectedLineBgColor: [reverse]\n    defaultFgColor: [black]\n")
	} else {
		sb.WriteString("    activeBorderColor: [green, bold]\n    inactiveBorderColor: [default]\n    selectedLineBgColor: [blue]\n    defaultFgColor: [default]\n")
	}
	sb.WriteString("git:\n  pagers:")
	if cfg.PagerPreset == "delta" {
		sb.WriteString("\n    - colorArg: always\n      pager: delta --dark --paging=never\n")
	} else {
		sb.WriteString(" []\n")
	}
	return sb.String()
}

func WriteLazyGitConfig(cfg LazyGitConfig, theme string) error {
	_, err := WriteLazyGitConfigTracked(cfg, theme)
	return err
}

func WriteLazyGitConfigTracked(cfg LazyGitConfig, theme string) (MutationEvidence, error) {
	return writeLazyGitConfigTrackedWithLocker(cfg, theme, operation.DefaultLocker)
}

func writeLazyGitConfigTrackedWithLocker(cfg LazyGitConfig, theme string, locker operation.Locker) (MutationEvidence, error) {
	if err := ValidateLazyGitConfig(cfg, theme); err != nil {
		return MutationEvidence{}, err
	}
	if locker == nil {
		return MutationEvidence{}, fmt.Errorf("LazyGit operation locker is unavailable")
	}
	path, err := LazyGitConfigMutationPath()
	if err != nil {
		return MutationEvidence{}, err
	}
	var evidence MutationEvidence
	err = withToolConfigLockAuthorized(path, locker, func(root, rel string) error {
		active, resolveErr := LazyGitConfigMutationPath()
		if resolveErr != nil {
			return resolveErr
		}
		if filepath.Clean(active) != filepath.Clean(path) {
			return fmt.Errorf("active LazyGit config changed from %s to %s while acquiring lock", path, active)
		}
		existing, revision, readErr := readToolConfig(root, rel)
		if readErr != nil {
			return readErr
		}
		if revision.Exists() && !IsManagedLazyGitConfigContent(existing) {
			return fmt.Errorf("existing LazyGit YAML is read-only because it is not an exact dotfiles-managed file")
		}
		desired := []byte(GenerateLazyGitConfig(cfg, theme))
		if revision.Exists() && bytes.Equal(existing, desired) {
			evidence = MutationEvidence{Path: path, Revision: revision}
			return nil
		}
		committed, writeErr := replaceToolConfigAtRevisionTracked(root, rel, revision, desired)
		if writeErr == nil {
			evidence = MutationEvidence{Path: path, Revision: committed}
		}
		return writeErr
	})
	return evidence, err
}

func WriteLazyGitConfigAtRevisionTracked(cfg LazyGitConfig, theme string, accepted safefile.Revision) (MutationEvidence, error) {
	path, err := LazyGitConfigMutationPath()
	if err != nil {
		return MutationEvidence{}, err
	}
	parents, err := compatibilityToolConfigParents(path)
	if err != nil {
		return MutationEvidence{}, err
	}
	return writeLazyGitConfigAtAuthorityTracked(path, cfg, theme, accepted, parents, operation.DefaultLocker)
}

func WriteLazyGitConfigAtAuthorityTracked(cfg LazyGitConfig, theme string, accepted safefile.Revision, parents *safefile.ParentChain, locker operation.Locker) (MutationEvidence, error) {
	path, err := LazyGitConfigMutationPath()
	if err != nil {
		return MutationEvidence{}, err
	}
	return writeLazyGitConfigAtAuthorityTracked(path, cfg, theme, accepted, parents, locker)
}

func writeLazyGitConfigAtAuthorityTracked(path string, cfg LazyGitConfig, theme string, accepted safefile.Revision, parents *safefile.ParentChain, locker operation.Locker) (MutationEvidence, error) {
	if err := ValidateLazyGitConfig(cfg, theme); err != nil {
		return MutationEvidence{}, err
	}
	if !accepted.Tracked() || parents == nil || !parents.Tracked() || locker == nil {
		return MutationEvidence{}, fmt.Errorf("%w: accepted LazyGit authority is incomplete", safefile.ErrParentChanged)
	}
	var evidence MutationEvidence
	err := withToolConfigLockAuthorized(path, locker, func(root, rel string) error {
		active, resolveErr := LazyGitConfigMutationPath()
		if resolveErr != nil {
			return resolveErr
		}
		if filepath.Clean(active) != filepath.Clean(path) {
			return fmt.Errorf("active LazyGit config changed from %s to %s while acquiring authority", path, active)
		}
		existing, current, readErr := safefile.ReadWithinAuthorized(root, rel, parents)
		if readErr != nil {
			return readErr
		}
		if current != accepted {
			return fmt.Errorf("%w: LazyGit config changed after plan acceptance", safefile.ErrRevisionChanged)
		}
		if current.Exists() && !IsManagedLazyGitConfigContent(existing) {
			return fmt.Errorf("existing LazyGit YAML is read-only because it is not an exact dotfiles-managed file")
		}
		desired := []byte(GenerateLazyGitConfig(cfg, theme))
		evidence = MutationEvidence{Path: path, Revision: current, Parents: parents}
		if current.Exists() && bytes.Equal(existing, desired) {
			return nil
		}
		committed, writeErr := replaceToolConfigAtRevisionNoCreateAuthorizedTracked(root, rel, accepted, parents, desired)
		if writeErr == nil {
			evidence.Revision = committed
		}
		return writeErr
	})
	return evidence, err
}

func IsManagedLazyGitConfigContent(content []byte) bool {
	if !bytes.HasPrefix(content, []byte(lazyGitManagedHeader+"# Color Preset: standard\n")) &&
		!bytes.HasPrefix(content, []byte(lazyGitManagedHeader+"# Color Preset: light-high-contrast\n")) {
		return false
	}
	parsed, err := parseLazyGitYAML("managed-lazygit.yml", content)
	if err != nil || ValidateLazyGitConfig(parsed.Config, "managed") != nil {
		return false
	}
	return bytes.Equal(content, []byte(GenerateLazyGitConfig(parsed.Config, "managed")))
}

func isLegacyManagedLazyGitConfigContent(content []byte) bool {
	// Prototype output did not carry an ownership checksum. A copied header and
	// lookalike sections cannot safely prove whole-file ownership, so legacy
	// files hydrate read-only instead of being taken over implicitly.
	return false
}
