package tools

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/tekierz/dotfiles/internal/pkg"
	"github.com/tekierz/dotfiles/internal/safefile"
)

// LazyGitConfig holds LazyGit configuration settings
type LazyGitConfig struct {
	SideBySide bool
	MouseMode  bool
	Theme      string // "auto", "dark", "light"
	Paging     string // "delta", "diff-so-fancy", "never"
}

// LazyGitTool represents LazyGit TUI for Git
type LazyGitTool struct {
	BaseTool
}

// NewLazyGitTool creates a new LazyGit tool
func NewLazyGitTool() *LazyGitTool {
	home, _ := os.UserHomeDir()
	return &LazyGitTool{
		BaseTool: BaseTool{
			id:          "lazygit",
			name:        "LazyGit",
			description: "Simple terminal UI for Git commands",
			icon:        "󰊢",
			category:    CategoryGit,
			packages: map[pkg.Platform][]string{
				pkg.PlatformMacOS: {"lazygit"},
				pkg.PlatformArch:  {"lazygit"},
				// lazygit is not in stock Debian/Ubuntu repos; install via Go or
				// manually — omitting Debian entry prevents a guaranteed-failing apt.
			},
			configPaths: []string{
				filepath.Join(home, ".config", "lazygit", "config.yml"),
			},
			// UI metadata
			uiGroup:        UIGroupCLITools,
			configScreen:   28, // ScreenConfigLazyGit - has dedicated config screen
			defaultEnabled: true,
		},
	}
}

// GenerateLazyGitConfig builds the lazygit config.yml content
func GenerateLazyGitConfig(cfg LazyGitConfig, theme string) string {
	var sb strings.Builder

	// Header
	sb.WriteString("# Generated by dotfiles TUI\n")
	sb.WriteString(fmt.Sprintf("# Theme: %s\n\n", theme))

	// GUI settings
	sb.WriteString("gui:\n")
	if cfg.SideBySide {
		sb.WriteString("  sidePanelWidth: 0.3333\n")
	}
	sb.WriteString("  scrollHeight: 2\n")
	sb.WriteString("  scrollPastBottom: true\n")
	sb.WriteString("  mouseEvents: " + fmt.Sprintf("%t", cfg.MouseMode) + "\n")
	sb.WriteString("  skipDiscardChangeWarning: false\n")
	sb.WriteString("  skipStashWarning: false\n")
	sb.WriteString("  showFileTree: true\n")
	sb.WriteString("  showRandomTip: false\n")
	sb.WriteString("  showCommandLog: true\n")
	sb.WriteString("  showBottomLine: true\n")
	sb.WriteString("  nerdFontsVersion: \"3\"\n")
	sb.WriteString(lazygitThemeBlock(cfg.Theme))
	sb.WriteString("\n")

	// Git settings
	sb.WriteString("git:\n")
	sb.WriteString("  paging:\n")
	sb.WriteString("    colorArg: always\n")
	sb.WriteString(fmt.Sprintf("    pager: %s\n", lazygitPager(cfg.Paging)))
	sb.WriteString("  commit:\n")
	sb.WriteString("    signOff: false\n")
	sb.WriteString("  merging:\n")
	sb.WriteString("    manualCommit: false\n")
	sb.WriteString("    args: \"\"\n")
	sb.WriteString("  log:\n")
	sb.WriteString("    order: topo-order\n")
	sb.WriteString("    showGraph: always\n")
	sb.WriteString("  skipHookPrefix: WIP\n")
	sb.WriteString("  autoFetch: true\n")
	sb.WriteString("  autoRefresh: true\n")
	sb.WriteString("  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --\n\n")

	// OS settings
	sb.WriteString("os:\n")
	sb.WriteString("  editPreset: nvim\n\n")

	// Keybinding hints
	sb.WriteString("keybinding:\n")
	sb.WriteString("  universal:\n")
	sb.WriteString("    quit: q\n")
	sb.WriteString("    quit-alt1: <c-c>\n")
	sb.WriteString("    return: <esc>\n")
	sb.WriteString("    togglePanel: <tab>\n")
	sb.WriteString("    prevItem: <up>\n")
	sb.WriteString("    nextItem: <down>\n")
	sb.WriteString("    prevPage: <pgup>\n")
	sb.WriteString("    nextPage: <pgdown>\n")
	sb.WriteString("    scrollLeft: <left>\n")
	sb.WriteString("    scrollRight: <right>\n")

	return sb.String()
}

// lazygitThemeBlock emits lazygit's gui.theme color block tuned for the chosen
// GUI theme. lazygit has no single "theme name" key (theming is per-color: see
// gui.theme.activeBorderColor / selectedLineBgColor / defaultFgColor in the
// lazygit Config docs), so the auto/dark/light selection maps onto concrete color
// choices:
//   - dark / auto: lazygit's standard palette (blue selected-line background).
//   - light: the lazygit-documented light-terminal palette — selectedLineBgColor
//     [reverse] (the blue background washes out on light terminals; reverse is the
//     recommended high-contrast alternative) and a dark default foreground.
//
// Each branch produces a DISTINCT, valid config block, so the GUI Theme control is
// a real applied setting rather than a silent no-op.
func lazygitThemeBlock(theme string) string {
	var sb strings.Builder
	sb.WriteString("  theme:\n")
	switch theme {
	case "light":
		sb.WriteString("    activeBorderColor:\n      - blue\n      - bold\n")
		sb.WriteString("    inactiveBorderColor:\n      - default\n")
		sb.WriteString("    selectedLineBgColor:\n      - reverse\n")
		sb.WriteString("    defaultFgColor:\n      - black\n")
	default: // "dark" and "auto" share lazygit's standard dark-friendly palette
		sb.WriteString("    activeBorderColor:\n      - green\n      - bold\n")
		sb.WriteString("    inactiveBorderColor:\n      - default\n")
		sb.WriteString("    selectedLineBgColor:\n      - blue\n")
		sb.WriteString("    defaultFgColor:\n      - default\n")
	}
	return sb.String()
}

// lazygitPager maps the Manage UI's paging vocabulary onto the pager command
// lazygit's git.paging.pager expects. "never" disables the external pager by
// routing through cat; anything unrecognized falls back to delta.
func lazygitPager(paging string) string {
	switch paging {
	case "diff-so-fancy":
		return "diff-so-fancy"
	case "never":
		return "cat"
	default:
		return "delta --dark --paging=never"
	}
}

// WriteLazyGitConfig writes the lazygit config to disk
func WriteLazyGitConfig(cfg LazyGitConfig, theme string) error {
	_, err := WriteLazyGitConfigTracked(cfg, theme)
	return err
}

// WriteLazyGitConfigTracked writes the lazygit config and returns the exact
// committed revision for rollback evidence.
func WriteLazyGitConfigTracked(cfg LazyGitConfig, theme string) (MutationEvidence, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return MutationEvidence{}, fmt.Errorf("failed to get home directory: %w", err)
	}

	configPath := filepath.Join(home, ".config", "lazygit", "config.yml")
	content := GenerateLazyGitConfig(cfg, theme)
	return writeToolConfigTracked(configPath, []byte(content))
}

// WriteLazyGitConfigAtRevisionTracked applies a plan-accepted LazyGit revision.
func WriteLazyGitConfigAtRevisionTracked(cfg LazyGitConfig, theme string, accepted safefile.Revision) (MutationEvidence, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return MutationEvidence{}, fmt.Errorf("failed to get home directory: %w", err)
	}
	configPath := filepath.Join(home, ".config", "lazygit", "config.yml")
	return writeToolConfigAtRevisionTracked(configPath, []byte(GenerateLazyGitConfig(cfg, theme)), accepted)
}
