package tools

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/tekierz/dotfiles/internal/operation"
	"github.com/tekierz/dotfiles/internal/safefile"
)

type neovimOverlayAuthority struct {
	initPath, optionsPath         string
	initRevision, optionsRevision safefile.Revision
	initParents, optionsParents   *safefile.ParentChain
}

func seedNeovimOverlayAuthority(t *testing.T, init, options []byte, createOptionsParent bool) neovimOverlayAuthority {
	t.Helper()
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("XDG_CONFIG_HOME", "")
	initPath := filepath.Join(home, ".config", "nvim", "init.lua")
	optionsPath := filepath.Join(home, ".config", "nvim", "lua", "custom", "options.lua")
	if err := os.MkdirAll(filepath.Dir(initPath), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(initPath, init, 0o600); err != nil {
		t.Fatal(err)
	}
	if createOptionsParent {
		if err := os.MkdirAll(filepath.Dir(optionsPath), 0o700); err != nil {
			t.Fatal(err)
		}
	}
	if options != nil {
		if err := os.WriteFile(optionsPath, options, 0o600); err != nil {
			t.Fatal(err)
		}
	}
	_, initRevision, initParents, err := safefile.ObserveFileWithin(home, ".config/nvim/init.lua")
	if err != nil {
		t.Fatal(err)
	}
	_, optionsRevision, optionsParents, err := safefile.ObserveFileWithin(home, ".config/nvim/lua/custom/options.lua")
	if err != nil {
		t.Fatal(err)
	}
	return neovimOverlayAuthority{initPath, optionsPath, initRevision, optionsRevision, initParents, optionsParents}
}

func noopCountingLocker(acquires, releases *int) operation.Locker {
	return func(string, string) (func() error, error) {
		*acquires++
		return func() error {
			*releases++
			return nil
		}, nil
	}
}

func TestNeovimReviewedOverlayWritesExactTwoFileEvidence(t *testing.T) {
	authority := seedNeovimOverlayAuthority(t, []byte("-- user init\n"), nil, true)
	acquires, releases := 0, 0
	evidence, err := WriteNeovimUserPrefsAtBoundAuthoritiesTracked(
		NeovimConfig{TabWidth: 8, LineNumbers: "relative", ExpandTab: true}, "dracula",
		authority.initRevision, authority.initParents, authority.optionsRevision, authority.optionsParents,
		noopCountingLocker(&acquires, &releases),
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(evidence) != 2 || evidence[0].Path != authority.optionsPath || evidence[1].Path != authority.initPath || acquires != 1 || releases != 1 {
		t.Fatalf("evidence=%+v acquires=%d releases=%d", evidence, acquires, releases)
	}
	initContent, _ := os.ReadFile(authority.initPath)
	if !bytes.HasPrefix(initContent, []byte("-- user init\n")) || bytes.Count(initContent, []byte(neovimManagedStart)) != 1 || bytes.Count(initContent, []byte(neovimRequireLine)) != 1 {
		t.Fatalf("reviewed init content:\n%s", initContent)
	}
	optionsContent, _ := os.ReadFile(authority.optionsPath)
	if !hasGeneratedConfigHeader(optionsContent) || !bytes.Contains(optionsContent, []byte("vim.opt.tabstop = 8")) {
		t.Fatalf("reviewed options content:\n%s", optionsContent)
	}
}

func TestMergeNeovimInitFragmentMigratesOnlyExactLegacyAppend(t *testing.T) {
	original := append([]byte("-- user prefix\n"), neovimLegacyAppend...)
	original = append(original, []byte("-- later user tail\n")...)
	merged, err := mergeNeovimInitFragment(original)
	if err != nil {
		t.Fatal(err)
	}
	if bytes.Contains(merged, neovimLegacyAppend) || !bytes.Contains(merged, []byte("-- later user tail\n")) || bytes.Count(merged, []byte(neovimManagedStart)) != 1 {
		t.Fatalf("legacy migration changed the wrong bytes:\n%s", merged)
	}
	arbitrary := []byte("-- pcall(require, \"custom.options\") is documented here\n")
	merged, err = mergeNeovimInitFragment(arbitrary)
	if err != nil || !bytes.HasPrefix(merged, arbitrary) || bytes.Count(merged, []byte(neovimRequireLine)) != 2 {
		t.Fatalf("arbitrary user require was removed: err=%v\n%s", err, merged)
	}
}

func TestMergeNeovimInitFragmentRejectsAmbiguousOwnership(t *testing.T) {
	canonical := wrapManagedConfigSection(neovimManagedStart, neovimManagedEnd, neovimRequireLine)
	for _, content := range [][]byte{
		[]byte(neovimManagedStart + "\n"),
		append(append([]byte("-- init"), neovimLegacyAppend...), neovimLegacyAppend...),
		append(append([]byte(nil), canonical...), neovimLegacyAppend...),
	} {
		if _, err := mergeNeovimInitFragment(content); err == nil {
			t.Fatalf("ambiguous init accepted:\n%s", content)
		}
	}
}

func TestNeovimReviewedOverlayRejectsStaleOptionsBeforeInitMutation(t *testing.T) {
	init := []byte("-- user init\n")
	managed := []byte(GenerateNeovimConfig(NeovimConfig{TabWidth: 4}, "dracula"))
	authority := seedNeovimOverlayAuthority(t, init, managed, true)
	external := []byte("-- Generated by dotfiles TUI\n-- external replacement\n")
	if err := os.WriteFile(authority.optionsPath, external, 0o600); err != nil {
		t.Fatal(err)
	}
	_, err := WriteNeovimUserPrefsAtBoundAuthoritiesTracked(NeovimConfig{TabWidth: 8}, "dracula", authority.initRevision, authority.initParents, authority.optionsRevision, authority.optionsParents, noopCountingLocker(new(int), new(int)))
	if !errors.Is(err, safefile.ErrRevisionChanged) {
		t.Fatalf("error=%v, want ErrRevisionChanged", err)
	}
	if got, _ := os.ReadFile(authority.initPath); !bytes.Equal(got, init) {
		t.Fatalf("stale options changed init.lua: %q", got)
	}
	if got, _ := os.ReadFile(authority.optionsPath); !bytes.Equal(got, external) {
		t.Fatalf("stale options replacement overwritten: %q", got)
	}
}

func TestNeovimReviewedOverlayRejectsReplacedOptionsParentBeforeMutation(t *testing.T) {
	init := []byte("-- user init\n")
	managed := []byte(GenerateNeovimConfig(NeovimConfig{TabWidth: 4}, "dracula"))
	authority := seedNeovimOverlayAuthority(t, init, managed, true)
	replaceDirectoryWithIdenticalNewIdentity(t, filepath.Dir(authority.optionsPath))
	_, err := WriteNeovimUserPrefsAtBoundAuthoritiesTracked(NeovimConfig{TabWidth: 8}, "dracula", authority.initRevision, authority.initParents, authority.optionsRevision, authority.optionsParents, noopCountingLocker(new(int), new(int)))
	if !errors.Is(err, safefile.ErrParentChanged) {
		t.Fatalf("error=%v, want ErrParentChanged", err)
	}
	if got, _ := os.ReadFile(authority.initPath); !bytes.Equal(got, init) {
		t.Fatalf("replaced options parent changed init.lua: %q", got)
	}
}

func TestNeovimReviewedOverlayRefusesUnmanagedOptionsBeforeMutation(t *testing.T) {
	init := []byte("-- user init\n")
	authority := seedNeovimOverlayAuthority(t, init, []byte("vim.opt.wrap = true\n"), true)
	_, err := WriteNeovimUserPrefsAtBoundAuthoritiesTracked(NeovimConfig{}, "dracula", authority.initRevision, authority.initParents, authority.optionsRevision, authority.optionsParents, noopCountingLocker(new(int), new(int)))
	if !errors.Is(err, ErrUnmanagedConfig) {
		t.Fatalf("error=%v, want ErrUnmanagedConfig", err)
	}
	got, _ := os.ReadFile(authority.initPath)
	if !bytes.Equal(got, init) {
		t.Fatalf("refused overlay changed init.lua: %q", got)
	}
}

func TestNeovimReviewedOverlaySecondWriteFailureReturnsOptionsEvidence(t *testing.T) {
	authority := seedNeovimOverlayAuthority(t, []byte("-- user init\n"), nil, true)
	actual := neovimAuthorizedReplace(safefile.ReplaceWithinRevisionNoCreateAuthorizedTracked)
	failure := errors.New("injected init replacement failure")
	calls := 0
	replace := func(root, rel string, accepted safefile.Revision, parents *safefile.ParentChain, content []byte, mode os.FileMode) (safefile.Revision, error) {
		calls++
		if calls == 2 {
			return safefile.Revision{}, failure
		}
		return actual(root, rel, accepted, parents, content, mode)
	}
	_, err := writeNeovimUserPrefsAtBoundAuthoritiesTracked(NeovimConfig{TabWidth: 2}, "dracula", authority.initRevision, authority.initParents, authority.optionsRevision, authority.optionsParents, noopCountingLocker(new(int), new(int)), replace)
	var partial *PartialMutationError
	if !errors.Is(err, failure) || !errors.As(err, &partial) || len(partial.Evidence) != 1 || partial.Evidence[0].Path != authority.optionsPath {
		t.Fatalf("error=%v partial=%+v", err, partial)
	}
	initContent, _ := os.ReadFile(authority.initPath)
	if strings.Contains(string(initContent), neovimManagedStart) {
		t.Fatalf("failed init replacement changed init.lua:\n%s", initContent)
	}
}

func TestNeovimReviewedOverlayCommittedInitFailureReturnsBothEvidence(t *testing.T) {
	authority := seedNeovimOverlayAuthority(t, []byte("-- user init\n"), nil, true)
	actual := neovimAuthorizedReplace(safefile.ReplaceWithinRevisionNoCreateAuthorizedTracked)
	failure := errors.New("injected init postcommit failure")
	calls := 0
	replace := func(root, rel string, accepted safefile.Revision, parents *safefile.ParentChain, content []byte, mode os.FileMode) (safefile.Revision, error) {
		calls++
		revision, err := actual(root, rel, accepted, parents, content, mode)
		if err == nil && calls == 2 {
			return revision, &safefile.CommittedError{Operation: "injected init validation", Err: failure}
		}
		return revision, err
	}
	_, err := writeNeovimUserPrefsAtBoundAuthoritiesTracked(NeovimConfig{TabWidth: 2}, "dracula", authority.initRevision, authority.initParents, authority.optionsRevision, authority.optionsParents, noopCountingLocker(new(int), new(int)), replace)
	var partial *PartialMutationError
	if !errors.Is(err, failure) || !errors.As(err, &partial) || len(partial.Evidence) != 2 {
		t.Fatalf("error=%v partial=%+v", err, partial)
	}
}

func TestNeovimReviewedOverlayUnprovenCommittedInitFailurePreservesOptionsEvidence(t *testing.T) {
	authority := seedNeovimOverlayAuthority(t, []byte("-- user init\n"), nil, true)
	actual := neovimAuthorizedReplace(safefile.ReplaceWithinRevisionNoCreateAuthorizedTracked)
	failure := &safefile.CommittedError{Operation: "injected unknown init commit", Err: errors.New("revision lost")}
	calls := 0
	replace := func(root, rel string, accepted safefile.Revision, parents *safefile.ParentChain, content []byte, mode os.FileMode) (safefile.Revision, error) {
		calls++
		if calls == 2 {
			return safefile.Revision{}, failure
		}
		return actual(root, rel, accepted, parents, content, mode)
	}
	_, err := writeNeovimUserPrefsAtBoundAuthoritiesTracked(NeovimConfig{}, "dracula", authority.initRevision, authority.initParents, authority.optionsRevision, authority.optionsParents, noopCountingLocker(new(int), new(int)), replace)
	var partial *PartialMutationError
	var committed interface{ Committed() bool }
	if !errors.As(err, &committed) || !committed.Committed() || !errors.As(err, &partial) || len(partial.Evidence) != 1 || partial.Evidence[0].Path != authority.optionsPath {
		t.Fatalf("error=%T %v partial=%+v", err, err, partial)
	}
}

func TestNeovimReviewedOverlayNoopReturnsCompleteEvidenceWithoutReplace(t *testing.T) {
	cfg := NeovimConfig{TabWidth: 4, LineNumbers: "relative"}
	init := wrapManagedConfigSection(neovimManagedStart, neovimManagedEnd, neovimRequireLine)
	options := []byte(GenerateNeovimConfig(cfg, "dracula"))
	authority := seedNeovimOverlayAuthority(t, init, options, true)
	replaceCalls := 0
	replace := func(string, string, safefile.Revision, *safefile.ParentChain, []byte, os.FileMode) (safefile.Revision, error) {
		replaceCalls++
		return safefile.Revision{}, errors.New("unexpected replacement")
	}
	evidence, err := writeNeovimUserPrefsAtBoundAuthoritiesTracked(cfg, "dracula", authority.initRevision, authority.initParents, authority.optionsRevision, authority.optionsParents, noopCountingLocker(new(int), new(int)), replace)
	if err != nil || replaceCalls != 0 || len(evidence) != 2 || evidence[0].Revision != authority.optionsRevision || evidence[1].Revision != authority.initRevision {
		t.Fatalf("evidence=%+v replaceCalls=%d err=%v", evidence, replaceCalls, err)
	}
}

func TestNeovimReviewedOverlayReleaseFailureReturnsAllCommittedEvidence(t *testing.T) {
	authority := seedNeovimOverlayAuthority(t, []byte("-- user init\n"), nil, true)
	releaseErr := errors.New("injected overlay unlock failure")
	locker := func(string, string) (func() error, error) { return func() error { return releaseErr }, nil }
	evidence, err := WriteNeovimUserPrefsAtBoundAuthoritiesTracked(NeovimConfig{}, "dracula", authority.initRevision, authority.initParents, authority.optionsRevision, authority.optionsParents, locker)
	var partial *PartialMutationError
	if evidence != nil || !errors.Is(err, releaseErr) || !errors.As(err, &partial) || len(partial.Evidence) != 2 {
		t.Fatalf("evidence=%+v error=%v partial=%+v", evidence, err, partial)
	}
}

func TestNeovimReviewedOverlayUsesLegacyToolConfigLockProtocol(t *testing.T) {
	authority := seedNeovimOverlayAuthority(t, []byte("-- user init\n"), nil, true)
	release, err := operation.DefaultLocker("tool-config", authority.initPath)
	if err != nil {
		t.Fatal(err)
	}
	done := make(chan error, 1)
	go func() {
		_, err := WriteNeovimUserPrefsAtBoundAuthoritiesTracked(NeovimConfig{}, "dracula", authority.initRevision, authority.initParents, authority.optionsRevision, authority.optionsParents, operation.DefaultLocker)
		done <- err
	}()
	select {
	case err := <-done:
		t.Fatalf("reviewed overlay did not wait for legacy lock: %v", err)
	case <-time.After(100 * time.Millisecond):
	}
	if err := release(); err != nil {
		t.Fatal(err)
	}
	if err := <-done; err != nil {
		t.Fatal(err)
	}
}
