package tools

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/tekierz/dotfiles/internal/pkg"
)

// NeovimConfig holds Neovim configuration settings.
type NeovimConfig struct {
	ConfigPreset string   // "kickstart", "lazyvim", "custom", "minimal"
	LSPs         []string // LSP servers to configure
	Plugins      []string // Plugins to enable
	TabWidth     int
	Wrap         bool
	CursorLine   bool
	Clipboard    string // "unnamedplus", "unnamed", "none"

	// LineNumbers is the SINGLE control for the line-number gutter:
	//   "absolute" -> number=true,  relativenumber=false
	//   "relative" -> number=true,  relativenumber=true
	//   "none"     -> number=false, relativenumber=false
	LineNumbers string
	ExpandTab   bool // use spaces instead of tabs
	UndoFile    bool // persistent undo on disk
}

// NeovimTool represents the Neovim editor.
type NeovimTool struct {
	BaseTool
}

// NewNeovimTool creates a new Neovim tool.
func NewNeovimTool() *NeovimTool {
	home, _ := os.UserHomeDir()
	return &NeovimTool{
		BaseTool: BaseTool{
			id:          "neovim",
			name:        "Neovim",
			description: "Hyperextensible Vim-based text editor",
			icon:        "",
			category:    CategoryEditor,
			packages: map[pkg.Platform][]string{
				pkg.PlatformMacOS:  {"neovim"},
				pkg.PlatformArch:   {"neovim"},
				pkg.PlatformDebian: {"neovim"},
			},
			configPaths: []string{
				filepath.Join(home, ".config", "nvim", "init.lua"),
			},
			// UI metadata
			uiGroup:        UIGroupNone,
			configScreen:   12, // ScreenConfigNeovim
			defaultEnabled: true,
		},
	}
}

// neovimConfigRepos maps preset names to their git repositories.
// Every preset listed here is cloned into ~/.config/nvim via setupNeovimPreset.
// The "custom" preset is intentionally absent — it is non-destructive and
// preserves whatever config the user already has.
var neovimConfigRepos = map[string]string{
	"kickstart": "https://github.com/nvim-lua/kickstart.nvim.git",
	"lazyvim":   "https://github.com/LazyVim/starter.git",
	"nvchad":    "https://github.com/NvChad/starter.git",
}

// ValidNeovimPresetOrder is the authoritative ordered list of preset identifiers
// in the order the config screen displays them.  screen_config_neovim.go MUST
// consume this slice for its option list — that is the compile-time guarantee
// that UI options and generator dispatch cannot drift independently.
var ValidNeovimPresetOrder = []string{"kickstart", "lazyvim", "nvchad", "custom"}

// ValidNeovimPresets is derived from ValidNeovimPresetOrder and provides O(1)
// membership checks.  Do not edit this directly; edit ValidNeovimPresetOrder.
var ValidNeovimPresets = func() map[string]struct{} {
	m := make(map[string]struct{}, len(ValidNeovimPresetOrder))
	for _, p := range ValidNeovimPresetOrder {
		m[p] = struct{}{}
	}
	return m
}()

// GenerateNeovimConfig builds basic neovim settings as a Lua string.
// For preset configs (kickstart, lazyvim), this generates a user preferences file.
func GenerateNeovimConfig(cfg NeovimConfig, theme string) string {
	var sb strings.Builder

	// Header
	sb.WriteString("-- Generated by dotfiles TUI\n")
	sb.WriteString(fmt.Sprintf("-- Theme: %s\n\n", theme))

	// Basic settings
	sb.WriteString("-- Basic settings\n")
	// LineNumbers is the single source for both opts: "absolute"/"relative" show
	// the number column ("none" hides it); only "relative" enables relative numbers.
	sb.WriteString(fmt.Sprintf("vim.opt.number = %t\n", cfg.LineNumbers != "none"))
	sb.WriteString(fmt.Sprintf("vim.opt.relativenumber = %t\n", cfg.LineNumbers == "relative"))
	sb.WriteString(fmt.Sprintf("vim.opt.tabstop = %d\n", cfg.TabWidth))
	sb.WriteString(fmt.Sprintf("vim.opt.shiftwidth = %d\n", cfg.TabWidth))
	sb.WriteString(fmt.Sprintf("vim.opt.expandtab = %t\n", cfg.ExpandTab))
	sb.WriteString(fmt.Sprintf("vim.opt.wrap = %t\n", cfg.Wrap))
	sb.WriteString(fmt.Sprintf("vim.opt.cursorline = %t\n", cfg.CursorLine))
	sb.WriteString(fmt.Sprintf("vim.opt.undofile = %t\n", cfg.UndoFile))
	sb.WriteString("\n")

	// Clipboard
	sb.WriteString("-- Clipboard\n")
	if cfg.Clipboard != "none" {
		sb.WriteString(fmt.Sprintf("vim.opt.clipboard = \"%s\"\n", cfg.Clipboard))
	}
	sb.WriteString("\n")

	// Search settings
	sb.WriteString("-- Search\n")
	sb.WriteString("vim.opt.ignorecase = true\n")
	sb.WriteString("vim.opt.smartcase = true\n")
	sb.WriteString("vim.opt.hlsearch = true\n")
	sb.WriteString("vim.opt.incsearch = true\n\n")

	// UI settings
	sb.WriteString("-- UI\n")
	sb.WriteString("vim.opt.termguicolors = true\n")
	sb.WriteString("vim.opt.signcolumn = \"yes\"\n")
	sb.WriteString("vim.opt.scrolloff = 8\n")
	sb.WriteString("vim.opt.sidescrolloff = 8\n\n")

	// Performance
	sb.WriteString("-- Performance\n")
	sb.WriteString("vim.opt.updatetime = 250\n")
	sb.WriteString("vim.opt.timeoutlen = 300\n\n")

	// Leader key
	sb.WriteString("-- Leader\n")
	sb.WriteString("vim.g.mapleader = \" \"\n")
	sb.WriteString("vim.g.maplocalleader = \" \"\n")

	return sb.String()
}

// WriteNeovimConfig writes the neovim configuration to disk.
func WriteNeovimConfig(cfg NeovimConfig, theme string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}

	nvimDir := filepath.Join(home, ".config", "nvim")

	// Handle preset configurations.  Every case here must correspond to an entry
	// in ValidNeovimPresets; adding a new preset requires updating both.
	switch cfg.ConfigPreset {
	case "kickstart", "lazyvim", "nvchad":
		return setupNeovimPreset(cfg, theme, nvimDir)
	case "custom":
		// "custom" means "leave the user's existing config alone".  Do not write
		// anything — the user manages their own ~/.config/nvim.
		return nil
	default:
		// Unknown preset: fall back to a minimal standalone config rather than
		// silently succeeding.  This branch should not be reachable from the UI
		// because neovimAdjust only sets values from ValidNeovimPresets.
		return writeMinimalNeovimConfig(cfg, theme, nvimDir)
	}
}

// setupNeovimPreset clones a preset config and adds user customizations.
func setupNeovimPreset(cfg NeovimConfig, theme, nvimDir string) error {
	repoURL, ok := neovimConfigRepos[cfg.ConfigPreset]
	if !ok {
		return writeMinimalNeovimConfig(cfg, theme, nvimDir)
	}

	// Check if config already exists
	initFile := filepath.Join(nvimDir, "init.lua")
	if _, err := os.Stat(initFile); err == nil {
		// Config exists, just update user preferences
		return writeNeovimUserPrefs(cfg, theme, nvimDir)
	}

	// Backup existing config if present
	if _, err := os.Stat(nvimDir); err == nil {
		backupDir := nvimDir + ".backup"
		_ = os.RemoveAll(backupDir)
		_ = os.Rename(nvimDir, backupDir)
	}

	// Clone the preset
	cmd := exec.Command("git", "clone", "--depth", "1", repoURL, nvimDir)
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("failed to clone %s config: %w", cfg.ConfigPreset, err)
	}

	// Remove .git directory to make it user-owned
	gitDir := filepath.Join(nvimDir, ".git")
	_ = os.RemoveAll(gitDir)

	// Write user preferences
	return writeNeovimUserPrefs(cfg, theme, nvimDir)
}

// WriteNeovimUserPrefs writes ONLY the user-preferences overlay
// (lua/custom/options.lua, plus a require appended to init.lua if present) into
// the existing ~/.config/nvim. It is the PURE, non-destructive counterpart of
// WriteNeovimConfig used by the config-apply path: it never clones a preset and
// never moves/removes ~/.config/nvim, so saving Neovim settings (Manage save or
// `dotfiles config neovim`) cannot do a network install or clobber the user's
// config. Preset cloning stays at install time only (installation.go).
//
// If ~/.config/nvim does not exist yet (Neovim not installed / no preset cloned),
// this is a deliberate no-op: there is no base config to overlay, and writing a
// bare options.lua there would be meaningless without the preset's init.lua. The
// preset clone at install time is what creates the directory; this writer only
// updates an existing one.
func WriteNeovimUserPrefs(cfg NeovimConfig, theme string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}
	nvimDir := filepath.Join(home, ".config", "nvim")

	// No existing config dir => nothing to overlay. Do NOT create it (that is the
	// install-time preset clone's job) and do NOT clone here.
	if _, statErr := os.Stat(nvimDir); statErr != nil {
		return nil
	}

	return writeNeovimUserPrefs(cfg, theme, nvimDir)
}

// writeNeovimUserPrefs writes user preferences to a separate file.
func writeNeovimUserPrefs(cfg NeovimConfig, theme, nvimDir string) error {
	prefsPath := filepath.Join(nvimDir, "lua", "custom", "options.lua")
	content := GenerateNeovimConfig(cfg, theme)
	if err := writeToolConfig(prefsPath, []byte(content)); err != nil {
		return err
	}

	// Add require to init.lua if not already present
	initPath := filepath.Join(nvimDir, "init.lua")
	initContent, err := os.ReadFile(initPath)
	if err == nil {
		requireLine := "pcall(require, \"custom.options\")"
		if !strings.Contains(string(initContent), requireLine) {
			// Append at the end
			newContent := string(initContent) + "\n\n-- User options from dotfiles\n" + requireLine + "\n"
			_ = os.WriteFile(initPath, []byte(newContent), 0600)
		}
	}

	return nil
}

// writeMinimalNeovimConfig writes a minimal standalone neovim config.
func writeMinimalNeovimConfig(cfg NeovimConfig, theme, nvimDir string) error {
	initPath := filepath.Join(nvimDir, "init.lua")
	content := GenerateNeovimConfig(cfg, theme)
	return writeToolConfig(initPath, []byte(content))
}
