package tools

import (
	"os"
	"path/filepath"
	"testing"
)

func TestImportTmuxConfigReadsLiteralSettingsWithProvenance(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("XDG_CONFIG_HOME", "")
	path := filepath.Join(home, ".tmux.conf")
	content := `# native tmux
set -g prefix C-b
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
set -g mouse off
set -g base-index 0
setw -g pane-base-index 0
set -g status-position top
setw -g pane-border-lines double
set -g history-limit 12345
set -sg escape-time 25
setw -g aggressive-resize off
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-save-interval '45'
set -g @continuum-restore 'off'
run '~/.tmux/plugins/tpm/tpm'
`
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
	got, err := ImportTmuxConfig()
	if err != nil {
		t.Fatal(err)
	}
	if len(got.Warnings) != 0 {
		t.Fatalf("unexpected warnings: %v", got.Warnings)
	}
	if got.Config.Prefix != "ctrl-b" || got.Config.SplitBinds != "pipes" || got.Config.MouseMode || got.Config.BaseIndex != 0 || got.Config.StatusBar != "top" || got.Config.PaneBorderStyle != "double" || got.Config.HistoryLimit != 12345 || got.Config.EscapeTime != 25 || got.Config.AggressiveResize || !got.Config.TPMEnabled || !got.Config.PluginContinuum || got.Config.ContinuumSaveMin != 45 || got.Config.ContinuumRestore {
		t.Fatalf("imported tmux config = %+v", got.Config)
	}
	if source := got.Fields[TmuxFieldPrefix]; source.Path != path || source.Line != 2 || source.Key != "prefix" || source.Scope != ConfigValueNative {
		t.Fatalf("prefix provenance = %+v", source)
	}
	if len(got.Sources) != 2 || !got.Sources[0].Active || got.Sources[1].Active {
		t.Fatalf("tmux sources = %+v", got.Sources)
	}
}

func TestImportTmuxConfigRespectsManagedAndTrailingNativePrecedence(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("XDG_CONFIG_HOME", "")
	path := filepath.Join(home, ".tmux.conf")
	content := "set -g prefix C-a\n" + tmuxManagedStart + "\n# Generated by dotfiles TUI\nset -g prefix C-b\nset -g base-index 1\nsetw -g pane-base-index 1\n" + tmuxManagedEnd + "\nset -g prefix C-Space\n"
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
	got, err := ImportTmuxConfig()
	if err != nil {
		t.Fatal(err)
	}
	if len(got.Warnings) != 0 {
		t.Fatalf("unexpected warnings: %v", got.Warnings)
	}
	if got.Config.Prefix != "ctrl-space" || got.Fields[TmuxFieldPrefix].Scope != ConfigValueNative || got.Fields[TmuxFieldPrefix].Line != 8 {
		t.Fatalf("trailing native precedence not reflected: config=%+v source=%+v", got.Config, got.Fields[TmuxFieldPrefix])
	}
	if !got.Sources[0].Managed {
		t.Fatalf("managed source not identified: %+v", got.Sources)
	}
}

func TestImportTmuxConfigFailsClosedOnDynamicOrAmbiguousSyntax(t *testing.T) {
	for name, content := range map[string]string{
		"source":      "set -g prefix C-a\nsource-file ~/.tmux-extra.conf\n",
		"conditional": "%if #{==:#{host},work}\nset -g mouse off\n%endif\n",
		"targeted":    "set -t work prefix C-a\n",
		"append":      "set -ag prefix C-a\n",
		"mismatch":    "set -g base-index 1\nsetw -g pane-base-index 0\n",
		"markers":     tmuxManagedStart + "\nset -g prefix C-a\n",
		"split":       "bind | split-window -h\n",
	} {
		t.Run(name, func(t *testing.T) {
			got := parseTmuxConfigImport("/home/test/.tmux.conf", []byte(content))
			if len(got.Warnings) == 0 {
				t.Fatalf("unsafe syntax was accepted: %+v", got)
			}
		})
	}
}

func TestImportTmuxConfigUsesActiveXDGSourceWithoutCreatingParents(t *testing.T) {
	home := t.TempDir()
	xdg := filepath.Join(home, "xdg")
	t.Setenv("HOME", home)
	t.Setenv("XDG_CONFIG_HOME", xdg)
	xdgPath := filepath.Join(xdg, "tmux", "tmux.conf")
	if err := os.MkdirAll(filepath.Dir(xdgPath), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(xdgPath, []byte("set -g prefix C-b\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	got, err := ImportTmuxConfig()
	if err != nil {
		t.Fatal(err)
	}
	if len(got.Sources) != 3 || got.Sources[0].Active || !got.Sources[1].Active || got.Sources[2].Active {
		t.Fatalf("XDG source chain = %+v", got.Sources)
	}
	if got.Config.Prefix != "ctrl-b" {
		t.Fatalf("XDG prefix = %q", got.Config.Prefix)
	}

	emptyHome := t.TempDir()
	emptyXDG := filepath.Join(emptyHome, "missing-xdg")
	t.Setenv("HOME", emptyHome)
	t.Setenv("XDG_CONFIG_HOME", emptyXDG)
	missing, err := ImportTmuxConfig()
	if err != nil {
		t.Fatal(err)
	}
	if len(missing.Fields) != 0 {
		t.Fatalf("missing import returned fields: %+v", missing.Fields)
	}
	if _, err := os.Lstat(emptyXDG); !os.IsNotExist(err) {
		t.Fatalf("read-only import created XDG parent: %v", err)
	}
}
