package tools

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/tekierz/dotfiles/internal/pkg"
)

// TmuxTool represents tmux terminal multiplexer
type TmuxTool struct {
	BaseTool
}

// TmuxConfig holds tmux configuration settings
type TmuxConfig struct {
	// Basic settings
	Prefix     string
	SplitBinds string
	StatusBar  string
	MouseMode  bool

	BaseIndex        int    // Starting index for windows/panes
	PaneBorderStyle  string // "single", "double", "heavy", "simple"
	HistoryLimit     int    // Scrollback buffer size
	EscapeTime       int    // Escape key delay in ms
	AggressiveResize bool   // Aggressively resize panes on window changes

	// TPM settings
	TPMEnabled       bool
	PluginSensible   bool
	PluginResurrect  bool
	PluginContinuum  bool
	PluginYank       bool
	ContinuumSaveMin int
	ContinuumRestore bool // Restore sessions on tmux start
}

// NewTmuxTool creates a new Tmux tool
func NewTmuxTool() *TmuxTool {
	home, _ := os.UserHomeDir()
	return &TmuxTool{
		BaseTool: BaseTool{
			id:          "tmux",
			name:        "Tmux",
			description: "Terminal multiplexer",
			icon:        "",
			category:    CategoryTerminal,
			packages: map[pkg.Platform][]string{
				pkg.PlatformMacOS:  {"tmux"},
				pkg.PlatformArch:   {"tmux"},
				pkg.PlatformDebian: {"tmux"},
			},
			configPaths: []string{
				filepath.Join(home, ".tmux.conf"),
			},
			// UI metadata
			uiGroup:        UIGroupNone,
			configScreen:   10, // ScreenConfigTmux
			defaultEnabled: true,
		},
	}
}

// TPMPath returns the TPM installation directory
func TPMPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".tmux", "plugins", "tpm")
}

// IsTPMInstalled checks if TPM is installed
func IsTPMInstalled() bool {
	_, err := os.Stat(TPMPath())
	return err == nil
}

// InstallTPM clones TPM repository
func InstallTPM() error {
	tpmPath := TPMPath()

	// Create parent directory
	pluginsDir := filepath.Dir(tpmPath)
	if err := os.MkdirAll(pluginsDir, 0700); err != nil {
		return fmt.Errorf("failed to create plugins directory: %w", err)
	}

	// Clone TPM
	cmd := exec.Command("git", "clone", "--depth", "1",
		"https://github.com/tmux-plugins/tpm",
		tpmPath)

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("failed to clone TPM: %w", err)
	}

	return nil
}

// RunTPMInstall triggers TPM to install plugins
func RunTPMInstall() error {
	installScript := filepath.Join(TPMPath(), "scripts", "install_plugins.sh")

	if _, err := os.Stat(installScript); err != nil {
		return fmt.Errorf("TPM install script not found: %w", err)
	}

	cmd := exec.Command(installScript)
	return cmd.Run()
}

// GenerateTmuxConfig builds the tmux.conf content
func GenerateTmuxConfig(cfg TmuxConfig, theme string) string {
	var sb strings.Builder

	// Header
	sb.WriteString("# Generated by dotfiles TUI\n")
	sb.WriteString(fmt.Sprintf("# Theme: %s\n\n", theme))

	// Terminal settings
	sb.WriteString("# Terminal settings\n")
	sb.WriteString("set -g default-terminal \"tmux-256color\"\n")
	sb.WriteString("set -ga terminal-overrides \",xterm-256color:Tc\"\n\n")

	// Prefix key
	sb.WriteString("# Prefix key\n")
	prefix := prefixToTmuxFormat(cfg.Prefix)
	sb.WriteString(fmt.Sprintf("set -g prefix %s\n", prefix))
	sb.WriteString("unbind C-b\n")
	sb.WriteString(fmt.Sprintf("bind %s send-prefix\n\n", prefix))

	// Split bindings
	sb.WriteString("# Split panes\n")
	if cfg.SplitBinds == "pipes" {
		sb.WriteString("bind | split-window -h -c \"#{pane_current_path}\"\n")
		sb.WriteString("bind - split-window -v -c \"#{pane_current_path}\"\n")
		sb.WriteString("unbind '\"'\n")
		sb.WriteString("unbind %\n")
	} else {
		sb.WriteString("bind % split-window -h -c \"#{pane_current_path}\"\n")
		sb.WriteString("bind '\"' split-window -v -c \"#{pane_current_path}\"\n")
	}
	sb.WriteString("\n")

	// Mouse mode
	sb.WriteString("# Mouse\n")
	if cfg.MouseMode {
		sb.WriteString("set -g mouse on\n")
	} else {
		sb.WriteString("set -g mouse off\n")
	}
	sb.WriteString("\n")

	// Window settings
	sb.WriteString("# Window settings\n")
	sb.WriteString(fmt.Sprintf("set -g base-index %d\n", cfg.BaseIndex))
	sb.WriteString(fmt.Sprintf("setw -g pane-base-index %d\n", cfg.BaseIndex))
	sb.WriteString("set -g renumber-windows on\n")
	if cfg.AggressiveResize {
		sb.WriteString("setw -g aggressive-resize on\n")
	} else {
		sb.WriteString("setw -g aggressive-resize off\n")
	}
	sb.WriteString(fmt.Sprintf("set -g pane-border-lines %s\n\n", paneBorderToTmuxFormat(cfg.PaneBorderStyle)))

	// Status bar
	sb.WriteString("# Status bar\n")
	sb.WriteString(fmt.Sprintf("set -g status-position %s\n", cfg.StatusBar))
	sb.WriteString("set -g status-left-length 30\n")
	sb.WriteString("set -g status-right-length 50\n\n")

	// Performance
	sb.WriteString("# Performance\n")
	sb.WriteString(fmt.Sprintf("set -sg escape-time %d\n", cfg.EscapeTime))
	sb.WriteString(fmt.Sprintf("set -g history-limit %d\n\n", cfg.HistoryLimit))

	// Reload binding
	sb.WriteString("# Reload config\n")
	sb.WriteString("bind r source-file ~/.tmux.conf \\; display \"Config reloaded!\"\n\n")

	// Quick window switching
	sb.WriteString("# Quick window switching (Alt + number)\n")
	for i := 1; i <= 5; i++ {
		sb.WriteString(fmt.Sprintf("bind -n M-%d select-window -t %d\n", i, i))
	}
	sb.WriteString("\n")

	// Pane navigation
	sb.WriteString("# Pane navigation (Alt + arrow)\n")
	sb.WriteString("bind -n M-Left select-pane -L\n")
	sb.WriteString("bind -n M-Right select-pane -R\n")
	sb.WriteString("bind -n M-Up select-pane -U\n")
	sb.WriteString("bind -n M-Down select-pane -D\n\n")

	// TPM configuration
	if cfg.TPMEnabled {
		sb.WriteString("# TPM (Tmux Plugin Manager)\n")
		sb.WriteString("set -g @plugin 'tmux-plugins/tpm'\n")

		// Add enabled plugins
		if cfg.PluginSensible {
			sb.WriteString("set -g @plugin 'tmux-plugins/tmux-sensible'\n")
		}
		if cfg.PluginResurrect {
			sb.WriteString("set -g @plugin 'tmux-plugins/tmux-resurrect'\n")
		}
		if cfg.PluginContinuum {
			sb.WriteString("set -g @plugin 'tmux-plugins/tmux-continuum'\n")
		}
		if cfg.PluginYank {
			sb.WriteString("set -g @plugin 'tmux-plugins/tmux-yank'\n")
		}
		sb.WriteString("\n")

		// Plugin-specific settings
		if cfg.PluginContinuum {
			sb.WriteString("# Continuum settings\n")
			sb.WriteString(fmt.Sprintf("set -g @continuum-save-interval '%d'\n", cfg.ContinuumSaveMin))
			restore := "off"
			if cfg.ContinuumRestore {
				restore = "on"
			}
			sb.WriteString(fmt.Sprintf("set -g @continuum-restore '%s'\n\n", restore))
		}

		if cfg.PluginResurrect {
			sb.WriteString("# Resurrect settings\n")
			sb.WriteString("set -g @resurrect-capture-pane-contents 'on'\n")
			sb.WriteString("set -g @resurrect-strategy-nvim 'session'\n\n")
		}

		// TPM init (must be at the very end)
		sb.WriteString("# Initialize TPM (keep at bottom)\n")
		sb.WriteString("run '~/.tmux/plugins/tpm/tpm'\n")
	}

	return sb.String()
}

// prefixToTmuxFormat converts config format to tmux format
func prefixToTmuxFormat(prefix string) string {
	switch prefix {
	case "ctrl-a":
		return "C-a"
	case "ctrl-b":
		return "C-b"
	case "ctrl-space":
		return "C-Space"
	default:
		return "C-a"
	}
}

// paneBorderToTmuxFormat maps the Manage UI's pane-border vocabulary onto the
// values tmux's pane-border-lines option accepts. tmux supports
// single/double/heavy/simple/number; the UI offers the first four, so anything
// unrecognized falls back to "single".
func paneBorderToTmuxFormat(style string) string {
	switch style {
	case "single", "double", "heavy", "simple":
		return style
	default:
		return "single"
	}
}

// WriteTmuxConfig writes the tmux.conf file
func WriteTmuxConfig(cfg TmuxConfig, theme string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}

	configPath := filepath.Join(home, ".tmux.conf")
	content := GenerateTmuxConfig(cfg, theme)
	return writeToolConfig(configPath, []byte(content))
}

// SetupTPM handles TPM installation and plugin setup
func SetupTPM(cfg TmuxConfig, theme string) error {
	// Write config first
	if err := WriteTmuxConfig(cfg, theme); err != nil {
		return err
	}

	if !cfg.TPMEnabled {
		return nil
	}

	// Install TPM if not present
	if !IsTPMInstalled() {
		if err := InstallTPM(); err != nil {
			return err
		}
	}

	// Run plugin installation
	// This may fail if tmux is not running, which is OK
	_ = RunTPMInstall()

	return nil
}
