package tools

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/tekierz/dotfiles/internal/operation"
	"github.com/tekierz/dotfiles/internal/safefile"
)

func TestGenerateTmuxConfigSplitBindingsSurvive(t *testing.T) {
	cases := []struct {
		name          string
		splitBinds    string
		wantBinds     []string
		forbiddenKeys []string
	}{
		{
			name:       "documented pipe splits",
			splitBinds: "pipes",
			wantBinds: []string{
				"bind | split-window -h -c \"#{pane_current_path}\"",
				"bind - split-window -v -c \"#{pane_current_path}\"",
			},
			forbiddenKeys: []string{"|", "-"},
		},
		{
			name:       "percent splits",
			splitBinds: "percent",
			wantBinds: []string{
				"bind % split-window -h -c \"#{pane_current_path}\"",
				"bind '\"' split-window -v -c \"#{pane_current_path}\"",
			},
			forbiddenKeys: []string{"%", "'\"'"},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			out := GenerateTmuxConfig(TmuxConfig{SplitBinds: tc.splitBinds}, "catppuccin-mocha")
			for _, want := range tc.wantBinds {
				if !strings.Contains(out, want) {
					t.Fatalf("generated config missing split binding %q:\n%s", want, out)
				}
			}
			for _, key := range tc.forbiddenKeys {
				if strings.Contains(out, "unbind "+key+"\n") {
					t.Fatalf("generated config binds and unbinds split key %s:\n%s", key, out)
				}
			}
		})
	}
}

func TestWriteTmuxConfigPreservesNativeSettingsInManagedSection(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	path := filepath.Join(home, ".tmux.conf")
	const native = "# user setting\nset -g focus-events on\n"
	if err := os.WriteFile(path, []byte(native), 0o640); err != nil {
		t.Fatal(err)
	}

	_, accepted, parents, err := safefile.ObserveFileWithin(home, ".tmux.conf")
	if err != nil {
		t.Fatal(err)
	}
	if _, err := WriteTmuxConfigAtAuthorityTracked(TmuxConfig{Prefix: "ctrl-a", StatusBar: "bottom"}, "nord", accepted, parents, operation.DefaultLocker); err != nil {
		t.Fatal(err)
	}
	first, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(first), native) || strings.Count(string(first), tmuxManagedStart) != 1 || strings.Count(string(first), tmuxManagedEnd) != 1 {
		t.Fatalf("native tmux bytes were not preserved around one managed section:\n%s", first)
	}

	if err := WriteTmuxConfig(TmuxConfig{Prefix: "ctrl-b", StatusBar: "top"}, "dracula"); err != nil {
		t.Fatal(err)
	}
	second, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(second), native) || strings.Count(string(second), tmuxManagedStart) != 1 || !strings.Contains(string(second), "set -g prefix C-b") {
		t.Fatalf("managed tmux update changed native bytes or duplicated the section:\n%s", second)
	}
}

func TestWriteTmuxConfigRequiresReviewedNativeAdoption(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("XDG_CONFIG_HOME", "")
	path := filepath.Join(home, ".tmux.conf")
	const original = "# user setting\nset -g focus-events on\n"
	if err := os.WriteFile(path, []byte(original), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := WriteTmuxConfig(TmuxConfig{}, "nord"); !errors.Is(err, ErrUnmanagedConfig) {
		t.Fatalf("native adoption error = %v, want ErrUnmanagedConfig", err)
	}
	got, err := os.ReadFile(path)
	if err != nil || string(got) != original {
		t.Fatalf("refused native config changed: %q err=%v", got, err)
	}
}

func TestWriteTmuxConfigRefusesAmbiguousManagedSections(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	path := filepath.Join(home, ".tmux.conf")
	original := "# user setting\n" + tmuxManagedStart + "\nset -g mouse on\n"
	if err := os.WriteFile(path, []byte(original), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := WriteTmuxConfig(TmuxConfig{}, "nord"); err == nil {
		t.Fatal("incomplete managed tmux section was accepted")
	}
	got, err := os.ReadFile(path)
	if err != nil || string(got) != original {
		t.Fatalf("ambiguous tmux config changed: %q err=%v", got, err)
	}
}

func TestWriteTmuxConfigMigratesLegacyOwnedWholeFile(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	path := filepath.Join(home, ".tmux.conf")
	if err := os.WriteFile(path, []byte("# Generated by dotfiles TUI\nset -g mouse off\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := WriteTmuxConfig(TmuxConfig{MouseMode: true}, "nord"); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Count(string(got), "# Generated by dotfiles TUI") != 1 || !strings.HasPrefix(string(got), tmuxManagedStart+"\n") {
		t.Fatalf("legacy owned tmux config was not migrated cleanly:\n%s", got)
	}
}

func TestTmuxConfigMutationPathUsesFirstExistingCandidate(t *testing.T) {
	home := t.TempDir()
	defaultXDG := filepath.Join(home, ".config")
	t.Setenv("HOME", home)
	t.Setenv("XDG_CONFIG_HOME", defaultXDG)
	xdgPath := filepath.Join(defaultXDG, "tmux", "tmux.conf")
	if err := os.MkdirAll(filepath.Dir(xdgPath), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(xdgPath, []byte("# native XDG tmux\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	got, err := TmuxConfigMutationPath()
	if err != nil {
		t.Fatal(err)
	}
	if got != xdgPath {
		t.Fatalf("active tmux path = %q, want %q", got, xdgPath)
	}
	_, accepted, parents, err := safefile.ObserveFileWithin(home, filepath.ToSlash(filepath.Join(".config", "tmux", "tmux.conf")))
	if err != nil {
		t.Fatal(err)
	}
	if _, err := WriteTmuxConfigAtAuthorityTracked(TmuxConfig{Prefix: "ctrl-a"}, "nord", accepted, parents, operation.DefaultLocker); err != nil {
		t.Fatal(err)
	}
	updated, err := os.ReadFile(xdgPath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(updated), `source-file "$XDG_CONFIG_HOME/tmux/tmux.conf"`) {
		t.Fatalf("XDG config has wrong reload target:\n%s", updated)
	}
	if _, err := os.Lstat(filepath.Join(home, ".tmux.conf")); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("XDG write created legacy tmux config: %v", err)
	}

	legacyPath := filepath.Join(home, ".tmux.conf")
	if err := os.WriteFile(legacyPath, []byte("# native legacy tmux\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	got, err = TmuxConfigMutationPath()
	if err != nil || got != legacyPath {
		t.Fatalf("legacy precedence path = %q err=%v", got, err)
	}
}

func TestTmuxConfigMutationPathRejectsRelativeXDG(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("XDG_CONFIG_HOME", "relative/config")
	if _, err := TmuxConfigMutationPath(); err == nil {
		t.Fatal("relative XDG_CONFIG_HOME was accepted")
	}
	if err := WriteTmuxConfig(TmuxConfig{}, "nord"); err == nil {
		t.Fatal("tmux writer ignored invalid XDG_CONFIG_HOME")
	}
	if _, err := os.Lstat(filepath.Join(home, ".tmux.conf")); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("invalid discovery created legacy config: %v", err)
	}
}

func TestTmuxConfigMutationPathDoesNotBypassActiveSymlink(t *testing.T) {
	if os.PathSeparator == '\\' {
		t.Skip("symlink ownership checks are Unix-specific")
	}
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("XDG_CONFIG_HOME", "")
	victim := filepath.Join(home, "victim")
	if err := os.WriteFile(victim, []byte("do not change\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	legacyPath := filepath.Join(home, ".tmux.conf")
	if err := os.Symlink(victim, legacyPath); err != nil {
		t.Fatal(err)
	}
	got, err := TmuxConfigMutationPath()
	if err != nil || got != legacyPath {
		t.Fatalf("active symlink path = %q err=%v", got, err)
	}
	if err := WriteTmuxConfig(TmuxConfig{}, "nord"); !errors.Is(err, safefile.ErrSymlink) {
		t.Fatalf("writer error = %v, want symlink refusal", err)
	}
	data, err := os.ReadFile(victim)
	if err != nil || string(data) != "do not change\n" {
		t.Fatalf("symlink victim changed: %q err=%v", data, err)
	}
}
