package tools

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateTmuxConfigSplitBindingsSurvive(t *testing.T) {
	cases := []struct {
		name          string
		splitBinds    string
		wantBinds     []string
		forbiddenKeys []string
	}{
		{
			name:       "documented pipe splits",
			splitBinds: "pipes",
			wantBinds: []string{
				"bind | split-window -h -c \"#{pane_current_path}\"",
				"bind - split-window -v -c \"#{pane_current_path}\"",
			},
			forbiddenKeys: []string{"|", "-"},
		},
		{
			name:       "percent splits",
			splitBinds: "percent",
			wantBinds: []string{
				"bind % split-window -h -c \"#{pane_current_path}\"",
				"bind '\"' split-window -v -c \"#{pane_current_path}\"",
			},
			forbiddenKeys: []string{"%", "'\"'"},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			out := GenerateTmuxConfig(TmuxConfig{SplitBinds: tc.splitBinds}, "catppuccin-mocha")
			for _, want := range tc.wantBinds {
				if !strings.Contains(out, want) {
					t.Fatalf("generated config missing split binding %q:\n%s", want, out)
				}
			}
			for _, key := range tc.forbiddenKeys {
				if strings.Contains(out, "unbind "+key+"\n") {
					t.Fatalf("generated config binds and unbinds split key %s:\n%s", key, out)
				}
			}
		})
	}
}

func TestWriteTmuxConfigPreservesNativeSettingsInManagedSection(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	path := filepath.Join(home, ".tmux.conf")
	const native = "# user setting\nset -g focus-events on\n"
	if err := os.WriteFile(path, []byte(native), 0o640); err != nil {
		t.Fatal(err)
	}

	if err := WriteTmuxConfig(TmuxConfig{Prefix: "ctrl-a", StatusBar: "bottom"}, "nord"); err != nil {
		t.Fatal(err)
	}
	first, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(first), native) || strings.Count(string(first), tmuxManagedStart) != 1 || strings.Count(string(first), tmuxManagedEnd) != 1 {
		t.Fatalf("native tmux bytes were not preserved around one managed section:\n%s", first)
	}

	if err := WriteTmuxConfig(TmuxConfig{Prefix: "ctrl-b", StatusBar: "top"}, "dracula"); err != nil {
		t.Fatal(err)
	}
	second, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(second), native) || strings.Count(string(second), tmuxManagedStart) != 1 || !strings.Contains(string(second), "set -g prefix C-b") {
		t.Fatalf("managed tmux update changed native bytes or duplicated the section:\n%s", second)
	}
}

func TestWriteTmuxConfigRefusesAmbiguousManagedSections(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	path := filepath.Join(home, ".tmux.conf")
	original := "# user setting\n" + tmuxManagedStart + "\nset -g mouse on\n"
	if err := os.WriteFile(path, []byte(original), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := WriteTmuxConfig(TmuxConfig{}, "nord"); err == nil {
		t.Fatal("incomplete managed tmux section was accepted")
	}
	got, err := os.ReadFile(path)
	if err != nil || string(got) != original {
		t.Fatalf("ambiguous tmux config changed: %q err=%v", got, err)
	}
}

func TestWriteTmuxConfigMigratesLegacyOwnedWholeFile(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	path := filepath.Join(home, ".tmux.conf")
	if err := os.WriteFile(path, []byte("# Generated by dotfiles TUI\nset -g mouse off\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := WriteTmuxConfig(TmuxConfig{MouseMode: true}, "nord"); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Count(string(got), "# Generated by dotfiles TUI") != 1 || !strings.HasPrefix(string(got), tmuxManagedStart+"\n") {
		t.Fatalf("legacy owned tmux config was not migrated cleanly:\n%s", got)
	}
}
