package tools

import (
	"bytes"
	"crypto/sha256"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"testing"
)

func TestGenerateYaziConfigExactMinimalV26Bytes(t *testing.T) {
	base := YaziConfig{ShowHidden: true, SortBy: "natural", SortReverse: true, LineMode: "permissions", ScrollOff: 9}
	wants := map[string]string{
		"auto":   "# Generated by dotfiles TUI\n# Compatibility: Yazi 26.5.6\n\n[mgr]\nsort_by = \"natural\"\nsort_reverse = true\nlinemode = \"permissions\"\nscrolloff = 9\nshow_hidden = true\n\n[preview]\nimage_delay = 30\n",
		"always": "# Generated by dotfiles TUI\n# Compatibility: Yazi 26.5.6\n\n[mgr]\nsort_by = \"natural\"\nsort_reverse = true\nlinemode = \"permissions\"\nscrolloff = 9\nshow_hidden = true\n\n[preview]\nimage_delay = 0\n",
		"never":  "# Generated by dotfiles TUI\n# Compatibility: Yazi 26.5.6\n\n[mgr]\nsort_by = \"natural\"\nsort_reverse = true\nlinemode = \"permissions\"\nscrolloff = 9\nshow_hidden = true\n\n[preview]\nimage_delay = 30\n\n[plugin]\npreviewers = []\npreloaders = []\n",
	}
	for mode, want := range wants {
		t.Run(mode, func(t *testing.T) {
			cfg := base
			cfg.PreviewMode = mode
			if got := GenerateYaziConfig(cfg, "nord"); got != want {
				t.Fatalf("canonical %s yazi.toml mismatch:\n--- got ---\n%s--- want ---\n%s", mode, got, want)
			}
			for _, obsolete := range []string{"ratio =", "sort_sensitive", "sort_dir_first", "show_symlink", "tab_size", "max_width", "[opener]", "[log]"} {
				assertNotContainsText(t, want, obsolete)
			}
		})
	}
}

func TestGenerateYaziKeymapExactNonDestructiveV26Bytes(t *testing.T) {
	vim := "# Generated by dotfiles TUI\n# Compatibility: Yazi 26.5.6\n# Keymap style: vim\n"
	emacs := "# Generated by dotfiles TUI\n# Compatibility: Yazi 26.5.6\n# Keymap style: emacs\n\n[mgr]\nprepend_keymap = [\n  { on = \"<C-p>\", run = \"arrow -1\", desc = \"Move up\" },\n  { on = \"<C-n>\", run = \"arrow 1\", desc = \"Move down\" },\n  { on = \"<C-b>\", run = \"leave\", desc = \"Go to parent\" },\n  { on = \"<C-f>\", run = \"enter\", desc = \"Enter directory\" },\n  { on = \"<Space>\", run = \"toggle\", desc = \"Toggle selection\" },\n]\n"
	for style, want := range map[string]string{"vim": vim, "emacs": emacs} {
		t.Run(style, func(t *testing.T) {
			if got := GenerateYaziKeymap(YaziConfig{Keymap: style}, "nord"); got != want {
				t.Fatalf("canonical %s keymap mismatch:\n--- got ---\n%s--- want ---\n%s", style, got, want)
			}
			assertNotContainsText(t, want, "\nkeymap =")
			assertNotContainsText(t, want, "select --state=none")
		})
	}
}

func TestGenerateYaziKeymapInvalidOrEmptyFallsBackToCanonicalVim(t *testing.T) {
	want := GenerateYaziKeymap(YaziConfig{Keymap: "vim"}, "nord")
	for _, keymap := range []string{"", "unknown", "VIM"} {
		t.Run(fmt.Sprintf("%q", keymap), func(t *testing.T) {
			got := GenerateYaziKeymap(YaziConfig{Keymap: keymap}, "nord")
			if got != want {
				t.Fatalf("invalid keymap fallback mismatch:\n--- got ---\n%s--- want Vim ---\n%s", got, want)
			}
			home := t.TempDir()
			t.Setenv("HOME", home)
			t.Setenv("XDG_CONFIG_HOME", "")
			t.Setenv("YAZI_CONFIG_HOME", "")
			dir := filepath.Join(home, ".config", "yazi")
			if err := os.MkdirAll(dir, 0o700); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(filepath.Join(dir, YaziFileKeymap), []byte(got), 0o600); err != nil {
				t.Fatal(err)
			}
			imported, err := ImportYaziConfig()
			if err != nil {
				t.Fatal(err)
			}
			if imported.Keymap.Ownership != YaziOwnershipExactCurrent || imported.Config.Keymap != "vim" {
				t.Fatalf("fallback bytes not canonical Vim: observation=%#v config=%#v", imported.Keymap, imported.Config)
			}
		})
	}
}

func TestGenerateYaziThemeHasCompatibilityHeaderAndPinnedHash(t *testing.T) {
	got := GenerateYaziTheme("nord")
	assertContainsText(t, got, "# Generated by dotfiles TUI\n# Compatibility: Yazi 26.5.6\n# Theme: nord\n")
	if hash := fmt.Sprintf("%x", sha256.Sum256([]byte(got))); hash != "846959713f83ef8750d1b69f51f8f29ee71a433ca9b01d3473e21fff61bfa656" {
		t.Fatalf("canonical current theme hash = %s", hash)
	}
}

func TestGeneratedYaziTripleImportsAsExactCurrent(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("XDG_CONFIG_HOME", "")
	t.Setenv("YAZI_CONFIG_HOME", "")
	dir := filepath.Join(home, ".config", "yazi")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		t.Fatal(err)
	}
	cfg := YaziConfig{Keymap: "emacs", ShowHidden: true, PreviewMode: "never", SortBy: "natural", SortReverse: true, LineMode: "permissions", ScrollOff: 9}
	for name, content := range map[string]string{
		YaziFileMain: GenerateYaziConfig(cfg, "nord"), YaziFileKeymap: GenerateYaziKeymap(cfg, "nord"), YaziFileTheme: GenerateYaziTheme("nord"),
	} {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	imported, err := ImportYaziConfig()
	if err != nil {
		t.Fatal(err)
	}
	if imported.Main.Ownership != YaziOwnershipExactCurrent || imported.Keymap.Ownership != YaziOwnershipExactCurrent || imported.Theme.Ownership != YaziOwnershipExactCurrent {
		t.Fatalf("generated triple not ExactCurrent: main=%#v keymap=%#v theme=%#v", imported.Main, imported.Keymap, imported.Theme)
	}
}

func TestWriteYaziConfigWritesAllFiles(t *testing.T) {
	tmpHome := t.TempDir()
	t.Setenv("HOME", tmpHome)
	t.Setenv("XDG_CONFIG_HOME", "")
	t.Setenv("YAZI_CONFIG_HOME", "")

	cfg := YaziConfig{
		Keymap:      "emacs",
		ShowHidden:  true,
		PreviewMode: "auto",
		SortBy:      "natural",
		LineMode:    "size",
		ScrollOff:   5,
	}
	if err := WriteYaziConfig(cfg, "dracula"); err != nil {
		t.Fatalf("WriteYaziConfig returned error: %v", err)
	}

	configDir := filepath.Join(tmpHome, ".config", "yazi")
	for _, name := range []string{"yazi.toml", "keymap.toml", "theme.toml"} {
		if _, err := os.Stat(filepath.Join(configDir, name)); err != nil {
			t.Fatalf("expected %s to be written: %v", name, err)
		}
	}
}

func TestGenerateYaziTheme(t *testing.T) {
	out := GenerateYaziTheme("dracula")

	assertContainsText(t, out, "#ff79c6")
	// yazi 26.x renamed [manager]->[mgr] and [select]->[pick]; the old names are
	// silently ignored, so the generator (and this test) must use the new schema.
	for _, header := range []string{
		"[mgr]",
		"[tabs]",
		"[status]",
		"[input]",
		"[pick]",
		"[tasks]",
		"[which]",
		"[help]",
		"[filetype]",
	} {
		assertContainsText(t, out, header)
	}
	assertNotContainsText(t, out, "[manager]")
	assertNotContainsText(t, out, "[select]")
}

func TestGenerateYaziThemeUnknownFallsBackToMocha(t *testing.T) {
	got := GenerateYaziTheme("unknown-theme")
	want := GenerateYaziTheme("catppuccin-mocha")
	if got != want {
		t.Fatalf("unknown theme did not normalize to canonical Mocha bytes:\n--- got ---\n%s--- want ---\n%s", got, want)
	}
	assertContainsText(t, got, "# Compatibility: Yazi 26.5.6")
	assertContainsText(t, got, "# Theme: catppuccin-mocha")
	assertNotContainsText(t, got, "unknown-theme")

	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("XDG_CONFIG_HOME", "")
	t.Setenv("YAZI_CONFIG_HOME", "")
	dir := filepath.Join(home, ".config", "yazi")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, YaziFileTheme), []byte(got), 0o600); err != nil {
		t.Fatal(err)
	}
	imported, err := ImportYaziConfig()
	if err != nil {
		t.Fatal(err)
	}
	if imported.Theme.Ownership != YaziOwnershipExactCurrent {
		t.Fatalf("normalized Mocha theme not ExactCurrent: %#v", imported.Theme)
	}
}

func TestWriteYaziConfigPreflightsWholeSetBeforeChangingEarlierFiles(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("XDG_CONFIG_HOME", "")
	dir := filepath.Join(home, ".config", "yazi")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		t.Fatal(err)
	}
	yaziPath := filepath.Join(dir, "yazi.toml")
	original := []byte(GenerateYaziConfig(YaziConfig{SortBy: "natural"}, "nord"))
	if err := os.WriteFile(yaziPath, original, 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "theme.toml"), []byte("# user-owned theme\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := WriteYaziConfig(YaziConfig{SortBy: "size"}, "dracula"); !errors.Is(err, ErrUnmanagedConfig) {
		t.Fatalf("WriteYaziConfig error = %v, want ErrUnmanagedConfig", err)
	}
	if got := mustReadOwnershipFile(t, yaziPath); !bytes.Equal(got, original) {
		t.Fatalf("yazi.toml changed before later theme ownership failure: %q", got)
	}
	assertOwnershipPathAbsent(t, filepath.Join(dir, "keymap.toml"))
}

func TestWriteYaziConfigReportsOnlyDefinitelyCommittedPartialTargets(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("XDG_CONFIG_HOME", "")
	wantErr := errors.New("injected second-target failure")
	calls := 0
	_, err := writeYaziConfigWithWriters(YaziConfig{}, "dracula", func(path string, _ []byte) (MutationEvidence, error) {
		calls++
		if calls == 2 {
			return MutationEvidence{}, wantErr
		}
		return MutationEvidence{Path: path}, nil
	}, func(string, []byte) (MutationEvidence, error) {
		t.Fatal("theme writer ran after second-target failure")
		return MutationEvidence{}, nil
	})
	if !errors.Is(err, wantErr) {
		t.Fatalf("writeYaziConfigWithWriters error = %v", err)
	}
	var partial interface{ CommittedEvidence() []MutationEvidence }
	if !errors.As(err, &partial) {
		t.Fatalf("partial write error did not expose committed targets: %T", err)
	}
	want := filepath.Join(home, ".config", "yazi", "yazi.toml")
	if got := partial.CommittedEvidence(); len(got) != 1 || got[0].Path != want {
		t.Fatalf("committed targets = %v, want only %s", got, want)
	}
}

func TestGenerateYaziConfigPreviewModeAffectsOutput(t *testing.T) {
	cfg := YaziConfig{
		SortBy:    "natural",
		LineMode:  "size",
		ScrollOff: 5,
	}

	auto := GenerateYaziConfig(cfg, "catppuccin-mocha")
	cfg.PreviewMode = "never"
	never := GenerateYaziConfig(cfg, "catppuccin-mocha")

	if auto == never {
		t.Fatal("PreviewMode=never produced the same yazi.toml as auto")
	}
	assertContainsText(t, auto, "image_delay = 30")
	assertNotContainsText(t, auto, "previewers = []")
	assertContainsText(t, never, "[plugin]")
	assertContainsText(t, never, "previewers = []")
	assertContainsText(t, never, "preloaders = []")
}

func TestGenerateYaziConfigDefaultsEmptyLineMode(t *testing.T) {
	out := GenerateYaziConfig(YaziConfig{}, "catppuccin-mocha")

	assertContainsText(t, out, `linemode = "none"`)
	assertNotContainsText(t, out, `linemode = ""`)
}
