package tools

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/tekierz/dotfiles/internal/pkg"
)

// YaziConfig holds Yazi configuration settings
type YaziConfig struct {
	Keymap      string // "vim", "emacs"
	ShowHidden  bool
	PreviewMode string // "auto", "always", "never"
}

// YaziTool represents the Yazi file manager
type YaziTool struct {
	BaseTool
}

// NewYaziTool creates a new Yazi tool
func NewYaziTool() *YaziTool {
	home, _ := os.UserHomeDir()
	return &YaziTool{
		BaseTool: BaseTool{
			id:          "yazi",
			name:        "Yazi",
			description: "Blazing fast terminal file manager",
			icon:        "󰉋",
			category:    CategoryFile,
			packages: map[pkg.Platform][]string{
				pkg.PlatformMacOS: {"yazi", "ffmpegthumbnailer", "unar", "jq", "poppler", "fd", "ripgrep", "fzf", "zoxide", "imagemagick"},
				pkg.PlatformArch:  {"yazi", "ffmpegthumbnailer", "unarchiver", "jq", "poppler", "fd", "ripgrep", "fzf", "zoxide", "imagemagick"},
			},
			configPaths: []string{
				filepath.Join(home, ".config", "yazi", "yazi.toml"),
				filepath.Join(home, ".config", "yazi", "keymap.toml"),
				filepath.Join(home, ".config", "yazi", "theme.toml"),
			},
			heavyTool: true, // Skip on low-memory systems (Pi Zero 2)
			// UI metadata
			uiGroup:        UIGroupNone,
			configScreen:   14, // ScreenConfigYazi
			defaultEnabled: true,
		},
	}
}

// GenerateYaziConfig builds the yazi.toml content
func GenerateYaziConfig(cfg YaziConfig, theme string) string {
	var sb strings.Builder

	// Header
	sb.WriteString("# Generated by dotfiles TUI\n")
	sb.WriteString(fmt.Sprintf("# Theme: %s\n\n", theme))

	// Manager settings
	sb.WriteString("[manager]\n")
	sb.WriteString("ratio = [1, 4, 3]\n")
	sb.WriteString("sort_by = \"natural\"\n")
	sb.WriteString("sort_sensitive = false\n")
	sb.WriteString("sort_reverse = false\n")
	sb.WriteString("sort_dir_first = true\n")
	sb.WriteString("linemode = \"size\"\n")
	sb.WriteString(fmt.Sprintf("show_hidden = %t\n", cfg.ShowHidden))
	sb.WriteString("show_symlink = true\n\n")

	// Preview settings
	sb.WriteString("[preview]\n")
	sb.WriteString("tab_size = 2\n")
	sb.WriteString("max_width = 600\n")
	sb.WriteString("max_height = 900\n")
	sb.WriteString("cache_dir = \"\"\n")
	sb.WriteString("image_filter = \"triangle\"\n")
	sb.WriteString("image_quality = 75\n")
	sb.WriteString("sixel_fraction = 15\n")
	sb.WriteString("ueberzug_scale = 1\n")
	sb.WriteString("ueberzug_offset = [0, 0, 0, 0]\n\n")

	// Opener settings
	sb.WriteString("[opener]\n")
	sb.WriteString("edit = [\n")
	sb.WriteString("  { run = '\"$EDITOR\" \"$@\"', block = true, for = \"unix\" },\n")
	sb.WriteString("]\n")
	sb.WriteString("open = [\n")
	sb.WriteString("  { run = 'xdg-open \"$@\"', desc = \"Open\", for = \"linux\" },\n")
	sb.WriteString("  { run = 'open \"$@\"', desc = \"Open\", for = \"macos\" },\n")
	sb.WriteString("]\n\n")

	// Log settings
	sb.WriteString("[log]\n")
	sb.WriteString("enabled = false\n")

	return sb.String()
}

// GenerateYaziKeymap builds the keymap.toml content
func GenerateYaziKeymap(cfg YaziConfig, theme string) string {
	var sb strings.Builder

	// Header
	sb.WriteString("# Generated by dotfiles TUI\n")
	sb.WriteString(fmt.Sprintf("# Keymap style: %s\n\n", cfg.Keymap))

	// Manager keymaps (common)
	sb.WriteString("[manager]\n")
	sb.WriteString("keymap = [\n")

	// Navigation keys depend on keymap style
	if cfg.Keymap == "vim" {
		sb.WriteString("  # Vim-style navigation\n")
		sb.WriteString("  { on = \"k\", run = \"arrow -1\", desc = \"Move up\" },\n")
		sb.WriteString("  { on = \"j\", run = \"arrow 1\", desc = \"Move down\" },\n")
		sb.WriteString("  { on = \"h\", run = \"leave\", desc = \"Go to parent\" },\n")
		sb.WriteString("  { on = \"l\", run = \"enter\", desc = \"Enter directory\" },\n")
		sb.WriteString("  { on = \"g\", run = \"arrow -99999999\", desc = \"Go to top\" },\n")
		sb.WriteString("  { on = \"G\", run = \"arrow 99999999\", desc = \"Go to bottom\" },\n")
	} else {
		sb.WriteString("  # Emacs-style navigation\n")
		sb.WriteString("  { on = \"<C-p>\", run = \"arrow -1\", desc = \"Move up\" },\n")
		sb.WriteString("  { on = \"<C-n>\", run = \"arrow 1\", desc = \"Move down\" },\n")
		sb.WriteString("  { on = \"<C-b>\", run = \"leave\", desc = \"Go to parent\" },\n")
		sb.WriteString("  { on = \"<C-f>\", run = \"enter\", desc = \"Enter directory\" },\n")
		sb.WriteString("  { on = \"<M-<>\", run = \"arrow -99999999\", desc = \"Go to top\" },\n")
		sb.WriteString("  { on = \"<M->>\", run = \"arrow 99999999\", desc = \"Go to bottom\" },\n")
	}

	// Common keys
	sb.WriteString("\n  # Common operations\n")
	sb.WriteString("  { on = \"<Enter>\", run = \"open\", desc = \"Open file\" },\n")
	sb.WriteString("  { on = \"<Esc>\", run = \"escape\", desc = \"Cancel\" },\n")
	sb.WriteString("  { on = \"q\", run = \"quit\", desc = \"Quit\" },\n")
	sb.WriteString("  { on = \"Q\", run = \"quit --no-cwd-file\", desc = \"Quit without changing cwd\" },\n")
	sb.WriteString("  { on = \".\", run = \"hidden toggle\", desc = \"Toggle hidden files\" },\n")
	sb.WriteString("  { on = \"/\", run = \"find --smart\", desc = \"Find\" },\n")
	sb.WriteString("  { on = \"y\", run = \"yank\", desc = \"Yank (copy)\" },\n")
	sb.WriteString("  { on = \"x\", run = \"yank --cut\", desc = \"Cut\" },\n")
	sb.WriteString("  { on = \"p\", run = \"paste\", desc = \"Paste\" },\n")
	sb.WriteString("  { on = \"d\", run = \"remove\", desc = \"Delete\" },\n")
	sb.WriteString("  { on = \"a\", run = \"create\", desc = \"Create file/directory\" },\n")
	sb.WriteString("  { on = \"r\", run = \"rename\", desc = \"Rename\" },\n")
	sb.WriteString("  { on = \"<Space>\", run = \"select --state=none\", desc = \"Toggle selection\" },\n")
	sb.WriteString("  { on = \"~\", run = \"cd ~\", desc = \"Go to home\" },\n")
	sb.WriteString("]\n")

	return sb.String()
}

// WriteYaziConfig writes all Yazi config files to disk
func WriteYaziConfig(cfg YaziConfig, theme string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}

	configDir := filepath.Join(home, ".config", "yazi")
	if err := os.MkdirAll(configDir, 0700); err != nil {
		return fmt.Errorf("failed to create yazi config directory: %w", err)
	}

	// Write yazi.toml
	yaziPath := filepath.Join(configDir, "yazi.toml")
	yaziContent := GenerateYaziConfig(cfg, theme)
	if err := os.WriteFile(yaziPath, []byte(yaziContent), 0600); err != nil {
		return fmt.Errorf("failed to write yazi.toml: %w", err)
	}

	// Write keymap.toml
	keymapPath := filepath.Join(configDir, "keymap.toml")
	keymapContent := GenerateYaziKeymap(cfg, theme)
	if err := os.WriteFile(keymapPath, []byte(keymapContent), 0600); err != nil {
		return fmt.Errorf("failed to write keymap.toml: %w", err)
	}

	return nil
}

// GenerateConfig implements Tool interface (uses defaults)
func (t *YaziTool) GenerateConfig(theme string) string {
	cfg := YaziConfig{
		Keymap:      "vim",
		ShowHidden:  false,
		PreviewMode: "auto",
	}
	return GenerateYaziConfig(cfg, theme)
}

// ApplyConfig implements Tool interface (uses defaults)
func (t *YaziTool) ApplyConfig(theme string) error {
	cfg := YaziConfig{
		Keymap:      "vim",
		ShowHidden:  false,
		PreviewMode: "auto",
	}
	return WriteYaziConfig(cfg, theme)
}
