package tools

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/tekierz/dotfiles/internal/operation"
	"github.com/tekierz/dotfiles/internal/pkg"
	"github.com/tekierz/dotfiles/internal/safefile"
)

// YaziConfig holds Yazi configuration settings
type YaziConfig struct {
	Keymap      string // "vim", "emacs"
	ShowHidden  bool
	PreviewMode string // "auto", "always", "never"

	SortBy      string // "alphabetical", "modified", "size", "natural"
	SortReverse bool   // reverse sort direction
	LineMode    string // "size", "permissions", "mtime", "none"
	ScrollOff   int    // items kept visible above/below cursor
}

// IsInstalled recognizes direct/manual Yazi installs as well as package
// receipts. This keeps unsupported Debian/Pi package planning separate from an
// external binary that the dashboard may still configure.
func (t *YaziTool) IsInstalled() bool {
	return directInstallationDetected(t) || t.BaseTool.IsInstalled()
}

func (t *YaziTool) IsInstalledOutsidePackageManager(DirectInstallationObservation) bool {
	if _, err := exec.LookPath("yazi"); err == nil {
		return true
	}
	return false
}

// YaziTool represents the Yazi file manager
type YaziTool struct {
	BaseTool
}

// NewYaziTool creates a new Yazi tool
func NewYaziTool() *YaziTool {
	home, _ := os.UserHomeDir()
	return &YaziTool{
		BaseTool: BaseTool{
			id:          "yazi",
			name:        "Yazi",
			description: "Blazing fast terminal file manager",
			icon:        "󰉋",
			category:    CategoryFile,
			packages: map[pkg.Platform][]string{
				pkg.PlatformMacOS: {"yazi", "ffmpegthumbnailer", "unar", "jq", "poppler", "fd", "ripgrep", "fzf", "zoxide", "imagemagick"},
				pkg.PlatformArch:  {"yazi", "ffmpegthumbnailer", "unarchiver", "jq", "poppler", "fd", "ripgrep", "fzf", "zoxide", "imagemagick"},
			},
			configPaths: []string{
				filepath.Join(home, ".config", "yazi", "yazi.toml"),
				filepath.Join(home, ".config", "yazi", "keymap.toml"),
				filepath.Join(home, ".config", "yazi", "theme.toml"),
			},
			heavyTool: true, // Skip on low-memory systems (Pi Zero 2)
			// UI metadata
			uiGroup:        UIGroupNone,
			configScreen:   14, // ScreenConfigYazi
			defaultEnabled: true,
		},
	}
}

// GenerateYaziConfig builds the yazi.toml content
func GenerateYaziConfig(cfg YaziConfig, theme string) string {
	var sb strings.Builder

	// Header
	sb.WriteString("# Generated by dotfiles TUI\n")
	sb.WriteString(fmt.Sprintf("# Theme: %s\n\n", theme))

	// Manager settings
	sb.WriteString("[mgr]\n")
	sb.WriteString("ratio = [1, 4, 3]\n")
	sb.WriteString(fmt.Sprintf("sort_by = \"%s\"\n", yaziSortBy(cfg.SortBy)))
	sb.WriteString("sort_sensitive = false\n")
	sb.WriteString(fmt.Sprintf("sort_reverse = %t\n", cfg.SortReverse))
	sb.WriteString("sort_dir_first = true\n")
	sb.WriteString(fmt.Sprintf("linemode = \"%s\"\n", yaziLineMode(cfg.LineMode)))
	sb.WriteString(fmt.Sprintf("scrolloff = %d\n", cfg.ScrollOff))
	sb.WriteString(fmt.Sprintf("show_hidden = %t\n", cfg.ShowHidden))
	sb.WriteString("show_symlink = true\n\n")

	// Preview settings
	sb.WriteString("[preview]\n")
	sb.WriteString(fmt.Sprintf("# Preview mode: %s\n", yaziPreviewMode(cfg.PreviewMode)))
	sb.WriteString("# yazi has no single preview toggle; image_delay controls eager image rendering,\n")
	sb.WriteString("# and PreviewMode=never disables previewer plugins in the [plugin] section below.\n")
	sb.WriteString(fmt.Sprintf("image_delay = %d\n", yaziPreviewImageDelay(cfg.PreviewMode)))
	sb.WriteString("tab_size = 2\n")
	sb.WriteString("max_width = 600\n")
	sb.WriteString("max_height = 900\n")
	sb.WriteString("cache_dir = \"\"\n")
	sb.WriteString("image_filter = \"triangle\"\n")
	sb.WriteString("image_quality = 75\n")
	sb.WriteString("ueberzug_scale = 1\n")
	sb.WriteString("ueberzug_offset = [0, 0, 0, 0]\n\n")

	// Opener settings
	sb.WriteString("[opener]\n")
	sb.WriteString("edit = [\n")
	sb.WriteString("  { run = '\"$EDITOR\" \"$@\"', block = true, for = \"unix\" },\n")
	sb.WriteString("]\n")
	sb.WriteString("open = [\n")
	sb.WriteString("  { run = 'xdg-open \"$@\"', desc = \"Open\", for = \"linux\" },\n")
	sb.WriteString("  { run = 'open \"$@\"', desc = \"Open\", for = \"macos\" },\n")
	sb.WriteString("]\n\n")

	// Log settings
	sb.WriteString("[log]\n")
	sb.WriteString("enabled = false\n")

	if yaziPreviewMode(cfg.PreviewMode) == "never" {
		sb.WriteString("\n[plugin]\n")
		sb.WriteString("# PreviewMode=never disables yazi's previewer plugins with a schema-valid override.\n")
		sb.WriteString("previewers = []\n")
	}

	return sb.String()
}

func yaziPreviewMode(mode string) string {
	switch mode {
	case "always", "never":
		return mode
	default:
		return "auto"
	}
}

func yaziPreviewImageDelay(mode string) int {
	if yaziPreviewMode(mode) == "always" {
		return 0
	}
	return 30
}

// yaziSortBy maps the Manage UI's sort vocabulary onto the values yazi's
// [mgr] sort_by accepts. yazi understands alphabetical/natural/size/mtime
// (among others); the UI's "modified" is yazi's "mtime". Unrecognized values fall
// back to "natural" so the written file is always a value yazi accepts.
func yaziSortBy(sortBy string) string {
	switch sortBy {
	case "modified":
		return "mtime"
	case "alphabetical", "natural", "size":
		return sortBy
	default:
		return "natural"
	}
}

// yaziLineMode validates the value written to [mgr] linemode. yazi accepts
// none/size/btime/ctime/mtime/permissions/owner; unrecognized values fall back
// to "size" so the written file is always a value yazi accepts.
func yaziLineMode(lineMode string) string {
	switch lineMode {
	case "none", "size", "btime", "ctime", "mtime", "permissions", "owner":
		return lineMode
	default:
		return "size"
	}
}

// GenerateYaziKeymap builds the keymap.toml content
func GenerateYaziKeymap(cfg YaziConfig, theme string) string {
	var sb strings.Builder

	// Header
	sb.WriteString("# Generated by dotfiles TUI\n")
	sb.WriteString(fmt.Sprintf("# Keymap style: %s\n\n", cfg.Keymap))

	// Manager keymaps (common)
	sb.WriteString("[mgr]\n")
	sb.WriteString("keymap = [\n")

	// Navigation keys depend on keymap style
	if cfg.Keymap == "vim" {
		sb.WriteString("  # Vim-style navigation\n")
		sb.WriteString("  { on = \"k\", run = \"arrow -1\", desc = \"Move up\" },\n")
		sb.WriteString("  { on = \"j\", run = \"arrow 1\", desc = \"Move down\" },\n")
		sb.WriteString("  { on = \"h\", run = \"leave\", desc = \"Go to parent\" },\n")
		sb.WriteString("  { on = \"l\", run = \"enter\", desc = \"Enter directory\" },\n")
		sb.WriteString("  { on = \"g\", run = \"arrow -99999999\", desc = \"Go to top\" },\n")
		sb.WriteString("  { on = \"G\", run = \"arrow 99999999\", desc = \"Go to bottom\" },\n")
	} else {
		sb.WriteString("  # Emacs-style navigation\n")
		sb.WriteString("  { on = \"<C-p>\", run = \"arrow -1\", desc = \"Move up\" },\n")
		sb.WriteString("  { on = \"<C-n>\", run = \"arrow 1\", desc = \"Move down\" },\n")
		sb.WriteString("  { on = \"<C-b>\", run = \"leave\", desc = \"Go to parent\" },\n")
		sb.WriteString("  { on = \"<C-f>\", run = \"enter\", desc = \"Enter directory\" },\n")
		sb.WriteString("  { on = \"g\", run = \"arrow -99999999\", desc = \"Go to top\" },\n")
		sb.WriteString("  { on = \"G\", run = \"arrow 99999999\", desc = \"Go to bottom\" },\n")
	}

	// Common keys
	sb.WriteString("\n  # Common operations\n")
	sb.WriteString("  { on = \"<Enter>\", run = \"open\", desc = \"Open file\" },\n")
	sb.WriteString("  { on = \"<Esc>\", run = \"escape\", desc = \"Cancel\" },\n")
	sb.WriteString("  { on = \"q\", run = \"quit\", desc = \"Quit\" },\n")
	sb.WriteString("  { on = \"Q\", run = \"quit --no-cwd-file\", desc = \"Quit without changing cwd\" },\n")
	sb.WriteString("  { on = \".\", run = \"hidden toggle\", desc = \"Toggle hidden files\" },\n")
	sb.WriteString("  { on = \"/\", run = \"find --smart\", desc = \"Find\" },\n")
	sb.WriteString("  { on = \"y\", run = \"yank\", desc = \"Yank (copy)\" },\n")
	sb.WriteString("  { on = \"x\", run = \"yank --cut\", desc = \"Cut\" },\n")
	sb.WriteString("  { on = \"p\", run = \"paste\", desc = \"Paste\" },\n")
	sb.WriteString("  { on = \"d\", run = \"remove\", desc = \"Delete\" },\n")
	sb.WriteString("  { on = \"a\", run = \"create\", desc = \"Create file/directory\" },\n")
	sb.WriteString("  { on = \"r\", run = \"rename\", desc = \"Rename\" },\n")
	sb.WriteString("  { on = \"<Space>\", run = \"select --state=none\", desc = \"Toggle selection\" },\n")
	sb.WriteString("  { on = \"~\", run = \"cd ~\", desc = \"Go to home\" },\n")
	sb.WriteString("]\n")

	return sb.String()
}

// WriteYaziConfig writes all Yazi config files to disk
func WriteYaziConfig(cfg YaziConfig, theme string) error {
	_, err := WriteYaziConfigTracked(cfg, theme)
	return err
}

func WriteYaziConfigTracked(cfg YaziConfig, theme string) ([]MutationEvidence, error) {
	return writeYaziConfigWithWriters(cfg, theme, writeToolConfigTracked, writeYaziThemeConfigTracked)
}

// WriteYaziConfigAtRevisionsTracked applies the complete plan-accepted Yazi set.
func WriteYaziConfigAtRevisionsTracked(cfg YaziConfig, theme string, yaziAccepted, keymapAccepted, themeAccepted safefile.Revision) ([]MutationEvidence, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, err
	}
	dir := filepath.Join(home, ".config", "yazi")
	yp, err := compatibilityToolConfigParents(filepath.Join(dir, "yazi.toml"))
	if err != nil {
		return nil, err
	}
	kp, err := compatibilityToolConfigParents(filepath.Join(dir, "keymap.toml"))
	if err != nil {
		return nil, err
	}
	tp, err := compatibilityToolConfigParents(filepath.Join(dir, "theme.toml"))
	if err != nil {
		return nil, err
	}
	return WriteYaziConfigAtAuthoritiesTracked(cfg, theme, yaziAccepted, yp, keymapAccepted, kp, themeAccepted, tp, operation.DefaultLocker)
}

func WriteYaziConfigAtAuthoritiesTracked(cfg YaziConfig, theme string, yaziAccepted safefile.Revision, yaziParents *safefile.ParentChain, keymapAccepted safefile.Revision, keymapParents *safefile.ParentChain, themeAccepted safefile.Revision, themeParents *safefile.ParentChain, locker operation.Locker) ([]MutationEvidence, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, fmt.Errorf("failed to get home directory: %w", err)
	}
	configDir := filepath.Join(home, ".config", "yazi")
	yaziPath := filepath.Join(configDir, "yazi.toml")
	keymapPath := filepath.Join(configDir, "keymap.toml")
	themePath := filepath.Join(configDir, "theme.toml")
	for _, target := range []struct {
		path     string
		accepted safefile.Revision
		parents  *safefile.ParentChain
		legacy   func([]byte) bool
	}{
		{yaziPath, yaziAccepted, yaziParents, nil},
		{keymapPath, keymapAccepted, keymapParents, nil},
		{themePath, themeAccepted, themeParents, hasLegacyGeneratedYaziThemeHeader},
	} {
		if err := preflightToolConfigAtAuthority(target.path, target.accepted, target.parents, locker, target.legacy); err != nil {
			return nil, fmt.Errorf("preflight accepted Yazi config set: %w", err)
		}
	}

	var results, committed []MutationEvidence
	evidence, err := writeToolConfigAtAuthorityTracked(yaziPath, []byte(GenerateYaziConfig(cfg, theme)), yaziAccepted, yaziParents, locker)
	if err != nil {
		return nil, partialMutationError(err, committed)
	}
	results = append(results, evidence)
	if evidence.Revision != yaziAccepted {
		committed = append(committed, evidence)
	}
	evidence, err = writeToolConfigAtAuthorityTracked(keymapPath, []byte(GenerateYaziKeymap(cfg, theme)), keymapAccepted, keymapParents, locker)
	if err != nil {
		return nil, partialMutationError(err, committed)
	}
	results = append(results, evidence)
	if evidence.Revision != keymapAccepted {
		committed = append(committed, evidence)
	}
	evidence, err = writeYaziThemeConfigAtAuthorityTracked(themePath, []byte(GenerateYaziTheme(theme)), themeAccepted, themeParents, locker)
	if err != nil {
		return nil, partialMutationError(err, committed)
	}
	return append(results, evidence), nil
}

func writeYaziConfigWithWriters(cfg YaziConfig, theme string, writeWhole, writeTheme func(string, []byte) (MutationEvidence, error)) ([]MutationEvidence, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, fmt.Errorf("failed to get home directory: %w", err)
	}

	configDir := filepath.Join(home, ".config", "yazi")
	yaziPath := filepath.Join(configDir, "yazi.toml")
	keymapPath := filepath.Join(configDir, "keymap.toml")
	themePath := filepath.Join(configDir, "theme.toml")
	for _, target := range []struct {
		path        string
		legacyTheme bool
	}{{yaziPath, false}, {keymapPath, false}, {themePath, true}} {
		if err := preflightWholeFileConfig(target.path, target.legacyTheme); err != nil {
			return nil, fmt.Errorf("preflight Yazi config set: %w", err)
		}
	}

	// Write yazi.toml
	var committed []MutationEvidence
	yaziContent := GenerateYaziConfig(cfg, theme)
	evidence, err := writeWhole(yaziPath, []byte(yaziContent))
	if err != nil {
		return nil, partialMutationError(err, committed)
	}
	committed = append(committed, evidence)

	// Write keymap.toml
	keymapContent := GenerateYaziKeymap(cfg, theme)
	evidence, err = writeWhole(keymapPath, []byte(keymapContent))
	if err != nil {
		return nil, partialMutationError(err, committed)
	}
	committed = append(committed, evidence)

	// Write theme.toml
	themeContent := GenerateYaziTheme(theme)
	evidence, err = writeTheme(themePath, []byte(themeContent))
	if err != nil {
		return nil, partialMutationError(err, committed)
	}
	return append(committed, evidence), nil
}

// writeYaziThemeConfig is the path-scoped migration adapter for themes emitted
// before the exact whole-file ownership header was introduced. Only a known
// Yazi theme name in the former exact first-line format is accepted; arbitrary
// TOML comments cannot grant ownership. The reviewed operation backup owns
// recovery, and all other unmarked files fail closed.
func writeYaziThemeConfig(path string, content []byte) error {
	_, err := writeYaziThemeConfigTracked(path, content)
	return err
}

func writeYaziThemeConfigTracked(path string, content []byte) (MutationEvidence, error) {
	if !hasGeneratedConfigHeader(content) {
		return MutationEvidence{}, fmt.Errorf("%w: replacement for %s has no recognized ownership header", ErrUnmanagedConfig, path)
	}
	var evidence MutationEvidence
	err := withToolConfigLock(path, func(root, rel string) error {
		existing, revision, err := readToolConfig(root, rel)
		if err != nil {
			return err
		}
		legacy := revision.Exists() && hasLegacyGeneratedYaziThemeHeader(existing)
		if revision.Exists() && !hasGeneratedConfigHeader(existing) && !legacy {
			return fmt.Errorf("%w: %s", ErrUnmanagedConfig, path)
		}
		if revision.Exists() && bytes.Equal(existing, content) {
			return nil
		}
		committed, err := replaceToolConfigAtRevisionTracked(root, rel, revision, content)
		if err == nil {
			evidence = MutationEvidence{Path: path, Revision: committed}
		}
		return err
	})
	return evidence, err
}

func writeYaziThemeConfigAtAuthorityTracked(path string, content []byte, accepted safefile.Revision, parents *safefile.ParentChain, locker operation.Locker) (MutationEvidence, error) {
	if !accepted.Tracked() {
		return MutationEvidence{}, fmt.Errorf("%w: accepted Yazi theme revision is untracked", safefile.ErrRevisionChanged)
	}
	if !parents.Tracked() || locker == nil {
		return MutationEvidence{}, fmt.Errorf("%w: accepted Yazi theme authority is incomplete", safefile.ErrParentChanged)
	}
	if !hasGeneratedConfigHeader(content) {
		return MutationEvidence{}, fmt.Errorf("%w: replacement for %s has no recognized ownership header", ErrUnmanagedConfig, path)
	}
	var evidence MutationEvidence
	err := withToolConfigLockAuthorized(path, locker, func(root, rel string) error {
		var existing []byte
		var current safefile.Revision
		var err error
		if parents != nil {
			existing, current, err = safefile.ReadWithinAuthorized(root, rel, parents)
		} else {
			existing, current, err = readToolConfig(root, rel)
		}
		if err != nil {
			return err
		}
		if current != accepted {
			return fmt.Errorf("%w: Yazi theme changed after plan acceptance", safefile.ErrRevisionChanged)
		}
		legacy := current.Exists() && hasLegacyGeneratedYaziThemeHeader(existing)
		if current.Exists() && !hasGeneratedConfigHeader(existing) && !legacy {
			return fmt.Errorf("%w: %s", ErrUnmanagedConfig, path)
		}
		if current.Exists() && bytes.Equal(existing, content) {
			evidence = MutationEvidence{Path: path, Revision: current, Parents: parents}
			return nil
		}
		var committed safefile.Revision
		if parents != nil {
			committed, err = replaceToolConfigAtRevisionNoCreateAuthorizedTracked(root, rel, accepted, parents, content)
		} else {
			committed, err = replaceToolConfigAtRevisionNoCreateTracked(root, rel, accepted, content)
		}
		if err == nil {
			evidence = MutationEvidence{Path: path, Revision: committed, Parents: parents}
		}
		return err
	})
	return evidence, err
}

// IsLegacyGeneratedYaziThemeConfig reports whether path carries the one exact
// pre-ownership Yazi theme header that the writer can safely migrate. It is
// read-only and uses the same no-follow observer as config adoption.
func IsLegacyGeneratedYaziThemeConfig(path string) (bool, error) {
	content, exists, err := readNativeConfig(path)
	if err != nil || !exists {
		return false, err
	}
	return hasLegacyGeneratedYaziThemeHeader(content), nil
}

func hasLegacyGeneratedYaziThemeHeader(content []byte) bool {
	line := content
	if newline := bytes.IndexByte(line, '\n'); newline >= 0 {
		line = line[:newline]
	}
	line = bytes.TrimSuffix(line, []byte("\r"))
	const prefix = "# Theme: "
	const suffix = " (generated by dotfiles)"
	if !bytes.HasPrefix(line, []byte(prefix)) || !bytes.HasSuffix(line, []byte(suffix)) {
		return false
	}
	_, known := yaziThemePalettes[string(line[len(prefix):len(line)-len(suffix)])]
	return known
}
