package tools

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"testing"
)

func TestWriteYaziConfigWritesAllFiles(t *testing.T) {
	tmpHome := t.TempDir()
	t.Setenv("HOME", tmpHome)

	cfg := YaziConfig{
		Keymap:      "emacs",
		ShowHidden:  true,
		PreviewMode: "auto",
		SortBy:      "natural",
		LineMode:    "size",
		ScrollOff:   5,
	}
	if err := WriteYaziConfig(cfg, "dracula"); err != nil {
		t.Fatalf("WriteYaziConfig returned error: %v", err)
	}

	configDir := filepath.Join(tmpHome, ".config", "yazi")
	for _, name := range []string{"yazi.toml", "keymap.toml", "theme.toml"} {
		if _, err := os.Stat(filepath.Join(configDir, name)); err != nil {
			t.Fatalf("expected %s to be written: %v", name, err)
		}
	}
}

func TestGenerateYaziTheme(t *testing.T) {
	out := GenerateYaziTheme("dracula")

	assertContainsText(t, out, "#ff79c6")
	// yazi 26.x renamed [manager]->[mgr] and [select]->[pick]; the old names are
	// silently ignored, so the generator (and this test) must use the new schema.
	for _, header := range []string{
		"[mgr]",
		"[tabs]",
		"[status]",
		"[input]",
		"[pick]",
		"[tasks]",
		"[which]",
		"[help]",
		"[filetype]",
	} {
		assertContainsText(t, out, header)
	}
	assertNotContainsText(t, out, "[manager]")
	assertNotContainsText(t, out, "[select]")
}

func TestGenerateYaziThemeUnknownFallsBackToMocha(t *testing.T) {
	out := GenerateYaziTheme("unknown-theme")

	assertContainsText(t, out, "#89b4fa")
	assertNotContainsText(t, out, `fg = ""`)
	assertNotContainsText(t, out, `bg = ""`)
}

func TestWriteYaziThemeConfigMigratesExactLegacyOwnershipWithoutSidecar(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("XDG_CONFIG_HOME", "")
	path := filepath.Join(home, ".config", "yazi", "theme.toml")
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatal(err)
	}
	legacy := []byte("# Theme: dracula (generated by dotfiles)\n\n[mgr]\ncwd = { fg = \"#ff79c6\" }\n")
	if err := os.WriteFile(path, legacy, 0o644); err != nil {
		t.Fatal(err)
	}
	want := []byte(GenerateYaziTheme("dracula"))

	if err := writeYaziThemeConfig(path, want); err != nil {
		t.Fatalf("writeYaziThemeConfig: %v", err)
	}
	if got := mustReadOwnershipFile(t, path); !bytes.Equal(got, want) {
		t.Fatalf("migrated Yazi theme differs:\n%s", got)
	}
	assertOwnershipPathAbsent(t, path+".dotfiles.bak")
	assertOwnershipFileMode(t, path, 0o600)

	if err := writeYaziThemeConfig(path, want); err != nil {
		t.Fatalf("idempotent writeYaziThemeConfig: %v", err)
	}
	assertOwnershipPathAbsent(t, path+".dotfiles.bak")
}

func TestWriteYaziThemeConfigRefusesUnprovenLegacyHeaderAndPreservesSidecars(t *testing.T) {
	newContent := []byte(GenerateYaziTheme("dracula"))
	t.Run("unknown legacy theme name", func(t *testing.T) {
		home := t.TempDir()
		t.Setenv("HOME", home)
		t.Setenv("XDG_CONFIG_HOME", "")
		path := filepath.Join(home, ".config", "yazi", "theme.toml")
		if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
			t.Fatal(err)
		}
		original := []byte("# Theme: forged-theme (generated by dotfiles)\nuser = true\n")
		if err := os.WriteFile(path, original, 0o600); err != nil {
			t.Fatal(err)
		}
		err := writeYaziThemeConfig(path, newContent)
		if !errors.Is(err, ErrUnmanagedConfig) {
			t.Fatalf("writeYaziThemeConfig error = %v, want ErrUnmanagedConfig", err)
		}
		if got := mustReadOwnershipFile(t, path); !bytes.Equal(got, original) {
			t.Fatalf("unproven Yazi theme changed: %q", got)
		}
		assertOwnershipPathAbsent(t, path+".dotfiles.bak")
	})

	t.Run("occupied unowned sidecar", func(t *testing.T) {
		home := t.TempDir()
		t.Setenv("HOME", home)
		t.Setenv("XDG_CONFIG_HOME", "")
		path := filepath.Join(home, ".config", "yazi", "theme.toml")
		if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
			t.Fatal(err)
		}
		legacy := []byte("# Theme: dracula (generated by dotfiles)\nlegacy = true\n")
		if err := os.WriteFile(path, legacy, 0o600); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path+".dotfiles.bak", []byte("occupied\n"), 0o600); err != nil {
			t.Fatal(err)
		}
		if err := writeYaziThemeConfig(path, newContent); err != nil {
			t.Fatalf("writeYaziThemeConfig: %v", err)
		}
		if got := mustReadOwnershipFile(t, path); !bytes.Equal(got, newContent) {
			t.Fatalf("legacy Yazi theme was not migrated: %q", got)
		}
		if got := mustReadOwnershipFile(t, path+".dotfiles.bak"); string(got) != "occupied\n" {
			t.Fatalf("unowned sidecar changed: %q", got)
		}
	})
}

func TestWriteYaziConfigPreflightsWholeSetBeforeChangingEarlierFiles(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("XDG_CONFIG_HOME", "")
	dir := filepath.Join(home, ".config", "yazi")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		t.Fatal(err)
	}
	yaziPath := filepath.Join(dir, "yazi.toml")
	original := []byte(GenerateYaziConfig(YaziConfig{SortBy: "natural"}, "nord"))
	if err := os.WriteFile(yaziPath, original, 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "theme.toml"), []byte("# user-owned theme\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := WriteYaziConfig(YaziConfig{SortBy: "size"}, "dracula"); !errors.Is(err, ErrUnmanagedConfig) {
		t.Fatalf("WriteYaziConfig error = %v, want ErrUnmanagedConfig", err)
	}
	if got := mustReadOwnershipFile(t, yaziPath); !bytes.Equal(got, original) {
		t.Fatalf("yazi.toml changed before later theme ownership failure: %q", got)
	}
	assertOwnershipPathAbsent(t, filepath.Join(dir, "keymap.toml"))
}

func TestWriteYaziConfigReportsOnlyDefinitelyCommittedPartialTargets(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("XDG_CONFIG_HOME", "")
	wantErr := errors.New("injected second-target failure")
	calls := 0
	_, err := writeYaziConfigWithWriters(YaziConfig{}, "dracula", func(path string, _ []byte) (MutationEvidence, error) {
		calls++
		if calls == 2 {
			return MutationEvidence{}, wantErr
		}
		return MutationEvidence{Path: path}, nil
	}, func(string, []byte) (MutationEvidence, error) {
		t.Fatal("theme writer ran after second-target failure")
		return MutationEvidence{}, nil
	})
	if !errors.Is(err, wantErr) {
		t.Fatalf("writeYaziConfigWithWriters error = %v", err)
	}
	var partial interface{ CommittedEvidence() []MutationEvidence }
	if !errors.As(err, &partial) {
		t.Fatalf("partial write error did not expose committed targets: %T", err)
	}
	want := filepath.Join(home, ".config", "yazi", "yazi.toml")
	if got := partial.CommittedEvidence(); len(got) != 1 || got[0].Path != want {
		t.Fatalf("committed targets = %v, want only %s", got, want)
	}
}

func TestGenerateYaziConfigPreviewModeAffectsOutput(t *testing.T) {
	cfg := YaziConfig{
		SortBy:    "natural",
		LineMode:  "size",
		ScrollOff: 5,
	}

	auto := GenerateYaziConfig(cfg, "catppuccin-mocha")
	cfg.PreviewMode = "never"
	never := GenerateYaziConfig(cfg, "catppuccin-mocha")

	if auto == never {
		t.Fatal("PreviewMode=never produced the same yazi.toml as auto")
	}
	assertContainsText(t, auto, "image_delay = 30")
	assertNotContainsText(t, auto, "previewers = []")
	assertContainsText(t, never, "PreviewMode=never")
	assertContainsText(t, never, "[plugin]")
	assertContainsText(t, never, "previewers = []")
}

func TestGenerateYaziConfigDefaultsEmptyLineMode(t *testing.T) {
	out := GenerateYaziConfig(YaziConfig{}, "catppuccin-mocha")

	assertContainsText(t, out, `linemode = "size"`)
	assertNotContainsText(t, out, `linemode = ""`)
}
