package tools

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/tekierz/dotfiles/internal/pkg"
)

// ZshConfig holds Zsh configuration settings.
type ZshConfig struct {
	PromptStyle     string          // "p10k", "starship", "pure", "minimal"
	Plugins         []string        // List of plugins to source
	Aliases         map[string]bool // Aliases to enable
	HistorySize     int
	AutoCD          bool
	SyntaxHighlight bool
	Autosuggestions bool

	HistoryIgnoreDups bool // setopt HIST_IGNORE_DUPS
	Correction        bool // setopt CORRECT
	CompletionMenu    bool // zstyle menu select
}

// ZshTool represents the Zsh shell.
type ZshTool struct {
	BaseTool
}

// NewZshTool creates a new Zsh tool.
func NewZshTool() *ZshTool {
	home, _ := os.UserHomeDir()
	return &ZshTool{
		BaseTool: BaseTool{
			id:          "zsh",
			name:        "Zsh",
			description: "Z shell with plugins and customization",
			icon:        "",
			category:    CategoryShell,
			packages: map[pkg.Platform][]string{
				pkg.PlatformMacOS:  {"zsh", "zsh-autosuggestions", "zsh-syntax-highlighting", "zsh-completions"},
				pkg.PlatformArch:   {"zsh", "zsh-autosuggestions", "zsh-syntax-highlighting", "zsh-completions"},
				pkg.PlatformDebian: {"zsh", "zsh-autosuggestions", "zsh-syntax-highlighting"},
			},
			configPaths: []string{
				filepath.Join(home, ".zshrc"),
				filepath.Join(home, ".zshenv"),
			},
			// UI metadata
			uiGroup:        UIGroupNone,
			configScreen:   11, // ScreenConfigZsh
			defaultEnabled: true,
		},
	}
}

// GenerateZshConfig builds the .zshrc content.
func GenerateZshConfig(cfg ZshConfig, theme string) string {
	var sb strings.Builder
	platform := pkg.DetectPlatform()

	// Header
	sb.WriteString("# Generated by dotfiles TUI\n")
	sb.WriteString(fmt.Sprintf("# Theme: %s\n\n", theme))

	// History settings
	sb.WriteString("# History\n")
	sb.WriteString(fmt.Sprintf("HISTSIZE=%d\n", cfg.HistorySize))
	sb.WriteString(fmt.Sprintf("SAVEHIST=%d\n", cfg.HistorySize))
	sb.WriteString("HISTFILE=~/.zsh_history\n")
	if cfg.HistoryIgnoreDups {
		sb.WriteString("setopt HIST_IGNORE_DUPS\n")
	}
	sb.WriteString("setopt HIST_IGNORE_SPACE\n")
	sb.WriteString("setopt SHARE_HISTORY\n\n")

	// Auto CD
	if cfg.AutoCD {
		sb.WriteString("# Auto CD\n")
		sb.WriteString("setopt AUTO_CD\n\n")
	}

	// Auto correction
	if cfg.Correction {
		sb.WriteString("# Correction\n")
		sb.WriteString("setopt CORRECT\n\n")
	}

	// Completion
	sb.WriteString("# Completion\n")
	sb.WriteString("autoload -Uz compinit && compinit\n")
	if cfg.CompletionMenu {
		sb.WriteString("zstyle ':completion:*' menu select\n")
	}
	sb.WriteString("zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'\n\n")

	// PATH additions
	sb.WriteString("# PATH\n")
	sb.WriteString("export PATH=\"$HOME/.local/bin:$PATH\"\n\n")

	// Plugin sources based on platform
	writeZshPlugins(&sb, cfg, platform)

	// Aliases
	writeZshAliases(&sb, cfg)

	// Modern tool aliases (if available)
	sb.WriteString("# Modern tool aliases (if installed)\n")
	sb.WriteString("command -v eza &>/dev/null && alias ls='eza --icons'\n")
	sb.WriteString("command -v bat &>/dev/null && alias cat='bat --paging=never'\n")
	sb.WriteString("command -v zoxide &>/dev/null && eval \"$(zoxide init zsh)\"\n\n")

	// Prompt configuration
	writeZshPrompt(&sb, cfg)

	return sb.String()
}

// zshPluginSource returns the line that sources the named zsh plugin (e.g.
// "zsh-syntax-highlighting") for the given platform: the plugin lives in a
// like-named directory as "<name>.zsh". An empty string means no known path.
func zshPluginSource(platform pkg.Platform, name string) string {
	switch platform {
	case pkg.PlatformMacOS:
		return fmt.Sprintf("source $(brew --prefix)/share/%s/%s.zsh 2>/dev/null\n", name, name)
	case pkg.PlatformArch:
		return fmt.Sprintf("source /usr/share/zsh/plugins/%s/%s.zsh 2>/dev/null\n", name, name)
	case pkg.PlatformDebian, pkg.PlatformPi:
		return fmt.Sprintf("source /usr/share/%s/%s.zsh 2>/dev/null\n", name, name)
	case pkg.PlatformUnknown:
		return "" // No plugin source path available for unknown platforms.
	}
	return ""
}

// writeZshPlugins appends the syntax-highlighting and autosuggestion plugin
// source lines for the detected platform.
func writeZshPlugins(sb *strings.Builder, cfg ZshConfig, platform pkg.Platform) {
	sb.WriteString("# Plugins\n")
	if cfg.SyntaxHighlight {
		sb.WriteString(zshPluginSource(platform, "zsh-syntax-highlighting"))
	}
	if cfg.Autosuggestions {
		sb.WriteString(zshPluginSource(platform, "zsh-autosuggestions"))
	}
	sb.WriteString("\n")
}

// writeZshAliases appends the user-selected shell aliases.
func writeZshAliases(sb *strings.Builder, cfg ZshConfig) {
	sb.WriteString("# Aliases\n")
	for _, a := range []struct{ key, line string }{
		{"ll", "alias ll='ls -la'\n"},
		{"la", "alias la='ls -A'\n"},
		{"gs", "alias gs='git status'\n"},
		{"gp", "alias gp='git push'\n"},
		{"gc", "alias gc='git commit'\n"},
	} {
		if cfg.Aliases[a.key] {
			sb.WriteString(a.line)
		}
	}
	if cfg.Aliases["docker"] {
		sb.WriteString("alias d='docker'\n")
		sb.WriteString("alias dc='docker compose'\n")
	}
	sb.WriteString("\n")
}

// writeZshPrompt appends the prompt initialization for the configured style.
func writeZshPrompt(sb *strings.Builder, cfg ZshConfig) {
	sb.WriteString("# Prompt\n")
	switch cfg.PromptStyle {
	case "starship":
		sb.WriteString("command -v starship &>/dev/null && eval \"$(starship init zsh)\"\n")
	case "p10k":
		sb.WriteString("# Powerlevel10k instant prompt\n")
		sb.WriteString("if [[ -r \"${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh\" ]]; then\n")
		sb.WriteString("  source \"${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh\"\n")
		sb.WriteString("fi\n")
		sb.WriteString("[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh\n")
	case "pure":
		sb.WriteString("autoload -U promptinit; promptinit\n")
		sb.WriteString("prompt pure 2>/dev/null || PROMPT='%~ > '\n")
	case "minimal":
		sb.WriteString("PROMPT='%~ > '\n")
	}
}

// WriteZshConfig writes the .zshrc file to disk.
func WriteZshConfig(cfg ZshConfig, theme string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}

	configPath := filepath.Join(home, ".zshrc")
	content := GenerateZshConfig(cfg, theme)
	return writeToolConfig(configPath, []byte(content))
}
