package tools

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/tekierz/dotfiles/internal/pkg"
)

// ZshConfig holds Zsh configuration settings
type ZshConfig struct {
	PromptStyle     string          // "p10k", "starship", "pure", "minimal"
	Plugins         []string        // List of plugins to source
	Aliases         map[string]bool // Aliases to enable
	HistorySize     int
	AutoCD          bool
	SyntaxHighlight bool
	Autosuggestions bool
}

// ZshTool represents the Zsh shell
type ZshTool struct {
	BaseTool
}

// NewZshTool creates a new Zsh tool
func NewZshTool() *ZshTool {
	home, _ := os.UserHomeDir()
	return &ZshTool{
		BaseTool: BaseTool{
			id:          "zsh",
			name:        "Zsh",
			description: "Z shell with plugins and customization",
			icon:        "",
			category:    CategoryShell,
			packages: map[pkg.Platform][]string{
				pkg.PlatformMacOS:  {"zsh", "zsh-autosuggestions", "zsh-syntax-highlighting", "zsh-completions"},
				pkg.PlatformArch:   {"zsh", "zsh-autosuggestions", "zsh-syntax-highlighting", "zsh-completions"},
				pkg.PlatformDebian: {"zsh", "zsh-autosuggestions", "zsh-syntax-highlighting"},
			},
			configPaths: []string{
				filepath.Join(home, ".zshrc"),
				filepath.Join(home, ".zshenv"),
			},
			// UI metadata
			uiGroup:        UIGroupNone,
			configScreen:   11, // ScreenConfigZsh
			defaultEnabled: true,
		},
	}
}

// GenerateZshConfig builds the .zshrc content
func GenerateZshConfig(cfg ZshConfig, theme string) string {
	var sb strings.Builder
	platform := pkg.DetectPlatform()

	// Header
	sb.WriteString("# Generated by dotfiles TUI\n")
	sb.WriteString(fmt.Sprintf("# Theme: %s\n\n", theme))

	// History settings
	sb.WriteString("# History\n")
	sb.WriteString(fmt.Sprintf("HISTSIZE=%d\n", cfg.HistorySize))
	sb.WriteString(fmt.Sprintf("SAVEHIST=%d\n", cfg.HistorySize))
	sb.WriteString("HISTFILE=~/.zsh_history\n")
	sb.WriteString("setopt HIST_IGNORE_DUPS\n")
	sb.WriteString("setopt HIST_IGNORE_SPACE\n")
	sb.WriteString("setopt SHARE_HISTORY\n\n")

	// Auto CD
	if cfg.AutoCD {
		sb.WriteString("# Auto CD\n")
		sb.WriteString("setopt AUTO_CD\n\n")
	}

	// Completion
	sb.WriteString("# Completion\n")
	sb.WriteString("autoload -Uz compinit && compinit\n")
	sb.WriteString("zstyle ':completion:*' menu select\n")
	sb.WriteString("zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'\n\n")

	// PATH additions
	sb.WriteString("# PATH\n")
	sb.WriteString("export PATH=\"$HOME/.local/bin:$PATH\"\n\n")

	// Plugin sources based on platform
	sb.WriteString("# Plugins\n")
	if cfg.SyntaxHighlight {
		switch platform {
		case pkg.PlatformMacOS:
			sb.WriteString("source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null\n")
		case pkg.PlatformArch:
			sb.WriteString("source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null\n")
		case pkg.PlatformDebian:
			sb.WriteString("source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null\n")
		}
	}
	if cfg.Autosuggestions {
		switch platform {
		case pkg.PlatformMacOS:
			sb.WriteString("source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh 2>/dev/null\n")
		case pkg.PlatformArch:
			sb.WriteString("source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh 2>/dev/null\n")
		case pkg.PlatformDebian:
			sb.WriteString("source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh 2>/dev/null\n")
		}
	}
	sb.WriteString("\n")

	// Aliases
	sb.WriteString("# Aliases\n")
	if cfg.Aliases["ll"] {
		sb.WriteString("alias ll='ls -la'\n")
	}
	if cfg.Aliases["la"] {
		sb.WriteString("alias la='ls -A'\n")
	}
	if cfg.Aliases["gs"] {
		sb.WriteString("alias gs='git status'\n")
	}
	if cfg.Aliases["gp"] {
		sb.WriteString("alias gp='git push'\n")
	}
	if cfg.Aliases["gc"] {
		sb.WriteString("alias gc='git commit'\n")
	}
	if cfg.Aliases["docker"] {
		sb.WriteString("alias d='docker'\n")
		sb.WriteString("alias dc='docker compose'\n")
	}
	sb.WriteString("\n")

	// Modern tool aliases (if available)
	sb.WriteString("# Modern tool aliases (if installed)\n")
	sb.WriteString("command -v eza &>/dev/null && alias ls='eza --icons'\n")
	sb.WriteString("command -v bat &>/dev/null && alias cat='bat --paging=never'\n")
	sb.WriteString("command -v zoxide &>/dev/null && eval \"$(zoxide init zsh)\"\n\n")

	// Prompt configuration
	sb.WriteString("# Prompt\n")
	switch cfg.PromptStyle {
	case "starship":
		sb.WriteString("command -v starship &>/dev/null && eval \"$(starship init zsh)\"\n")
	case "p10k":
		sb.WriteString("# Powerlevel10k instant prompt\n")
		sb.WriteString("if [[ -r \"${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh\" ]]; then\n")
		sb.WriteString("  source \"${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh\"\n")
		sb.WriteString("fi\n")
		sb.WriteString("[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh\n")
	case "pure":
		sb.WriteString("autoload -U promptinit; promptinit\n")
		sb.WriteString("prompt pure 2>/dev/null || PROMPT='%~ > '\n")
	case "minimal":
		sb.WriteString("PROMPT='%~ > '\n")
	}

	return sb.String()
}

// WriteZshConfig writes the .zshrc file to disk
func WriteZshConfig(cfg ZshConfig, theme string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}

	configPath := filepath.Join(home, ".zshrc")
	content := GenerateZshConfig(cfg, theme)

	if err := os.WriteFile(configPath, []byte(content), 0600); err != nil {
		return fmt.Errorf("failed to write .zshrc: %w", err)
	}

	return nil
}

// GenerateConfig implements Tool interface (uses defaults)
func (t *ZshTool) GenerateConfig(theme string) string {
	cfg := ZshConfig{
		PromptStyle: "p10k",
		Plugins: []string{
			"zsh-autosuggestions",
			"zsh-syntax-highlighting",
		},
		Aliases: map[string]bool{
			"ll":     true,
			"la":     true,
			"gs":     true,
			"gp":     true,
			"gc":     true,
			"docker": true,
		},
		HistorySize:     10000,
		AutoCD:          true,
		SyntaxHighlight: true,
		Autosuggestions: true,
	}
	return GenerateZshConfig(cfg, theme)
}

// ApplyConfig implements Tool interface (uses defaults)
func (t *ZshTool) ApplyConfig(theme string) error {
	cfg := ZshConfig{
		PromptStyle: "p10k",
		Plugins: []string{
			"zsh-autosuggestions",
			"zsh-syntax-highlighting",
		},
		Aliases: map[string]bool{
			"ll":     true,
			"la":     true,
			"gs":     true,
			"gp":     true,
			"gc":     true,
			"docker": true,
		},
		HistorySize:     10000,
		AutoCD:          true,
		SyntaxHighlight: true,
		Autosuggestions: true,
	}
	return WriteZshConfig(cfg, theme)
}
