package tools

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/tekierz/dotfiles/internal/config"
	"github.com/tekierz/dotfiles/internal/pkg"
	"github.com/tekierz/dotfiles/internal/safefile"
)

// ZshConfig holds Zsh configuration settings
type ZshConfig struct {
	PromptStyle     string          // "p10k", "starship", "pure", "minimal"
	Plugins         []string        // List of plugins to source
	Aliases         map[string]bool // Aliases to enable
	HistorySize     int
	AutoCD          bool
	SyntaxHighlight bool
	Autosuggestions bool

	HistoryIgnoreDups bool // setopt HIST_IGNORE_DUPS
	Correction        bool // setopt CORRECT
	CompletionMenu    bool // zstyle menu select
}

// ZshTool represents the Zsh shell
type ZshTool struct {
	BaseTool
}

const (
	zshManagedStart = "# >>> dotfiles zsh (managed)"
	zshManagedEnd   = "# <<< dotfiles zsh (managed)"
)

// NewZshTool creates a new Zsh tool
func NewZshTool() *ZshTool {
	home, _ := os.UserHomeDir()
	return &ZshTool{
		BaseTool: BaseTool{
			id:          "zsh",
			name:        "Zsh",
			description: "Z shell with plugins and customization",
			icon:        "",
			category:    CategoryShell,
			packages: map[pkg.Platform][]string{
				pkg.PlatformMacOS:  {"zsh", "zsh-autosuggestions", "zsh-syntax-highlighting", "zsh-completions", "powerlevel10k"},
				pkg.PlatformArch:   {"zsh", "zsh-autosuggestions", "zsh-syntax-highlighting", "zsh-completions", "zsh-theme-powerlevel10k"},
				pkg.PlatformDebian: {"zsh", "zsh-autosuggestions", "zsh-syntax-highlighting"},
			},
			configPaths: []string{
				filepath.Join(home, ".zshrc"),
				filepath.Join(home, ".zshenv"),
			},
			// UI metadata
			uiGroup:        UIGroupNone,
			configScreen:   11, // ScreenConfigZsh
			defaultEnabled: true,
		},
	}
}

// GenerateZshConfig builds the .zshrc content
func GenerateZshConfig(cfg ZshConfig, theme string) string {
	var sb strings.Builder

	// Header
	sb.WriteString("# Generated by dotfiles TUI\n")
	sb.WriteString(fmt.Sprintf("# Theme: %s\n\n", theme))

	// History settings
	sb.WriteString("# History\n")
	sb.WriteString(fmt.Sprintf("HISTSIZE=%d\n", cfg.HistorySize))
	sb.WriteString(fmt.Sprintf("SAVEHIST=%d\n", cfg.HistorySize))
	sb.WriteString("HISTFILE=~/.zsh_history\n")
	if cfg.HistoryIgnoreDups {
		sb.WriteString("setopt HIST_IGNORE_DUPS\n")
	}
	sb.WriteString("setopt HIST_IGNORE_SPACE\n")
	sb.WriteString("setopt SHARE_HISTORY\n\n")

	// Auto CD
	if cfg.AutoCD {
		sb.WriteString("# Auto CD\n")
		sb.WriteString("setopt AUTO_CD\n\n")
	}

	// Auto correction
	if cfg.Correction {
		sb.WriteString("# Correction\n")
		sb.WriteString("setopt CORRECT\n\n")
	}

	if zshPluginEnabled(cfg, "zsh-completions", false) {
		sb.WriteString("# Extra completions\n")
		sb.WriteString("if command -v brew &>/dev/null; then\n")
		sb.WriteString("  FPATH=\"$(brew --prefix)/share/zsh-completions:$FPATH\"\n")
		sb.WriteString("fi\n")
		sb.WriteString("[[ -d /usr/share/zsh/site-functions ]] && FPATH=\"/usr/share/zsh/site-functions:$FPATH\"\n")
		sb.WriteString("[[ -d /usr/local/share/zsh/site-functions ]] && FPATH=\"/usr/local/share/zsh/site-functions:$FPATH\"\n\n")
	}

	// Completion
	sb.WriteString("# Completion\n")
	sb.WriteString("autoload -Uz compinit && compinit\n")
	if cfg.CompletionMenu {
		sb.WriteString("zstyle ':completion:*' menu select\n")
	}
	sb.WriteString("zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'\n\n")

	// PATH additions
	sb.WriteString("# PATH\n")
	sb.WriteString("export PATH=\"$HOME/.local/bin:$PATH\"\n\n")

	// Plugin sources based on platform
	sb.WriteString("# Plugins\n")
	writeZshSourceFirstFunction(&sb)
	if zshPluginEnabled(cfg, "zsh-autosuggestions", cfg.Autosuggestions) {
		writeZshSourceFirst(&sb,
			"$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh",
			"${HOMEBREW_PREFIX:-$(brew --prefix 2>/dev/null)}/share/zsh-autosuggestions/zsh-autosuggestions.zsh",
			"/usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh",
			"/usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh",
			"/opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh",
			"/usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh",
		)
	}
	if zshPluginEnabled(cfg, "zsh-syntax-highlighting", cfg.SyntaxHighlight) {
		writeZshSourceFirst(&sb,
			"$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh",
			"${HOMEBREW_PREFIX:-$(brew --prefix 2>/dev/null)}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh",
			"/usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh",
			"/usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh",
			"/opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh",
			"/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh",
		)
	}
	sb.WriteString("\n")

	// Aliases
	sb.WriteString("# Aliases\n")
	if cfg.Aliases["ll"] {
		sb.WriteString("alias ll='ls -la'\n")
	}
	if cfg.Aliases["la"] {
		sb.WriteString("alias la='ls -A'\n")
	}
	if cfg.Aliases["gs"] {
		sb.WriteString("alias gs='git status'\n")
	}
	if cfg.Aliases["gp"] {
		sb.WriteString("alias gp='git push'\n")
	}
	if cfg.Aliases["gc"] {
		sb.WriteString("alias gc='git commit'\n")
	}
	if cfg.Aliases["docker"] {
		sb.WriteString("command -v docker &>/dev/null && alias d='docker'\n")
		sb.WriteString("command -v docker &>/dev/null && alias dc='docker compose'\n")
	}
	writeSavedAliases(&sb, loadSavedHotkeyAliases())
	sb.WriteString("\n")

	// Modern tool aliases (if available). Each alias is guarded by a
	// command-exists check so it never shadows the real command when the
	// modern replacement is not installed. Matches the documented set
	// (docs/tools.md) and the legacy bash script.
	sb.WriteString("# Modern tool aliases (if installed)\n")
	sb.WriteString("command -v eza &>/dev/null && alias ls='eza --icons'\n")
	sb.WriteString("command -v eza &>/dev/null && alias lt='eza --tree --level=2 --icons'\n")
	sb.WriteString("command -v bat &>/dev/null && alias cat='bat --paging=never'\n")
	// Disk usage tools
	sb.WriteString("command -v duf &>/dev/null && alias df='duf'\n")
	sb.WriteString("command -v dust &>/dev/null && alias du='dust'\n")
	sb.WriteString("command -v ncdu &>/dev/null && alias diskuse='ncdu'\n")
	// Network tools
	sb.WriteString("command -v bandwhich &>/dev/null && alias bandwidth='bandwhich'\n")
	sb.WriteString("command -v gping &>/dev/null && alias ping='gping'\n")
	sb.WriteString("command -v doggo &>/dev/null && alias dig='doggo'\n")
	sb.WriteString("command -v trip &>/dev/null && alias trace='trip'\n")
	// zoxide (smarter cd)
	sb.WriteString("if command -v zoxide &>/dev/null; then\n")
	sb.WriteString("  eval \"$(zoxide init zsh)\"\n")
	sb.WriteString("  alias cd='z'\n")
	sb.WriteString("fi\n\n")

	// fzf configuration written by WriteFzfConfig.
	sb.WriteString("# fzf\n")
	sb.WriteString("[[ -r \"$HOME/.config/fzf/fzf.zsh\" ]] && source \"$HOME/.config/fzf/fzf.zsh\"\n\n")

	// Prompt configuration
	sb.WriteString("# Prompt\n")
	writeZshPrompt(&sb, cfg.PromptStyle)

	return sb.String()
}

func writeZshPrompt(sb *strings.Builder, promptStyle string) {
	switch promptStyle {
	case "starship":
		// Starship is not installed by the tool registry, so fall back to a
		// working minimal prompt when it is absent instead of leaving a bare
		// shell prompt.
		sb.WriteString("if command -v starship &>/dev/null; then\n")
		sb.WriteString("  eval \"$(starship init zsh)\"\n")
		sb.WriteString("else\n")
		sb.WriteString("  PROMPT='%~ > '\n")
		sb.WriteString("fi\n")
	case "p10k":
		sb.WriteString("# Powerlevel10k instant prompt\n")
		sb.WriteString("if [[ -r \"${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh\" ]]; then\n")
		sb.WriteString("  source \"${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh\"\n")
		sb.WriteString("fi\n")
		sb.WriteString("if ")
		writeZshSourceFirstCall(sb, []string{
			"${HOMEBREW_PREFIX:-$(brew --prefix 2>/dev/null)}/share/powerlevel10k/powerlevel10k.zsh-theme",
			"/opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme",
			"/usr/local/share/powerlevel10k/powerlevel10k.zsh-theme",
			"/usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme",
			"/usr/share/powerlevel10k/powerlevel10k.zsh-theme",
			"$HOME/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme",
			"$HOME/.powerlevel10k/powerlevel10k.zsh-theme",
			"$HOME/powerlevel10k/powerlevel10k.zsh-theme",
		}, "; then\n")
		sb.WriteString("  [[ -f \"$HOME/.p10k.zsh\" ]] && source \"$HOME/.p10k.zsh\"\n")
		sb.WriteString("else\n")
		sb.WriteString("  PROMPT='%~ > '\n")
		sb.WriteString("fi\n")
	case "pure":
		sb.WriteString("autoload -U promptinit; promptinit\n")
		sb.WriteString("prompt pure 2>/dev/null || PROMPT='%~ > '\n")
	case "minimal":
		sb.WriteString("PROMPT='%~ > '\n")
	}
}

func zshPluginEnabled(cfg ZshConfig, plugin string, fallback bool) bool {
	switch plugin {
	case "zsh-autosuggestions":
		return cfg.Autosuggestions
	case "zsh-syntax-highlighting":
		return cfg.SyntaxHighlight
	}

	listed := false
	for _, selected := range cfg.Plugins {
		if selected == plugin {
			listed = true
			break
		}
	}
	if len(cfg.Plugins) == 0 {
		return fallback
	}
	return listed
}

func writeZshSourceFirstFunction(sb *strings.Builder) {
	sb.WriteString("_dotfiles_source_first() {\n")
	sb.WriteString("  local _dotfiles_source_path\n")
	sb.WriteString("  for _dotfiles_source_path in \"$@\"; do\n")
	sb.WriteString("    if [[ -r \"$_dotfiles_source_path\" ]]; then\n")
	sb.WriteString("      source \"$_dotfiles_source_path\"\n")
	sb.WriteString("      return 0\n")
	sb.WriteString("    fi\n")
	sb.WriteString("  done\n")
	sb.WriteString("  return 1\n")
	sb.WriteString("}\n\n")
}

func writeZshSourceFirst(sb *strings.Builder, paths ...string) {
	writeZshSourceFirstCall(sb, paths, "\n")
}

func writeZshSourceFirstCall(sb *strings.Builder, paths []string, terminator string) {
	sb.WriteString("_dotfiles_source_first")
	for _, path := range paths {
		sb.WriteString(" \\\n")
		sb.WriteString("  ")
		sb.WriteString(zshPathRef(path))
	}
	sb.WriteString(terminator)
}

func zshPathRef(path string) string {
	if strings.HasPrefix(path, "$HOME/") || strings.HasPrefix(path, "${") {
		return `"` + path + `"`
	}
	return shellQuote(path)
}

func loadSavedHotkeyAliases() map[string]string {
	username := "default"
	if globalCfg, err := config.LoadGlobalConfig(); err == nil && globalCfg != nil && globalCfg.ActiveUser != "" {
		username = globalCfg.ActiveUser
	}

	hotkeysCfg, err := config.LoadHotkeysConfig()
	if err != nil || hotkeysCfg == nil {
		return nil
	}
	userHotkeys := hotkeysCfg.GetUserHotkeys(username)
	if userHotkeys == nil {
		return nil
	}
	return userHotkeys.Aliases
}

func writeSavedAliases(sb *strings.Builder, aliases map[string]string) {
	if len(aliases) == 0 {
		return
	}

	names := make([]string, 0, len(aliases))
	for name := range aliases {
		names = append(names, name)
	}
	sort.Strings(names)

	sb.WriteString("\n# Saved hotkey aliases\n")
	for _, name := range names {
		command := aliases[name]
		if !validAliasName(name) || strings.ContainsAny(command, "\x00\n\r") {
			continue
		}
		sb.WriteString(fmt.Sprintf("alias -- %s\n", shellQuote(name+"="+command)))
	}
}

func validAliasName(name string) bool {
	if strings.TrimSpace(name) != name || name == "" {
		return false
	}
	if strings.HasPrefix(name, "-") {
		return false
	}
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z':
		case r >= 'A' && r <= 'Z':
		case r >= '0' && r <= '9':
		case r == '_' || r == '-' || r == '.':
		default:
			return false
		}
	}
	return true
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}

// WriteZshConfig writes the .zshrc file to disk
func WriteZshConfig(cfg ZshConfig, theme string) error {
	_, err := WriteZshConfigTracked(cfg, theme)
	return err
}

func WriteZshConfigTracked(cfg ZshConfig, theme string) (MutationEvidence, error) {
	return writeZshConfigAtRevisionTracked(cfg, theme, nil)
}

// WriteZshConfigAtRevisionTracked applies a plan-accepted Zsh revision.
func WriteZshConfigAtRevisionTracked(cfg ZshConfig, theme string, accepted safefile.Revision) (MutationEvidence, error) {
	if !accepted.Tracked() {
		return MutationEvidence{}, fmt.Errorf("%w: accepted Zsh revision is untracked", safefile.ErrRevisionChanged)
	}
	return writeZshConfigAtRevisionTracked(cfg, theme, &accepted)
}

func writeZshConfigAtRevisionTracked(cfg ZshConfig, theme string, accepted *safefile.Revision) (MutationEvidence, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return MutationEvidence{}, fmt.Errorf("failed to get home directory: %w", err)
	}

	configPath := filepath.Join(home, ".zshrc")
	managed := []byte(wrapZshManagedSection(GenerateZshConfig(cfg, theme)))
	var evidence MutationEvidence
	err = withToolConfigLock(configPath, func(root, rel string) error {
		existing, revision, err := readToolConfig(root, rel)
		if err != nil {
			return err
		}
		if accepted != nil && revision != *accepted {
			return fmt.Errorf("%w: Zsh config changed after plan acceptance", safefile.ErrRevisionChanged)
		}
		content := managed
		if revision.Exists() {
			content, err = mergeZshManagedSection(existing, managed)
			if err != nil {
				return err
			}
		}
		expected := revision
		if accepted != nil {
			expected = *accepted
		}
		committed, err := replaceToolConfigAtRevisionTracked(root, rel, expected, content)
		if err == nil {
			evidence = MutationEvidence{Path: configPath, Revision: committed}
		}
		return err
	})
	return evidence, err
}

func wrapZshManagedSection(content string) string {
	return zshManagedStart + "\n" + strings.TrimRight(content, "\n") + "\n" + zshManagedEnd + "\n"
}

func mergeZshManagedSection(existing, managed []byte) ([]byte, error) {
	current := string(existing)
	starts := exactZshMarkerLines(current, zshManagedStart)
	ends := exactZshMarkerLines(current, zshManagedEnd)

	switch {
	case len(starts) == 1 && len(ends) == 1 && starts[0].start < ends[0].start:
		return []byte(current[:starts[0].start] + string(managed) + current[ends[0].end:]), nil
	case len(starts) != 0 || len(ends) != 0:
		return nil, fmt.Errorf("refusing to update .zshrc with ambiguous or incomplete dotfiles managed sections (%d start, %d end)", len(starts), len(ends))
	}

	if isLegacyGeneratedZshConfig(current) {
		tail, err := legacyGeneratedZshTail(current)
		if err != nil {
			return nil, err
		}
		migrated := append([]byte(nil), managed...)
		migrated = append(migrated, tail...)
		return migrated, nil
	}

	if strings.TrimSpace(current) == "" {
		return managed, nil
	}
	separator := "\n\n"
	if strings.HasSuffix(current, "\n\n") {
		separator = ""
	} else if strings.HasSuffix(current, "\n") {
		separator = "\n"
	}
	return []byte(current + separator + string(managed)), nil
}

type zshLineSpan struct {
	start int
	end   int
}

// exactZshMarkerLines returns only markers that occupy an entire logical line.
// Marker text inside a quoted string, comment, or shell command is user content
// and must never grant ownership of the surrounding bytes. CRLF is accepted so
// a config copied from another platform can still be migrated safely.
func exactZshMarkerLines(content, marker string) []zshLineSpan {
	var spans []zshLineSpan
	for start := 0; start < len(content); {
		relativeEnd := strings.IndexByte(content[start:], '\n')
		end := len(content)
		contentEnd := end
		if relativeEnd >= 0 {
			contentEnd = start + relativeEnd
			end = contentEnd + 1
		}
		logicalEnd := contentEnd
		if logicalEnd > start && content[logicalEnd-1] == '\r' {
			logicalEnd--
		}
		if content[start:logicalEnd] == marker {
			spans = append(spans, zshLineSpan{start: start, end: end})
		}
		start = end
	}
	return spans
}

// legacyGeneratedZshTail recognizes the exact prompt suffixes emitted by the
// previous whole-file generator and returns only bytes appended after that
// generated region. If the legacy shape is unknown, migration fails closed:
// guessing where generated content ends would risk deleting user additions.
func legacyGeneratedZshTail(content string) ([]byte, error) {
	trimmed := strings.TrimLeft(content, "\ufeff \t\r\n")
	lineEnding := "\n"
	promptMarker := "# Prompt\n"
	if strings.HasPrefix(trimmed, "# Generated by dotfiles TUI\r\n") {
		lineEnding = "\r\n"
		promptMarker = "# Prompt\r\n"
	}
	promptIndex := strings.Index(trimmed, promptMarker)
	if promptIndex < 0 {
		return nil, fmt.Errorf("refusing to migrate legacy generated .zshrc with no recognizable prompt section")
	}
	remainder := trimmed[promptIndex+len(promptMarker):]
	for _, style := range []string{"p10k", "starship", "pure", "minimal"} {
		var prompt strings.Builder
		writeZshPrompt(&prompt, style)
		body := prompt.String()
		if lineEnding == "\r\n" {
			body = strings.ReplaceAll(body, "\n", "\r\n")
		}
		if strings.HasPrefix(remainder, body) {
			return []byte(remainder[len(body):]), nil
		}
	}
	return nil, fmt.Errorf("refusing to migrate legacy generated .zshrc with an unrecognized prompt section")
}

func isLegacyGeneratedZshConfig(content string) bool {
	trimmed := strings.TrimLeft(content, "\ufeff \t\r\n")
	return strings.HasPrefix(trimmed, "# Generated by dotfiles TUI\n") ||
		strings.HasPrefix(trimmed, "# Generated by dotfiles TUI\r\n")
}
