package ui

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
	"testing"
	"time"

	"github.com/tekierz/dotfiles/internal/config"
	"github.com/tekierz/dotfiles/internal/operation"
	"github.com/tekierz/dotfiles/internal/pkg"
	"github.com/tekierz/dotfiles/internal/tools"
)

func newLazyGitPlanApp(t *testing.T, home string, installed map[string]bool) (*App, toolInstallRuntime) {
	t.Helper()
	app := NewApp(true)
	seedTypedReadyInstallCache(t, app, installed)
	app.manageInstalledReady = true
	app.installCacheLoading = false
	app.manageInstalled = installed
	app.deepDiveConfig.CLITools["lazygit"] = true
	return app, registryRuntime(pkg.PlatformMacOS, installed)
}

func TestLazyGitPlanTargetPrecedence(t *testing.T) {
	home := withTempHome(t)
	t.Setenv("LG_CONFIG_FILE", "")
	t.Run("CONFIG_DIR", func(t *testing.T) {
		dir := filepath.Join(home, "config-dir")
		t.Setenv("CONFIG_DIR", dir)
		t.Setenv("XDG_CONFIG_HOME", filepath.Join(home, "xdg"))
		got, reason := lazyGitPlanTarget(home)
		if got != "config-dir/config.yml" || reason != "" {
			t.Fatalf("target=%q reason=%q", got, reason)
		}
	})
	t.Run("XDG", func(t *testing.T) {
		t.Setenv("CONFIG_DIR", "")
		t.Setenv("XDG_CONFIG_HOME", filepath.Join(home, "xdg"))
		got, reason := lazyGitPlanTarget(home)
		if got != "xdg/lazygit/config.yml" || reason != "" {
			t.Fatalf("target=%q reason=%q", got, reason)
		}
	})
	t.Run("platform default", func(t *testing.T) {
		t.Setenv("CONFIG_DIR", "")
		t.Setenv("XDG_CONFIG_HOME", "")
		got, reason := lazyGitPlanTarget(home)
		want := ".config/lazygit/config.yml"
		if runtime.GOOS == "darwin" {
			want = "Library/Application Support/lazygit/config.yml"
		}
		if got != want || reason != "" {
			t.Fatalf("target=%q want=%q reason=%q", got, want, reason)
		}
	})
}

func TestLazyGitPlannerBlocksUnsafeNativeSourcesWithExactReason(t *testing.T) {
	tests := []struct {
		name string
		body []byte
		want string
	}{
		{"arbitrary", []byte("gui:\n  mouseEvents: false\ncustom: keep\n"), "arbitrary native LazyGit YAML"},
		{"legacy generated", []byte("# Generated by dotfiles TUI\ngui:\n  mouseEvents: true\n"), "arbitrary native LazyGit YAML"},
		{"custom pager", []byte("git:\n  pagers:\n    - pager: less\n"), "custom LazyGit pagers"},
		{"malformed", []byte("gui: [\n"), "could not be imported safely"},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			home := withTempHome(t)
			dir := filepath.Join(home, ".config", "lazygit")
			t.Setenv("CONFIG_DIR", dir)
			t.Setenv("LG_CONFIG_FILE", "")
			if err := os.MkdirAll(dir, 0o700); err != nil {
				t.Fatal(err)
			}
			path := filepath.Join(dir, "config.yml")
			if err := os.WriteFile(path, tc.body, 0o600); err != nil {
				t.Fatal(err)
			}
			app, rt := newLazyGitPlanApp(t, home, map[string]bool{"delta": true})
			plan, err := buildInstallPlan(app, rt, time.Now())
			if err != nil {
				t.Fatal(err)
			}
			action := planActionByID(t, plan, "config:lazygit")
			if action.Disposition != operation.DispositionBlocked || !strings.Contains(action.Reason, tc.want) {
				t.Fatalf("action=%+v", action)
			}
			if got, err := os.ReadFile(path); err != nil || !bytes.Equal(got, tc.body) {
				t.Fatalf("preview mutated bytes=%q err=%v", got, err)
			}
		})
	}
}

func TestLazyGitPlannerBlocksConfigFileChainAndExternalSource(t *testing.T) {
	home := withTempHome(t)
	one := filepath.Join(home, "one.yml")
	two := filepath.Join(home, "two.yml")
	for _, path := range []string{one, two} {
		if err := os.WriteFile(path, []byte("gui:\n  mouseEvents: true\n"), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	t.Setenv("LG_CONFIG_FILE", one+","+two)
	app, rt := newLazyGitPlanApp(t, home, map[string]bool{"delta": true})
	plan, err := buildInstallPlan(app, rt, time.Now())
	if err != nil {
		t.Fatal(err)
	}
	action := planActionByID(t, plan, "config:lazygit")
	if action.Disposition != operation.DispositionBlocked || !strings.Contains(action.Reason, "LG_CONFIG_FILE") {
		t.Fatalf("action=%+v", action)
	}

	external := filepath.Join(t.TempDir(), "lazygit")
	t.Setenv("LG_CONFIG_FILE", "")
	t.Setenv("CONFIG_DIR", external)
	app, rt = newLazyGitPlanApp(t, home, map[string]bool{"delta": true})
	plan, err = buildInstallPlan(app, rt, time.Now())
	if err != nil {
		t.Fatal(err)
	}
	action = planActionByID(t, plan, "config:lazygit")
	if action.Disposition != operation.DispositionBlocked || !strings.Contains(action.Reason, "outside HOME") {
		t.Fatalf("external action=%+v", action)
	}
}

func TestLazyGitPlannerBlocksRelativeSourceOverride(t *testing.T) {
	home := withTempHome(t)
	t.Setenv("CONFIG_DIR", "relative/lazygit")
	t.Setenv("LG_CONFIG_FILE", "")
	app, rt := newLazyGitPlanApp(t, home, map[string]bool{"delta": true})
	plan, err := buildInstallPlan(app, rt, time.Now())
	if err != nil {
		t.Fatal(err)
	}
	action := planActionByID(t, plan, "config:lazygit")
	if action.Disposition != operation.DispositionBlocked || !strings.Contains(action.Reason, "CONFIG_DIR must be absolute") {
		t.Fatalf("action=%+v", action)
	}
}

func TestLazyGitPlannerBlocksActiveJesseduffieldFallbackEvenForManagedLookingBytes(t *testing.T) {
	tests := []struct {
		name string
		body []byte
	}{
		{"current generator", []byte(tools.GenerateLazyGitConfig(tools.LazyGitConfig{SidePanelWidth: "0.3333", MouseEvents: true, ColorPreset: "standard", PagerPreset: "builtin"}, "ignored"))},
		{"legacy prototype", []byte("# Generated by dotfiles TUI\ngui:\n  mouseEvents: true\n")},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			home := withTempHome(t)
			xdg := filepath.Join(home, "xdg")
			legacyDir := filepath.Join(xdg, "jesseduffield", "lazygit")
			t.Setenv("CONFIG_DIR", "")
			t.Setenv("XDG_CONFIG_HOME", xdg)
			t.Setenv("LG_CONFIG_FILE", "")
			if err := os.MkdirAll(legacyDir, 0o700); err != nil {
				t.Fatal(err)
			}
			path := filepath.Join(legacyDir, "config.yml")
			if err := os.WriteFile(path, tc.body, 0o600); err != nil {
				t.Fatal(err)
			}
			app, rt := newLazyGitPlanApp(t, home, map[string]bool{"delta": true})
			plan, err := buildInstallPlan(app, rt, time.Now())
			if err != nil {
				t.Fatal(err)
			}
			action := planActionByID(t, plan, "config:lazygit")
			if action.Disposition != operation.DispositionBlocked || !strings.Contains(action.Reason, "legacy jesseduffield") {
				t.Fatalf("action=%+v", action)
			}
			if got, err := os.ReadFile(path); err != nil || !bytes.Equal(got, tc.body) {
				t.Fatalf("legacy preview mutated bytes=%q err=%v", got, err)
			}
		})
	}
}

func TestLazyGitCurrentBytesAfterAppConstructionStillBlock(t *testing.T) {
	home := withTempHome(t)
	dir := filepath.Join(home, ".config", "lazygit")
	t.Setenv("CONFIG_DIR", dir)
	t.Setenv("LG_CONFIG_FILE", "")
	app, rt := newLazyGitPlanApp(t, home, map[string]bool{"delta": true})
	if err := os.MkdirAll(dir, 0o700); err != nil {
		t.Fatal(err)
	}
	native := []byte("gui:\n  sidePanelWidth: 0.42\n")
	if err := os.WriteFile(filepath.Join(dir, "config.yml"), native, 0o600); err != nil {
		t.Fatal(err)
	}
	plan, err := buildInstallPlan(app, rt, time.Now())
	if err != nil {
		t.Fatal(err)
	}
	if action := planActionByID(t, plan, "config:lazygit"); action.Disposition != operation.DispositionBlocked || !strings.Contains(action.Reason, "arbitrary native") {
		t.Fatalf("action=%+v", action)
	}
}

func TestLazyGitReadOnlyNativeBadgeIsVisiblyBlocked(t *testing.T) {
	home := withTempHome(t)
	dir := filepath.Join(home, ".config", "lazygit")
	t.Setenv("CONFIG_DIR", dir)
	t.Setenv("LG_CONFIG_FILE", "")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "config.yml"), []byte("gui:\n  mouseEvents: false\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	app, _ := newLazyGitPlanApp(t, home, map[string]bool{"delta": true})
	if badge := app.nativeImportBadge("lazygit"); !strings.Contains(badge, "IMPORT BLOCKED") {
		t.Fatalf("badge=%q reason=%q", badge, app.nativeConfigState.LazyGit.ReadOnlyReason)
	}
}

func TestLazyGitPreferenceReadFailureBlocksSaveWithoutTouchingNative(t *testing.T) {
	home := withTempHome(t)
	dir := filepath.Join(home, ".config", "lazygit")
	t.Setenv("CONFIG_DIR", dir)
	t.Setenv("LG_CONFIG_FILE", "")
	if err := os.MkdirAll(filepath.Dir(filepath.Join(config.ToolsDir(), "manage.json")), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(config.ToolsDir(), "manage.json"), []byte("{"), 0o600); err != nil {
		t.Fatal(err)
	}
	app, rt := newLazyGitPlanApp(t, home, map[string]bool{"delta": true})
	plan, err := buildInstallPlan(app, rt, time.Now())
	if err != nil {
		t.Fatal(err)
	}
	action := planActionByID(t, plan, "config:lazygit")
	if action.Disposition != operation.DispositionBlocked || !strings.Contains(action.Reason, "saved management preferences") {
		t.Fatalf("action=%+v", action)
	}
	if _, err := os.Stat(filepath.Join(dir, "config.yml")); !os.IsNotExist(err) {
		t.Fatalf("blocked preference preview created native file: %v", err)
	}
}

func TestReviewedStandaloneLazyGitExecutesAtManagedDynamicTarget(t *testing.T) {
	home := withTempHome(t)
	dir := filepath.Join(home, "reviewed", "lazygit")
	t.Setenv("CONFIG_DIR", dir)
	t.Setenv("LG_CONFIG_FILE", "")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(dir, "config.yml")
	initial := []byte(tools.GenerateLazyGitConfig(tools.LazyGitConfig{SidePanelWidth: "0.3333", MouseEvents: true, ColorPreset: "standard", PagerPreset: "builtin"}, "ignored"))
	if err := os.WriteFile(path, initial, 0o600); err != nil {
		t.Fatal(err)
	}
	app, _ := newLazyGitPlanApp(t, home, map[string]bool{"delta": true})
	app.startScreen = ScreenConfigLazyGit
	app.deepDiveConfig.LazyGitSidePanelWidth = "0.5"
	plan, err := buildStandaloneConfigPlan(app, time.Now())
	if err != nil || plan.hasBlocked() {
		t.Fatalf("plan blocked=%v err=%v", plan != nil && plan.hasBlocked(), err)
	}
	action := planActionByID(t, plan, "config:lazygit")
	wantRel := "reviewed/lazygit/config.yml"
	if !slices.Equal(action.BackupTargets, []string{wantRel}) || !action.Observations[0].Managed {
		t.Fatalf("action=%+v", action)
	}
	result := executeStandaloneConfigPlanResult(context.Background(), plan, defaultStandaloneConfigRuntime())
	if result.err != nil || result.manualRecovery || !result.applied {
		t.Fatalf("result=%+v", result)
	}
	got, err := os.ReadFile(path)
	if err != nil || !strings.Contains(string(got), "sidePanelWidth: 0.5") {
		t.Fatalf("result bytes=%q err=%v", got, err)
	}
}

func TestReviewedManageLazyGitCreatesMissingDynamicTargetWithEvidence(t *testing.T) {
	home := withTempHome(t)
	dir := filepath.Join(home, "xdg", "lazygit")
	t.Setenv("CONFIG_DIR", dir)
	t.Setenv("LG_CONFIG_FILE", "")
	app, _ := newLazyGitPlanApp(t, home, map[string]bool{"delta": true})
	app.manageConfig.LazyGitSidePanelWidth = "0.5"
	plan, err := buildManageSavePlan(app, time.Now())
	if err != nil || plan.plan.hasBlocked() {
		t.Fatalf("plan blocked=%v err=%v", plan != nil && plan.plan.hasBlocked(), err)
	}
	action := planActionByID(t, plan.plan, "config:lazygit")
	wantRel := "xdg/lazygit/config.yml"
	if !slices.Contains(action.BackupTargets, wantRel) || action.Observation.Exists || action.Ownership != operation.OwnershipManagedFile {
		t.Fatalf("action=%+v", action)
	}
	result := executeManageSavePlanResult(context.Background(), plan, defaultManageSaveRuntime())
	if result.err != nil || result.manualRecovery || !result.applied {
		t.Fatalf("result=%+v", result)
	}
	content, err := os.ReadFile(filepath.Join(dir, "config.yml"))
	if err != nil || !tools.IsManagedLazyGitConfigContent(content) || !strings.Contains(string(content), "sidePanelWidth: 0.5") {
		t.Fatalf("managed bytes=%q err=%v", content, err)
	}
}

func TestReviewedInstallerWritesLazyGitToAcceptedConfigDirTarget(t *testing.T) {
	home := withTempHome(t)
	dir := filepath.Join(home, "reviewed", "lazygit")
	t.Setenv("CONFIG_DIR", dir)
	t.Setenv("LG_CONFIG_FILE", "")
	installed := make(map[string]bool)
	for _, tool := range tools.GetRegistry().All() {
		installed[tool.ID()] = true
	}
	app, installRuntime := newLazyGitPlanApp(t, home, installed)
	app.deepDiveConfig.LazyGitSidePanelWidth = "0.5"
	plan, err := buildInstallPlan(app, installRuntime, time.Now())
	if err != nil {
		t.Fatal(err)
	}
	wantRel := "reviewed/lazygit/config.yml"
	if action := planActionByID(t, plan, "config:lazygit"); !slices.Equal(action.BackupTargets, []string{wantRel}) {
		t.Fatalf("action=%+v", action)
	}
	keep := map[string]bool{"state:parents": true, "state:global": true, "config:lazygit": true}
	var actions []operation.Action
	authority := make(map[string]map[string]acceptedTarget)
	for _, action := range plan.actions() {
		if keep[action.ID] || action.Kind == operation.KindInstallFile {
			actions = append(actions, action)
			authority[action.ID] = plan.authority[action.ID]
		}
	}
	document, err := operation.NewPlan(time.Now(), actions)
	if err != nil {
		t.Fatal(err)
	}
	reviewed := &installPlan{
		document: document, configTools: []string{"lazygit"}, config: plan.config,
		theme: plan.theme, navStyle: plan.navStyle, animations: plan.animations,
		globalConfig: plan.globalConfig, authority: authority, parentDirs: plan.parentDirs,
		statePlan: plan.statePlan,
	}
	installRuntime.backupTargetsWithState = backupPlanTargetsWithState
	installRuntime.backupTargets = nil
	events := make(chan installEventMsg, 256)
	runInstallWorkerFromPlanWithRuntime(context.Background(), events, reviewed, installRuntime, true)
	var terminal installEventMsg
	for event := range events {
		if event.done {
			terminal = event
		}
	}
	if terminal.err != nil {
		t.Fatalf("reviewed installer result=%v\n%s", terminal.err, terminal.context)
	}
	content, err := os.ReadFile(filepath.Join(home, filepath.FromSlash(wantRel)))
	if err != nil || !tools.IsManagedLazyGitConfigContent(content) || !strings.Contains(string(content), "sidePanelWidth: 0.5") {
		t.Fatalf("managed bytes=%q err=%v", content, err)
	}
	if _, err := os.Stat(filepath.Join(home, ".config", "lazygit", "config.yml")); !os.IsNotExist(err) {
		t.Fatalf("installer wrote inactive fallback: %v", err)
	}
}

func TestLazyGitDeltaDependencyGatesInstallerAndEditors(t *testing.T) {
	home := withTempHome(t)
	t.Setenv("CONFIG_DIR", filepath.Join(home, ".config", "lazygit"))
	t.Setenv("LG_CONFIG_FILE", "")
	app, rt := newLazyGitPlanApp(t, home, map[string]bool{})
	app.deepDiveConfig.LazyGitPagerPreset = "delta"
	app.deepDiveConfig.CLIUtilities["delta"] = false
	plan, err := buildInstallPlan(app, rt, time.Now())
	if err != nil {
		t.Fatal(err)
	}
	if action := planActionByID(t, plan, "config:lazygit"); action.Disposition != operation.DispositionBlocked || !strings.Contains(action.Reason, "select the Delta") {
		t.Fatalf("disabled Delta action=%+v", action)
	}
	app.deepDiveConfig.CLIUtilities["delta"] = true
	plan, err = buildInstallPlan(app, rt, time.Now())
	if err != nil {
		t.Fatal(err)
	}
	if action := planActionByID(t, plan, "config:lazygit"); action.Disposition != operation.DispositionApply {
		t.Fatalf("planned Delta action=%+v", action)
	}
	if action := planActionByID(t, plan, "install:delta"); action.Disposition != operation.DispositionApply {
		t.Fatalf("Delta dependency action=%+v", action)
	}

	app.startScreen = ScreenConfigLazyGit
	app.manageInstalledReady = false
	if reason := lazyGitDeltaAvailabilityReason(app); !strings.Contains(reason, "not ready") {
		t.Fatalf("not-ready reason=%q", reason)
	}
	app.manageInstalledReady = true
	if reason := lazyGitDeltaAvailabilityReason(app); !strings.Contains(reason, "install the Delta") {
		t.Fatalf("missing reason=%q", reason)
	}
	app.manageInstalled["delta"] = true
	if reason := lazyGitDeltaAvailabilityReason(app); reason != "" {
		t.Fatalf("installed reason=%q", reason)
	}
	standalone, err := buildStandaloneConfigPlan(app, time.Now())
	if err != nil || standalone.hasBlocked() {
		t.Fatalf("installed standalone blocked=%v err=%v", standalone != nil && standalone.hasBlocked(), err)
	}
}

func TestManageLazyGitDeltaRequiresCachedInstallation(t *testing.T) {
	home := withTempHome(t)
	t.Setenv("CONFIG_DIR", filepath.Join(home, ".config", "lazygit"))
	t.Setenv("LG_CONFIG_FILE", "")
	app, _ := newLazyGitPlanApp(t, home, map[string]bool{})
	app.manageConfig.LazyGitPagerPreset = "delta"
	plan, err := buildManageSavePlan(app, time.Now())
	if err != nil {
		t.Fatal(err)
	}
	action := planActionByID(t, plan.plan, "config:lazygit")
	if action.Disposition != operation.DispositionBlocked || !strings.Contains(action.Reason, "install the Delta") {
		t.Fatalf("missing Delta action=%+v", action)
	}
	app.manageInstalled["delta"] = true
	plan, err = buildManageSavePlan(app, time.Now())
	if err != nil {
		t.Fatal(err)
	}
	if action = planActionByID(t, plan.plan, "config:lazygit"); action.Disposition != operation.DispositionApply {
		t.Fatalf("installed Delta action=%+v", action)
	}
}
