package ui

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// manageConfigToolIDs is the set of tool IDs whose Manage field tables this
// guardrail covers (everything manageFieldsFor returns fields for except the
// "global" pseudo-tool and claude-code, whose MCP toggles apply through a separate
// gated path). It is the iteration source for the completeness checks.
var manageConfigToolIDs = []string{
	"ghostty", "tmux", "zsh", "neovim", "git", "yazi",
	"fzf", "lazygit", "lazydocker", "btop", "glow",
}

// appForFields builds a minimal App sufficient for manageFieldsFor to enumerate a
// tool's editable fields.
func appForFields() *App {
	return &App{
		manageConfig:      NewManageConfig(),
		theme:             "catppuccin-mocha",
		navStyle:          "emacs",
		animationsEnabled: true,
	}
}

// manageFieldRoundTrip describes how to prove one applied Manage field reaches its
// generated config file: mutate sets the ManageConfig field away from its default,
// file is the generated path (relative to HOME), and want is a substring the
// mutated value must produce in that file.
type manageFieldRoundTrip struct {
	mutate func(mc *ManageConfig)
	file   string // path under HOME
	want   string
}

// manageAppliedRoundTrips is the round-trip proof table: every Manage field
// classified as APPLIED (i.e. NOT in manageNotAppliedFields) must have an entry
// here, keyed "toolID/fieldKey". Running the entry through the real scoped Manage
// save path (manageConfigToDeepDive -> changedManageTools -> applyChangedManageTools)
// and finding `want` in `file` proves the field is wired end-to-end:
// struct -> manageConfigToDeepDive -> toolDeepDiveFields (so the scoped diff
// detects it) -> generator (so the file actually changes). The guardrail test
// fails if any applied field lacks an entry here OR if its entry does not
// round-trip.
var manageAppliedRoundTrips = map[string]manageFieldRoundTrip{
	// Ghostty
	"ghostty/font_family":   {func(mc *ManageConfig) { mc.GhosttyFontFamily = "Fira Code" }, ".config/ghostty/config", "Fira Code"},
	"ghostty/font_size":     {func(mc *ManageConfig) { mc.GhosttyFontSize = 21 }, ".config/ghostty/config", "font-size = 21"},
	"ghostty/opacity":       {func(mc *ManageConfig) { mc.GhosttyOpacity = 80 }, ".config/ghostty/config", "background-opacity = 0.80"},
	"ghostty/blur":          {func(mc *ManageConfig) { mc.GhosttyBlurRadius = 12 }, ".config/ghostty/config", "background-blur-radius = 12"},
	"ghostty/cursor":        {func(mc *ManageConfig) { mc.GhosstyCursorStyle = "bar" }, ".config/ghostty/config", "cursor-style = bar"},
	"ghostty/scrollback":    {func(mc *ManageConfig) { mc.GhosttyScrollbackLines = 12345 }, ".config/ghostty/config", "scrollback-limit = 12345"},
	"ghostty/decor":         {func(mc *ManageConfig) { mc.GhosttyWindowDecorations = false }, ".config/ghostty/config", "window-decoration = false"},
	"ghostty/confirm_close": {func(mc *ManageConfig) { mc.GhosttyConfirmClose = false }, ".config/ghostty/config", "confirm-close-surface = false"},

	// Tmux
	"tmux/prefix":            {func(mc *ManageConfig) { mc.TmuxPrefix = "C-b" }, ".tmux.conf", "set -g prefix C-b"},
	"tmux/base":              {func(mc *ManageConfig) { mc.TmuxBaseIndex = 0 }, ".tmux.conf", "set -g base-index 0"},
	"tmux/mouse":             {func(mc *ManageConfig) { mc.TmuxMouseMode = false }, ".tmux.conf", "set -g mouse off"},
	"tmux/status_pos":        {func(mc *ManageConfig) { mc.TmuxStatusPosition = "top" }, ".tmux.conf", "set -g status-position top"},
	"tmux/pane_border":       {func(mc *ManageConfig) { mc.TmuxPaneBorderStyle = "double" }, ".tmux.conf", "pane-border-lines double"},
	"tmux/history":           {func(mc *ManageConfig) { mc.TmuxHistoryLimit = 12345 }, ".tmux.conf", "set -g history-limit 12345"},
	"tmux/escape":            {func(mc *ManageConfig) { mc.TmuxEscapeTime = 25 }, ".tmux.conf", "set -sg escape-time 25"},
	"tmux/resize":            {func(mc *ManageConfig) { mc.TmuxAggressiveResize = false }, ".tmux.conf", "aggressive-resize off"},
	"tmux/tpm_enabled":       {func(mc *ManageConfig) { mc.TmuxTPMEnabled = false }, ".tmux.conf", "Generated by dotfiles"},
	"tmux/plugin_sensible":   {func(mc *ManageConfig) { mc.TmuxPluginSensible = false }, ".tmux.conf", "Generated by dotfiles"},
	"tmux/plugin_resurrect":  {func(mc *ManageConfig) { mc.TmuxPluginResurrect = false }, ".tmux.conf", "Generated by dotfiles"},
	"tmux/plugin_continuum":  {func(mc *ManageConfig) { mc.TmuxPluginContinuum = true }, ".tmux.conf", "tmux-continuum"},
	"tmux/plugin_yank":       {func(mc *ManageConfig) { mc.TmuxPluginYank = false }, ".tmux.conf", "Generated by dotfiles"},
	"tmux/continuum_save":    {func(mc *ManageConfig) { mc.TmuxPluginContinuum = true; mc.TmuxContinuumSaveMin = 45 }, ".tmux.conf", "@continuum-save-interval '45'"},
	"tmux/continuum_restore": {func(mc *ManageConfig) { mc.TmuxPluginContinuum = true; mc.TmuxContinuumRestore = false }, ".tmux.conf", "@continuum-restore 'off'"},

	// Zsh
	"zsh/hist_size": {func(mc *ManageConfig) { mc.ZshHistorySize = 12345 }, ".zshrc", "HISTSIZE=12345"},
	"zsh/hist_dups": {func(mc *ManageConfig) { mc.ZshHistoryIgnoreDups = false }, ".zshrc", "Generated by dotfiles"},
	"zsh/autocd":    {func(mc *ManageConfig) { mc.ZshAutoCD = false }, ".zshrc", "Generated by dotfiles"},
	"zsh/correct":   {func(mc *ManageConfig) { mc.ZshCorrection = false }, ".zshrc", "Generated by dotfiles"},
	"zsh/menu":      {func(mc *ManageConfig) { mc.ZshCompletionMenu = false }, ".zshrc", "Generated by dotfiles"},
	"zsh/syntax":    {func(mc *ManageConfig) { mc.ZshSyntaxHighlight = false }, ".zshrc", "Generated by dotfiles"},
	"zsh/autosug":   {func(mc *ManageConfig) { mc.ZshAutosuggestions = false }, ".zshrc", "Generated by dotfiles"},

	// Neovim (requires an existing ~/.config/nvim; the test seeds it)
	"neovim/numbers": {func(mc *ManageConfig) { mc.NeovimLineNumbers = "none" }, ".config/nvim/lua/custom/options.lua", "vim.opt.number = false"},
	"neovim/rel":     {func(mc *ManageConfig) { mc.NeovimRelativeNum = false }, ".config/nvim/lua/custom/options.lua", "vim.opt.relativenumber = false"},
	"neovim/tab":     {func(mc *ManageConfig) { mc.NeovimTabWidth = 8 }, ".config/nvim/lua/custom/options.lua", "vim.opt.tabstop = 8"},
	"neovim/expand":  {func(mc *ManageConfig) { mc.NeovimExpandTab = false }, ".config/nvim/lua/custom/options.lua", "vim.opt.expandtab = false"},
	"neovim/wrap":    {func(mc *ManageConfig) { mc.NeovimWrap = true }, ".config/nvim/lua/custom/options.lua", "vim.opt.wrap = true"},
	"neovim/cursor":  {func(mc *ManageConfig) { mc.NeovimCursorLine = false }, ".config/nvim/lua/custom/options.lua", "vim.opt.cursorline = false"},
	"neovim/clip":    {func(mc *ManageConfig) { mc.NeovimClipboard = "unnamed" }, ".config/nvim/lua/custom/options.lua", "vim.opt.clipboard = \"unnamed\""},
	"neovim/undo":    {func(mc *ManageConfig) { mc.NeovimUndoFile = false }, ".config/nvim/lua/custom/options.lua", "vim.opt.undofile = false"},

	// Git
	"git/branch":       {func(mc *ManageConfig) { mc.GitDefaultBranch = "develop" }, ".gitconfig", "defaultBranch = develop"},
	"git/setup_remote": {func(mc *ManageConfig) { mc.GitAutoSetupRemote = false }, ".gitconfig", "autoSetupRemote = false"},
	"git/rebase":       {func(mc *ManageConfig) { mc.GitPullRebase = false }, ".gitconfig", "rebase = false"},
	"git/diff":         {func(mc *ManageConfig) { mc.GitDiffTool = "vimdiff" }, ".gitconfig", "Generated by dotfiles"},
	"git/merge":        {func(mc *ManageConfig) { mc.GitMergeTool = "meld" }, ".gitconfig", "tool = meld"},
	"git/creds":        {func(mc *ManageConfig) { mc.GitCredentialHelper = "store" }, ".gitconfig", "helper = store"},
	"git/sign":         {func(mc *ManageConfig) { mc.GitSignCommits = true }, ".gitconfig", "gpgsign = true"},

	// Yazi
	"yazi/hidden":    {func(mc *ManageConfig) { mc.YaziShowHidden = true }, ".config/yazi/yazi.toml", "show_hidden = true"},
	"yazi/sort_by":   {func(mc *ManageConfig) { mc.YaziSortBy = "modified" }, ".config/yazi/yazi.toml", "sort_by = \"mtime\""},
	"yazi/sort_rev":  {func(mc *ManageConfig) { mc.YaziSortReverse = true }, ".config/yazi/yazi.toml", "sort_reverse = true"},
	"yazi/linemode":  {func(mc *ManageConfig) { mc.YaziLineMode = "permissions" }, ".config/yazi/yazi.toml", "linemode = \"permissions\""},
	"yazi/scrolloff": {func(mc *ManageConfig) { mc.YaziScrollOff = 9 }, ".config/yazi/yazi.toml", "scrolloff = 9"},

	// FZF
	"fzf/opts":           {func(mc *ManageConfig) { mc.FzfDefaultOpts = "--cycle" }, ".config/fzf/fzf.zsh", "--cycle"},
	"fzf/height":         {func(mc *ManageConfig) { mc.FzfHeight = 55 }, ".config/fzf/fzf.zsh", "--height=55%"},
	"fzf/layout":         {func(mc *ManageConfig) { mc.FzfLayout = "reverse-list" }, ".config/fzf/fzf.zsh", "--layout=reverse-list"},
	"fzf/border":         {func(mc *ManageConfig) { mc.FzfBorderStyle = "sharp" }, ".config/fzf/fzf.zsh", "--border=sharp"},
	"fzf/preview":        {func(mc *ManageConfig) { mc.FzfPreview = false }, ".config/fzf/fzf.zsh", "Generated by dotfiles"},
	"fzf/preview_window": {func(mc *ManageConfig) { mc.FzfPreviewWindow = "up:50%" }, ".config/fzf/fzf.zsh", "--preview-window=up:50%"},

	// LazyGit
	"lazygit/side":      {func(mc *ManageConfig) { mc.LazyGitSideBySide = false }, ".config/lazygit/config.yml", "Generated by dotfiles"},
	"lazygit/paging":    {func(mc *ManageConfig) { mc.LazyGitPaging = "never" }, ".config/lazygit/config.yml", "pager: cat"},
	"lazygit/mouse":     {func(mc *ManageConfig) { mc.LazyGitMouseMode = false }, ".config/lazygit/config.yml", "mouseEvents: false"},
	"lazygit/gui_theme": {func(mc *ManageConfig) { mc.LazyGitGuiTheme = "light" }, ".config/lazygit/config.yml", "Generated by dotfiles"},

	// Btop
	"btop/theme": {func(mc *ManageConfig) { mc.BtopTheme = "nord" }, ".config/btop/btop.conf", "color_theme = \"nord\""},
	"btop/rate":  {func(mc *ManageConfig) { mc.BtopUpdateMs = 750 }, ".config/btop/btop.conf", "update_ms = 750"},
	"btop/temp":  {func(mc *ManageConfig) { mc.BtopShowTemp = false }, ".config/btop/btop.conf", "show_coretemp = false"},
	"btop/scale": {func(mc *ManageConfig) { mc.BtopTempScale = "fahrenheit" }, ".config/btop/btop.conf", "temp_scale = \"fahrenheit\""},
	"btop/graph": {func(mc *ManageConfig) { mc.BtopGraphSymbol = "block" }, ".config/btop/btop.conf", "graph_symbol = \"block\""},
	"btop/boxes": {func(mc *ManageConfig) { mc.BtopShownBoxes = "cpu mem" }, ".config/btop/btop.conf", "shown_boxes = \"cpu mem\""},

	// Glow
	"glow/style": {func(mc *ManageConfig) { mc.GlowStyle = "light" }, ".config/glow/glow.yml", "style: \"light\""},
	"glow/pager": {func(mc *ManageConfig) { mc.GlowPager = "never" }, ".config/glow/glow.yml", "pager: false"},
	"glow/width": {func(mc *ManageConfig) { mc.GlowWidth = 123 }, ".config/glow/glow.yml", "width: 123"},
	"glow/mouse": {func(mc *ManageConfig) { mc.GlowMouse = false }, ".config/glow/glow.yml", "mouse: false"},
}

// TestManageFieldsAllClassified is the completeness half of the guardrail: every
// field key the Manage UI presents as editable-and-saving must be classified as
// either applied (has a manageAppliedRoundTrips entry) or explicitly not-applied
// (in manageNotAppliedFields). This is what makes "no control may report success
// while doing nothing" unable to silently regress: add a new editable field and
// this test fails until it is wired or marked.
func TestManageFieldsAllClassified(t *testing.T) {
	app := appForFields()

	for _, toolID := range manageConfigToolIDs {
		fields := app.manageFieldsFor(toolID)
		if len(fields) == 0 {
			t.Errorf("tool %q presents no fields (manageConfigToolIDs out of sync?)", toolID)
			continue
		}
		for _, f := range fields {
			key := toolID + "/" + f.key
			applied := manageFieldIsApplied(toolID, f.key)
			_, hasRoundTrip := manageAppliedRoundTrips[key]

			if applied {
				if !hasRoundTrip {
					t.Errorf("field %q is classified APPLIED but has no round-trip proof in manageAppliedRoundTrips; either wire it through a generator (and add the round-trip) or list it in manageNotAppliedFields", key)
				}
			} else {
				if hasRoundTrip {
					t.Errorf("field %q is in manageNotAppliedFields yet also has a round-trip entry; remove one", key)
				}
			}
		}
	}
}

// TestManageNotAppliedKeysAreReal is the reverse-direction guard: every key listed
// in manageNotAppliedFields must correspond to a field the UI actually presents, so
// the not-applied list can never contain stale keys that mark nothing.
func TestManageNotAppliedKeysAreReal(t *testing.T) {
	app := appForFields()
	for toolID, keys := range manageNotAppliedFields {
		presented := map[string]bool{}
		for _, f := range app.manageFieldsFor(toolID) {
			presented[f.key] = true
		}
		for key := range keys {
			if !presented[key] {
				t.Errorf("manageNotAppliedFields[%q][%q] does not match any presented field", toolID, key)
			}
		}
	}
}

// TestManageAppliedFieldsRoundTrip is the apply half of the guardrail: for every
// applied field, mutating it and running the real scoped Manage save must change
// the generated config file (the `want` substring appears). This proves the field
// is wired through manageConfigToDeepDive + toolDeepDiveFields (so the scoped diff
// detects the change) + the generator (so the file is actually written) — closing
// the "added to generator but not toolDeepDiveFields" under-apply trap.
func TestManageAppliedFieldsRoundTrip(t *testing.T) {
	for key, rt := range manageAppliedRoundTrips {
		key, rt := key, rt
		t.Run(key, func(t *testing.T) {
			home := withTempHome(t)

			// Neovim's pure writer only overlays an EXISTING ~/.config/nvim, so seed
			// one (mirrors an installed preset) before saving.
			if strings.HasPrefix(key, "neovim/") {
				nvimDir := filepath.Join(home, ".config", "nvim")
				if err := os.MkdirAll(nvimDir, 0o755); err != nil {
					t.Fatalf("seed nvim dir: %v", err)
				}
				if err := os.WriteFile(filepath.Join(nvimDir, "init.lua"), []byte("-- seed\n"), 0o644); err != nil {
					t.Fatalf("seed init.lua: %v", err)
				}
			}

			baseline := NewManageConfig()
			current := NewManageConfig()
			rt.mutate(current)

			const theme = "catppuccin-mocha"
			changed := changedManageTools(baseline, current, theme, theme)
			if len(changed) == 0 {
				t.Fatalf("mutating %q produced no detected change; field is not wired into toolDeepDiveFields (under-apply trap)", key)
			}
			if errs := applyChangedManageTools(changed, manageConfigToDeepDive(current), theme); len(errs) > 0 {
				t.Fatalf("applyChangedManageTools(%q) errors: %v", key, errs)
			}

			path := filepath.Join(home, rt.file)
			data, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("read %s: %v", path, err)
			}
			if !strings.Contains(string(data), rt.want) {
				t.Errorf("field %q did not round-trip: %q not found in %s:\n%s", key, rt.want, rt.file, string(data))
			}
		})
	}
}
