package ui

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/tekierz/dotfiles/internal/config"
	"github.com/tekierz/dotfiles/internal/tools"
)

var yaziManageFields = []string{
	"YaziKeymap", "YaziShowHidden", "YaziPreviewMode", "YaziSortBy",
	"YaziSortReverse", "YaziLineMode", "YaziScrollOff",
}

func TestCurrentNativeImportSchemaVersionIsSix(t *testing.T) {
	if currentNativeImportSchemaVersion != 6 {
		t.Fatalf("native import schema = %d, want 6", currentNativeImportSchemaVersion)
	}
}

func TestYaziPreferencePresenceMigratesSchemasZeroThroughFive(t *testing.T) {
	for schema := 0; schema <= 6; schema++ {
		t.Run(fmt.Sprintf("schema-%d", schema), func(t *testing.T) {
			withTempHome(t)
			version := ""
			if schema != 0 {
				version = fmt.Sprintf(`"NativeImportSchemaVersion":%d,`, schema)
			}
			data := fmt.Sprintf(`{%s"YaziKeymap":"emacs","YaziShowHidden":true,"YaziPreviewMode":"never","YaziSortBy":"size","YaziSortReverse":true,"YaziLineMode":"permissions","YaziScrollOff":9}`, version)
			path := filepath.Join(config.ToolsDir(), "manage.json")
			if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(path, []byte(data), 0o600); err != nil {
				t.Fatal(err)
			}
			presence := inspectManagePreferencePresence()
			if presence.err != nil {
				t.Fatal(presence.err)
			}
			for _, field := range yaziManageFields {
				want := schema == 6
				if presence.fields[field] != want {
					t.Fatalf("%s presence = %t, want %t", field, presence.fields[field], want)
				}
			}
		})
	}
}

func TestYaziNativePerFilePrecedence(t *testing.T) {
	t.Run("native main and keymap override saved preferences read-only", func(t *testing.T) {
		dir := prepareNativeYaziUI(t)
		writeNativeYaziUI(t, dir, tools.YaziFileMain, "[mgr]\nshow_hidden = true\nsort_by = \"size\"\nsort_reverse = true\nlinemode = \"permissions\"\nscrolloff = 9\n\n[preview]\nimage_delay = 0\n")
		writeNativeYaziUI(t, dir, tools.YaziFileKeymap, "[mgr]\nkeymap = [{ on = \"<C-n>\", run = \"arrow 1\" }]\n")
		target := savedYaziPreferences()
		state := observeNativeManageConfig(target, explicitYaziPreferences(nil), "dracula")
		assertYaziValues(t, target, "emacs", true, "always", "size", true, "permissions", 9)
		if state.Yazi.Main.ReadOnlyReason == "" || state.Yazi.Keymap.ReadOnlyReason == "" {
			t.Fatalf("native observations not read-only: %#v", state.Yazi)
		}
	})

	for _, exact := range []bool{false, true} {
		name := "missing allows explicit schema6 preferences"
		if exact {
			name = "exact-current allows explicit schema6 preferences"
		}
		t.Run(name, func(t *testing.T) {
			dir := prepareNativeYaziUI(t)
			if exact {
				current := "# Generated by dotfiles TUI\n# Compatibility: Yazi 26.5.6\n\n[mgr]\nsort_by = \"natural\"\nsort_reverse = false\nlinemode = \"none\"\nscrolloff = 5\nshow_hidden = false\n\n[preview]\nimage_delay = 30\n"
				writeNativeYaziUI(t, dir, tools.YaziFileMain, current)
			}
			target := savedYaziPreferences()
			observeNativeManageConfig(target, explicitYaziPreferences(nil), "dracula")
			assertSavedYaziPreferences(t, target)
		})
	}

	t.Run("exact historical hydrates observed truth read-only", func(t *testing.T) {
		observed := tools.YaziConfig{Keymap: "emacs", ShowHidden: true, PreviewMode: "never", SortBy: "modified", SortReverse: true, LineMode: "permissions", ScrollOff: 9}
		imported := tools.YaziConfigImport{
			Config: observed,
			Main:   tools.YaziFileObservation{Kind: tools.YaziFileKindMain, Exists: true, Ownership: tools.YaziOwnershipExactHistorical, ReadOnlyReason: "exact historical Yazi main is read-only"},
			Keymap: tools.YaziFileObservation{Kind: tools.YaziFileKindKeymap, Exists: true, Ownership: tools.YaziOwnershipExactHistorical, ReadOnlyReason: "exact historical Yazi keymap is read-only"},
		}
		target := savedYaziPreferences()
		overlayImportedYaziConfig(target, imported, explicitYaziPreferences(nil).fields)
		assertYaziValues(t, target, "emacs", true, "never", "modified", true, "permissions", 9)
		if imported.Main.Ownership != tools.YaziOwnershipExactHistorical || imported.Keymap.Ownership != tools.YaziOwnershipExactHistorical {
			t.Fatalf("historical state lost: %#v", imported)
		}
	})

	t.Run("malformed main overlays none while valid keymap overlays", func(t *testing.T) {
		dir := prepareNativeYaziUI(t)
		writeNativeYaziUI(t, dir, tools.YaziFileMain, "[mgr\nshow_hidden = true\n")
		writeNativeYaziUI(t, dir, tools.YaziFileKeymap, "[mgr]\nkeymap = [{ on = \"<C-n>\", run = \"arrow 1\" }]\n")
		target := savedYaziPreferences()
		state := observeNativeManageConfig(target, explicitYaziPreferences(nil), "dracula")
		assertYaziValues(t, target, "emacs", false, "auto", "alphabetical", false, "none", 3)
		if state.Yazi.Main.Ownership != tools.YaziOwnershipMalformed || state.Yazi.Keymap.Ownership != tools.YaziOwnershipNative {
			t.Fatalf("per-file states lost: %#v", state.Yazi)
		}
	})

	t.Run("preference error retains observations and overlays nothing", func(t *testing.T) {
		dir := prepareNativeYaziUI(t)
		writeNativeYaziUI(t, dir, tools.YaziFileMain, "[mgr]\nshow_hidden = true\n")
		writeNativeYaziUI(t, dir, tools.YaziFileKeymap, "[mgr]\nkeymap = [{ on = \"<C-n>\", run = \"arrow 1\" }]\n")
		target := savedYaziPreferences()
		state := observeNativeManageConfig(target, explicitYaziPreferences(errors.New("preferences unreadable")), "dracula")
		assertSavedYaziPreferences(t, target)
		if state.PreferenceError == "" || !state.Yazi.Main.Exists || !state.Yazi.Keymap.Exists {
			t.Fatalf("preference error discarded observation: %#v", state)
		}
	})
}

func TestYaziSchemaSixPrecedenceCompleteness(t *testing.T) {
	t.Run("partial native main owns all six main fields", func(t *testing.T) {
		dir := prepareNativeYaziUI(t)
		writeNativeYaziUI(t, dir, tools.YaziFileMain, "[mgr]\nshow_hidden = true\n")
		target := savedYaziPreferences()
		target.YaziPreviewMode = "never"
		target.YaziSortBy = "size"
		target.YaziSortReverse = true
		target.YaziLineMode = "permissions"
		target.YaziScrollOff = 3
		state := observeNativeManageConfig(target, explicitYaziPreferences(nil), "dracula")
		assertYaziValues(t, target, "vim", true, "auto", "alphabetical", false, "none", 5)
		if state.Yazi.Main.Ownership != tools.YaziOwnershipNative {
			t.Fatalf("partial main ownership = %#v", state.Yazi.Main)
		}
	})

	t.Run("empty native keymap owns effective vim default", func(t *testing.T) {
		dir := prepareNativeYaziUI(t)
		writeNativeYaziUI(t, dir, tools.YaziFileKeymap, "")
		target := savedYaziPreferences()
		target.YaziKeymap = "emacs"
		state := observeNativeManageConfig(target, explicitYaziPreferences(nil), "dracula")
		if target.YaziKeymap != "vim" || state.Yazi.Keymap.Ownership != tools.YaziOwnershipNative {
			t.Fatalf("empty native keymap did not own effective default: target=%+v state=%#v", target, state.Yazi)
		}
		if _, exists := state.Yazi.Fields[tools.YaziFieldKeymap]; exists {
			t.Fatal("empty native keymap unexpectedly emitted field provenance")
		}
	})

	t.Run("native main and exact-current keymap split ownership", func(t *testing.T) {
		dir := prepareNativeYaziUI(t)
		writeNativeYaziUI(t, dir, tools.YaziFileMain, "[mgr]\nshow_hidden = true\n")
		writeNativeYaziUI(t, dir, tools.YaziFileKeymap, exactCurrentYaziVimKeymap())
		target := savedYaziPreferences()
		target.YaziKeymap = "emacs"
		state := observeNativeManageConfig(target, explicitYaziPreferences(nil), "dracula")
		assertYaziValues(t, target, "emacs", true, "auto", "alphabetical", false, "none", 5)
		if !state.Yazi.Main.Exists || !state.Yazi.Keymap.Exists || state.Yazi.Main.Ownership != tools.YaziOwnershipNative || state.Yazi.Keymap.Ownership != tools.YaziOwnershipExactCurrent {
			t.Fatalf("split ownership mismatch: %#v", state.Yazi)
		}
	})

	t.Run("exact-current main and native keymap split ownership", func(t *testing.T) {
		dir := prepareNativeYaziUI(t)
		writeNativeYaziUI(t, dir, tools.YaziFileMain, exactCurrentYaziMain())
		writeNativeYaziUI(t, dir, tools.YaziFileKeymap, "[mgr]\nkeymap = [{ on = \"<C-n>\", run = \"arrow 1\" }]\n")
		target := savedYaziPreferences()
		state := observeNativeManageConfig(target, explicitYaziPreferences(nil), "dracula")
		assertYaziValues(t, target, "emacs", false, "auto", "alphabetical", false, "none", 3)
		if !state.Yazi.Main.Exists || !state.Yazi.Keymap.Exists || state.Yazi.Main.Ownership != tools.YaziOwnershipExactCurrent || state.Yazi.Keymap.Ownership != tools.YaziOwnershipNative {
			t.Fatalf("inverse split ownership mismatch: %#v", state.Yazi)
		}
	})

	t.Run("partial explicit presence retains only saved exact-current fields", func(t *testing.T) {
		dir := prepareNativeYaziUI(t)
		writeNativeYaziUI(t, dir, tools.YaziFileMain, exactCurrentYaziMain())
		writeNativeYaziUI(t, dir, tools.YaziFileKeymap, exactCurrentYaziEmacsKeymap())
		target := savedYaziPreferences()
		presence := managePreferencePresence{exists: true, schema: 6, fields: map[string]bool{
			"YaziShowHidden": true,
			"YaziKeymap":     true,
		}}
		state := observeNativeManageConfig(target, presence, "dracula")
		assertYaziValues(t, target, "vim", false, "never", "natural", true, "permissions", 9)
		if !state.Yazi.Main.Exists || !state.Yazi.Keymap.Exists || state.Yazi.Main.Ownership != tools.YaziOwnershipExactCurrent || state.Yazi.Keymap.Ownership != tools.YaziOwnershipExactCurrent {
			t.Fatalf("partial-presence ownership mismatch: %#v", state.Yazi)
		}
	})
}

func TestYaziSchemaSixMalformedFileIsolation(t *testing.T) {
	t.Run("malformed keymap preserves saved keymap while native main overlays", func(t *testing.T) {
		dir := prepareNativeYaziUI(t)
		writeNativeYaziUI(t, dir, tools.YaziFileMain, "[mgr]\nshow_hidden = true\n")
		writeNativeYaziUI(t, dir, tools.YaziFileKeymap, "[mgr\nkeymap = []\n")
		target := savedYaziPreferences()
		target.YaziKeymap = "emacs"
		state := observeNativeManageConfig(target, explicitYaziPreferences(nil), "dracula")
		assertYaziValues(t, target, "emacs", true, "auto", "alphabetical", false, "none", 5)
		if state.Yazi.Main.Ownership != tools.YaziOwnershipNative || state.Yazi.Keymap.Ownership != tools.YaziOwnershipMalformed || state.Yazi.Keymap.Error == "" {
			t.Fatalf("malformed keymap isolation mismatch: %#v", state.Yazi)
		}
	})

	t.Run("malformed theme does not block valid main and keymap", func(t *testing.T) {
		dir := prepareNativeYaziUI(t)
		writeNativeYaziUI(t, dir, tools.YaziFileMain, "[mgr]\nshow_hidden = true\n")
		writeNativeYaziUI(t, dir, tools.YaziFileKeymap, "[mgr]\nkeymap = [{ on = \"<C-n>\", run = \"arrow 1\" }]\n")
		writeNativeYaziUI(t, dir, tools.YaziFileTheme, "[mgr\ncwd = {}\n")
		target := savedYaziPreferences()
		app := &App{theme: "dracula", manageConfig: target}
		app.nativeConfigState = observeNativeManageConfig(target, explicitYaziPreferences(nil), app.theme)
		assertYaziValues(t, target, "emacs", true, "auto", "alphabetical", false, "none", 5)
		if app.theme != "dracula" || app.nativeConfigState.Yazi.Main.Ownership != tools.YaziOwnershipNative || app.nativeConfigState.Yazi.Keymap.Ownership != tools.YaziOwnershipNative || app.nativeConfigState.Yazi.Theme.Ownership != tools.YaziOwnershipMalformed || app.nativeConfigState.Yazi.Theme.Error == "" {
			t.Fatalf("malformed theme isolation mismatch: theme=%q state=%#v", app.theme, app.nativeConfigState.Yazi)
		}
	})
}

func TestYaziResolverErrorIsVisibleAndOverlaysNothing(t *testing.T) {
	withTempHome(t)
	t.Setenv("YAZI_CONFIG_HOME", "relative/yazi")
	t.Setenv("CONFIG_DIR", "")
	t.Setenv("LG_CONFIG_FILE", "")
	target := savedYaziPreferences()
	before := *target
	state := observeNativeManageConfig(target, explicitYaziPreferences(nil), "dracula")
	if state.YaziError == "" {
		t.Fatal("resolver error was not exposed")
	}
	if *target != before {
		t.Fatalf("resolver error overlaid Yazi preferences: before=%+v after=%+v", before, *target)
	}
	if state.Yazi.Main.Exists || state.Yazi.Keymap.Exists || state.Yazi.Theme.Exists {
		t.Fatalf("resolver failure fabricated file observations: %#v", state.Yazi)
	}
}

func TestYaziSchemasZeroThroughFiveClearPresenceAndHydrateObservedTruth(t *testing.T) {
	for schema := 0; schema <= 5; schema++ {
		t.Run(fmt.Sprintf("schema-%d", schema), func(t *testing.T) {
			dir := prepareNativeYaziUI(t)
			writeNativeYaziUI(t, dir, tools.YaziFileMain, "[mgr]\nshow_hidden = true\nsort_by = \"size\"\nsort_reverse = true\nlinemode = \"permissions\"\nscrolloff = 9\n\n[preview]\nimage_delay = 0\n")
			writeNativeYaziUI(t, dir, tools.YaziFileKeymap, "[mgr]\nkeymap = [{ on = \"<C-n>\", run = \"arrow 1\" }]\n")
			version := ""
			if schema != 0 {
				version = fmt.Sprintf(`"NativeImportSchemaVersion":%d,`, schema)
			}
			data := fmt.Sprintf(`{%s"YaziKeymap":"vim","YaziShowHidden":false,"YaziPreviewMode":"auto","YaziSortBy":"alphabetical","YaziSortReverse":false,"YaziLineMode":"none","YaziScrollOff":3}`, version)
			path := filepath.Join(config.ToolsDir(), "manage.json")
			if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(path, []byte(data), 0o600); err != nil {
				t.Fatal(err)
			}
			presence := inspectManagePreferencePresence()
			if presence.err != nil {
				t.Fatal(presence.err)
			}
			for _, field := range yaziManageFields {
				if presence.fields[field] {
					t.Fatalf("legacy schema retained %s presence", field)
				}
			}
			target := savedYaziPreferences()
			target.NativeImportSchemaVersion = schema
			state := observeNativeManageConfig(target, presence, "dracula")
			assertYaziValues(t, target, "emacs", true, "always", "size", true, "permissions", 9)
			if state.Yazi.Main.Ownership != tools.YaziOwnershipNative || state.Yazi.Keymap.Ownership != tools.YaziOwnershipNative || target.NativeImportSchemaVersion != 6 || state.PreferenceError != "" {
				t.Fatalf("schema migration did not adopt observed truth: target=%+v state=%#v", target, state)
			}
		})
	}
}

func TestYaziThemeObservationNeverMutatesGlobalTheme(t *testing.T) {
	dir := prepareNativeYaziUI(t)
	writeNativeYaziUI(t, dir, tools.YaziFileTheme, "[flavor]\ndark = \"catppuccin-mocha\"\n")
	app := &App{theme: "dracula", manageConfig: NewManageConfig()}
	app.nativeConfigState = observeNativeManageConfig(app.manageConfig, managePreferencePresence{fields: map[string]bool{}, schema: 6}, app.theme)
	if app.theme != "dracula" || !app.nativeConfigState.Yazi.Theme.Exists || app.nativeConfigState.Yazi.Theme.ReadOnlyReason == "" {
		t.Fatalf("Yazi flavor changed global theme or was not observed: theme=%q state=%#v", app.theme, app.nativeConfigState.Yazi)
	}
}

func TestNativeConfigStateClonesYaziProvenance(t *testing.T) {
	app := &App{nativeConfigState: NativeManageConfigState{Yazi: tools.YaziConfigImport{Fields: map[string]tools.ConfigFieldProvenance{tools.YaziFieldShowHidden: {Path: "native", Line: 2}}}}}
	first := app.NativeConfigState()
	delete(first.Yazi.Fields, tools.YaziFieldShowHidden)
	second := app.NativeConfigState()
	if _, ok := second.Yazi.Fields[tools.YaziFieldShowHidden]; !ok {
		t.Fatal("NativeConfigState exposed mutable Yazi provenance")
	}
}

func TestYaziManageDeepDiveRoundTripAndDefaults(t *testing.T) {
	mc := savedYaziPreferences()
	dd := manageConfigToDeepDive(mc)
	got := yaziConfigFrom(dd)
	want := tools.YaziConfig{Keymap: mc.YaziKeymap, ShowHidden: mc.YaziShowHidden, PreviewMode: mc.YaziPreviewMode, SortBy: mc.YaziSortBy, SortReverse: mc.YaziSortReverse, LineMode: mc.YaziLineMode, ScrollOff: mc.YaziScrollOff}
	if got != want {
		t.Fatalf("Manage→DeepDive→Yazi = %#v, want %#v", got, want)
	}
	if NewManageConfig().YaziLineMode != "none" || NewDeepDiveConfig().YaziLineMode != "none" {
		t.Fatal("Yazi default line mode must match upstream none")
	}
}

func prepareNativeYaziUI(t *testing.T) string {
	t.Helper()
	home := withTempHome(t)
	t.Setenv("YAZI_CONFIG_HOME", "")
	t.Setenv("CONFIG_DIR", "")
	t.Setenv("LG_CONFIG_FILE", "")
	dir := filepath.Join(home, ".config", "yazi")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		t.Fatal(err)
	}
	return dir
}

func writeNativeYaziUI(t *testing.T, dir, name, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}

func explicitYaziPreferences(err error) managePreferencePresence {
	fields := map[string]bool{}
	for _, field := range yaziManageFields {
		fields[field] = true
	}
	return managePreferencePresence{exists: true, fields: fields, schema: 6, err: err}
}

func savedYaziPreferences() *ManageConfig {
	target := NewManageConfig()
	target.YaziKeymap = "vim"
	target.YaziShowHidden = false
	target.YaziPreviewMode = "auto"
	target.YaziSortBy = "alphabetical"
	target.YaziSortReverse = false
	target.YaziLineMode = "none"
	target.YaziScrollOff = 3
	return target
}

func assertSavedYaziPreferences(t *testing.T, got *ManageConfig) {
	t.Helper()
	assertYaziValues(t, got, "vim", false, "auto", "alphabetical", false, "none", 3)
}

func assertYaziValues(t *testing.T, got *ManageConfig, keymap string, hidden bool, preview, sort string, reverse bool, line string, scroll int) {
	t.Helper()
	if got.YaziKeymap != keymap || got.YaziShowHidden != hidden || got.YaziPreviewMode != preview || got.YaziSortBy != sort || got.YaziSortReverse != reverse || got.YaziLineMode != line || got.YaziScrollOff != scroll {
		t.Fatalf("Yazi values = %+v; want %s/%t/%s/%s/%t/%s/%d", got, keymap, hidden, preview, sort, reverse, line, scroll)
	}
}

func exactCurrentYaziMain() string {
	return "# Generated by dotfiles TUI\n# Compatibility: Yazi 26.5.6\n\n[mgr]\nsort_by = \"natural\"\nsort_reverse = true\nlinemode = \"permissions\"\nscrolloff = 9\nshow_hidden = true\n\n[preview]\nimage_delay = 30\n\n[plugin]\npreviewers = []\npreloaders = []\n"
}

func exactCurrentYaziVimKeymap() string {
	return "# Generated by dotfiles TUI\n# Compatibility: Yazi 26.5.6\n# Keymap style: vim\n"
}

func exactCurrentYaziEmacsKeymap() string {
	return "# Generated by dotfiles TUI\n# Compatibility: Yazi 26.5.6\n# Keymap style: emacs\n\n[mgr]\nprepend_keymap = [\n  { on = \"<C-p>\", run = \"arrow -1\", desc = \"Move up\" },\n  { on = \"<C-n>\", run = \"arrow 1\", desc = \"Move down\" },\n  { on = \"<C-b>\", run = \"leave\", desc = \"Go to parent\" },\n  { on = \"<C-f>\", run = \"enter\", desc = \"Enter directory\" },\n  { on = \"<Space>\", run = \"toggle\", desc = \"Toggle selection\" },\n]\n"
}
